const distractorAnatomy = {
    subject: 'english', slug: 'distractor-anatomy', moduleId: 'english-reading-method',
    title: 'Distractor Anatomy', minutes: '24 min',
    summary: 'Stop calling wrong answers “tricky.” Learn the small set of evidence failures that makes a tempting choice wrong, then audit every option with precision.',
    goals: ['Recognize recurring distractor patterns.', 'Name the exact defect in a tempting choice.', 'Use elimination as an evidence test rather than a feeling.'],
    openingCheck: {
        prompt: 'A choice accurately repeats a fact from the passage but does not answer why the author included an example. What kind of distractor is it?',
        choices: ['True but irrelevant', 'Reversed relationship', 'Too narrow grammar rule', 'Correct because it is stated'],
        answer: 0,
        explanation: 'An answer can be textually true and still fail the task. Function questions require a role, not merely a repeated fact.',
    },
    concepts: [
        { heading: 'Truth is necessary, not sufficient', body: ['The best distractors borrow real names, claims, and phrases from the passage. Their weakness often appears only when you connect them to the question.', 'Audit in two stages: Is the choice compatible with the text? Does it perform the requested job? A choice must pass both.'], moves: ['Textually valid?', 'Answers this stem?', 'Uses the right scope?', 'Preserves the logic?'] },
        { heading: 'Five recurring failure patterns', body: ['True but irrelevant choices state real information that answers a neighboring question. Half-right choices begin accurately and then add an unsupported claim. Reversed choices flip cause and effect, before and after, or agreement and disagreement. Too-strong choices inflate “may” into “must.” Unsupported choices introduce a new actor, motive, or result.', 'These labels are diagnostic, not magical. Always point to the exact word or relationship causing the failure.'], moves: ['True, wrong job', 'Half-right, then drift', 'Relationship reversed', 'Stronger than evidence', 'New story'] },
        { heading: 'Eliminate with a because-clause', body: ['“I don’t like B” teaches you nothing. “B is wrong because the passage links lower temperature to slower growth, while B reverses that direction” creates a reusable skill.', 'On hard questions, write or think the minimum decisive reason. If you cannot name it, the elimination is not yet stable.'], moves: ['Quote the costly word', 'Name the broken relationship', 'Connect it to evidence', 'Keep the reason transferable'] },
    ],
    workedExample: {
        skill: 'Choice audit',
        passage: 'Composer Elena Park incorporated recordings of train brakes into a chamber work. Rather than imitating a station, Park stretched and layered the recordings until their source was difficult to identify. She wanted listeners to notice the boundary between instrumental tone and environmental noise.',
        question: 'Which choice best describes Park’s purpose in transforming the recordings?',
        prediction: 'To blur or investigate the distinction between musical and environmental sound, not to recreate a station.',
        choices: [
            { text: 'To reproduce the sound of a train station as accurately as possible', verdict: 'Reversed', analysis: 'The source became difficult to identify; accurate reproduction was not the goal.' },
            { text: 'To examine how environmental noise can approach the sound world of instruments', verdict: 'Best', analysis: 'This matches the stated interest in the boundary between the two.' },
            { text: 'To show that train brakes are unpleasant to most listeners', verdict: 'Unsupported', analysis: 'No listener preference is reported.' },
            { text: 'To include recordings because chamber works normally require them', verdict: 'New rule', analysis: 'The passage gives a specific artistic purpose, not a genre requirement.' },
        ],
        answer: 1,
        decision: 'Choice A shares the train-station topic but reverses the transformation’s purpose. Vocabulary overlap cannot repair broken logic.',
    },
    takeaways: {
        rule: 'For every tempting wrong choice, name the exact defect: wrong job, half-right drift, reversal, overstatement, or unsupported addition.',
        highScore: 'At 700+, the final pair often differs by one modifier or relationship. Do not reread the whole passage equally; compare the two choices word by word and retrieve only the evidence that adjudicates their difference.',
        checklist: ['Does it answer this question?', 'Where does it stop being supported?', 'Is any relationship flipped?', 'Which word costs more evidence?'],
    },
    practiceSet: {
        title: 'Name the trap, then remove it', intro: 'Correctness matters; so does diagnosing why each alternative fails.',
        questions: [
            { id: 'distractor-irrelevant', difficulty: 'Foundation', skill: 'Central idea', passage: 'Engineer Sol Vega tested window films designed to reduce summer heat indoors. One film blocked slightly less light than the others while reducing indoor temperature by nearly the same amount. Vega argues that this film may suit rooms where daylight is especially valued.', question: 'Which choice best states the main idea?', choices: ['Window films are tested by engineers.', 'One film may balance heat reduction with preserving daylight.', 'All window films completely prevent indoor heating.', 'Vega prefers rooms with large windows.'], answer: 1, explanation: { whyCorrect: 'It states the study’s meaningful comparison and practical conclusion.', choices: ['True but irrelevant: it names an activity, not the finding.', 'Correct: comparison plus qualified use.', 'Too strong: “all” and “completely” are unsupported.', 'Unsupported: Vega’s personal preference is not discussed.'], takeaway: 'A topic statement is not automatically a main idea.' } },
            { id: 'distractor-half', difficulty: 'Core', skill: 'Inference', passage: 'Before the bridge opened, the island ferry ran twelve trips daily. The bridge then carried most commuter traffic, but the ferry continued six daily trips and added weekend sightseeing routes.', question: 'Which inference is best supported?', choices: ['The bridge reduced the ferry’s commuter role, though the ferry continued operating in a changed form.', 'The bridge reduced ferry trips and forced the ferry company to close.', 'Weekend visitors were the only people who ever used the ferry.', 'The bridge was built primarily to promote sightseeing.'], answer: 0, explanation: { whyCorrect: 'It combines the reduced daily schedule with the new sightseeing service.', choices: ['Correct: both decline and continuation.', 'Half-right then contradicted: trips fell, but service continued.', 'Too strong: “only” and “ever” are not supported.', 'Reversed motive: a later ferry change does not establish why the bridge was built.'], takeaway: 'Watch for choices that earn their first clause and invent their second.' } },
            { id: 'distractor-reversal', difficulty: 'Advanced', skill: 'Command of evidence', passage: 'A botanist hypothesizes that cooler nighttime temperatures delay the flowering of a certain alpine plant.', question: 'Which result would most directly weaken the hypothesis?', choices: ['Plants in cooler nights flower significantly earlier than plants in otherwise identical warmer nights.', 'Cooler nights occur more often at higher elevations.', 'The plant’s flowers vary in color.', 'Plants in both groups receive equal daylight.'], answer: 0, explanation: { whyCorrect: 'Earlier flowering under the proposed delaying condition directly reverses the predicted effect.', choices: ['Correct: same condition and outcome, opposite direction.', 'This provides context, not a flowering comparison.', 'Color does not test timing.', 'Equal daylight controls a variable but supplies no outcome.'], takeaway: 'For support and weaken questions, track the predicted direction before reading choices.' } },
            { id: 'distractor-700', difficulty: '700+ Lens', skill: 'Text structure', passage: 'Economist Ren Ito first presents a model predicting that remote work will reduce downtown lunch sales. Ito then notes that the model treats all workers as equally likely to buy lunch near an office, although survey data show large differences by occupation. Ito therefore recommends testing occupation-specific versions of the model.', question: 'What is the main function of the survey-data sentence?', choices: ['It disproves the possibility that remote work affects lunch sales.', 'It identifies a simplifying assumption that motivates refining the model.', 'It supplies the model’s final occupation-specific results.', 'It shows that occupation is the sole cause of lunch-buying behavior.'], answer: 1, explanation: { whyCorrect: 'The sentence exposes heterogeneity omitted by the model, leading directly to the refinement recommendation.', choices: ['Too broad: questioning an assumption does not disprove the entire effect.', 'Correct: limitation that motivates next step.', 'Reversed sequence: the versions are recommended, not already tested.', 'Too strong: differences by occupation do not establish sole causation.'], takeaway: 'The hardest distractors often misstate what a limitation does: refine a claim, not necessarily erase it.' } },
        ],
    },
    reflection: { prompt: 'Take one miss and complete: “I chose ___ because ___. It fails because the word/relationship ___ is not supported.”', steps: ['Name the attraction honestly.', 'Label the failure pattern.', 'Point to the decisive evidence.', 'Write one warning you can reuse.'] },
};

export default distractorAnatomy;
