const perimeterAreaAndCompositeFigures = {
    slug:'perimeter-area-and-composite-figures',moduleId:'area-volume-trig',title:'Perimeter, Area & Composite Figures',eyebrow:'Geometry and Trigonometry',minutes:'38 min',
    summary:'Translate diagrams and word problems into perimeter and area equations for polygons, circles, composites, and algebraic dimensions.',
    goals:['Choose the correct perimeter or area formula and units.','Use bases and perpendicular heights correctly.','Add and subtract component regions.','Build equations when dimensions contain variables or constraints.'],
    facts:[{label:'Rectangle',math:'A=lw',note:'perimeter 2l+2w'},{label:'Triangle',math:'A=\\frac12bh',note:'height is perpendicular to base'},{label:'Parallelogram',math:'A=bh',note:'not side times slanted side'},{label:'Trapezoid',math:'A=\\frac12(b_1+b_2)h',note:'average of parallel bases times height'}],
    sections:[
        {heading:'Big idea 1: perimeter traces; area fills',paragraphs:['Perimeter adds exposed boundary lengths. Area measures two-dimensional interior and uses square units.','In composite shapes, an internal shared edge does not belong to the outside perimeter unless the path actually traces it.']},
        {heading:'Big idea 2: height means perpendicular distance',paragraphs:['Triangle, parallelogram, and trapezoid area formulas require a height perpendicular to the chosen base. A slanted side is not automatically a height.','If height is hidden, use a right triangle, coordinate difference, or area relationship to find it.']},
        {heading:'Big idea 3: decompose before calculating',paragraphs:['Split a figure into familiar rectangles, triangles, or circle parts, or subtract a cutout from a larger shape. Choose divisions that avoid unknown lengths.','Write one line showing the region equation before substituting numbers.']},
        {heading:'Big idea 4: harder problems make dimensions algebraic',paragraphs:['A fixed perimeter can express one side in terms of another and create a quadratic area model. Similarity or scale may determine dimensions indirectly.','Apply positivity and stated bounds to any algebraic solutions.']},
    ],
    formulas:[
        {label:'Triangle area',math:'A=\\frac12bh',note:'Any side can serve as base if its perpendicular height is known.',meaning:'A triangle is half a matching parallelogram.',useWhen:'A base and perpendicular altitude are available.'},
        {label:'Trapezoid area',math:'A=\\frac{b_1+b_2}{2}h',note:'b one and b two are parallel.',meaning:'Use the average parallel width across the height.',useWhen:'Exactly one pair of opposite sides is parallel.'},
        {label:'Regular polygon area',math:'A=\\frac12aP',note:'a is apothem and P is perimeter.',meaning:'Split the polygon into center-based triangles.',useWhen:'A regular polygon gives apothem or central triangles.'},
        {label:'Composite region',math:'A_{wanted}=\\sum A_{added}-\\sum A_{removed}',note:'Keep exact values through the final combination.',meaning:'Nonoverlapping familiar pieces reconstruct the region.',useWhen:'A shape has cutouts, overlaps, or curved boundaries.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Use a perpendicular height',prompt:'A triangle has base 14 and height 9. Find its area.',math:'A=\\frac12(14)(9)',steps:[{text:'Evaluate.',math:'A=63'}],insight:'The height need not be a side of the triangle.',trap:'Do not omit the one-half factor.'},
        {level:'Core SAT',title:'Subtract a cutout',prompt:'A 12-by-10 rectangle has a 4-by-3 rectangular corner removed. Find the remaining area.',math:'A=12(10)-4(3)',steps:[{text:'Subtract.',math:'A=120-12=108'}],insight:'A region equation makes the geometry explicit.',trap:'The removed edges may change perimeter, but the question asks area.'},
        {level:'Advanced',title:'Build an area equation',prompt:'A rectangle has perimeter 50 and area 144. Find its longer side.',math:'l+w=25,\\quad lw=144',steps:[{text:'Substitute width.',math:'l(25-l)=144'},{text:'Factor.',math:'l^2-25l+144=0\\Rightarrow(l-9)(l-16)=0'},{text:'Choose the longer side.',math:'16'}],insight:'The two roots are the two side lengths.',trap:'Half the perimeter, not the full perimeter, equals length plus width.'},
    ],
    strategyCards:[{title:'Label before formula',items:['Mark base and perpendicular height.','Separate boundary from interior.','Write units beside the target.']},{title:'For composite shapes',items:['Outline the desired region.','Add simple pieces or subtract cutouts.','Avoid double-counting overlap.']},{title:'For algebraic dimensions',items:['Translate the constraint first.','Use area second.','Reject nonpositive or out-of-range roots.']}],
    studyTips:[{title:'Redraw with named pieces',summary:'A rough decomposition is more useful than a polished original diagram.',items:['Extend missing rectangle edges.','Drop perpendicular altitudes.','Label whole dimensions as sums of parts.']}],
    adaptiveDemo:{title:'Which length is height?',prompt:'A parallelogram has slanted side 7, base 12, and perpendicular distance between bases 5.',options:[{id:'height',label:'5',result:'Correct.',advice:'Area is base times perpendicular separation.'},{id:'slant',label:'7',result:'The slanted side is not perpendicular to the base.',advice:'Look for the right-angle marker.'}]},
    quickCheck:{prompt:'A trapezoid has parallel bases 8 and 14 and height 6. What is its area?',choices:['44','66','84','132'],choiceMath:true,answer:1,explanation:'Average the bases to get eleven, then multiply by height six for sixty-six.'},
    practiceSet:{title:'Area and composite figures',intro:'Identify the desired region and perpendicular dimensions.',questions:[
        {id:'area-parallelogram',difficulty:'Foundation',skill:'Parallelogram',title:'Use perpendicular height',stem:'A parallelogram has base 15 and height 8. Find its area.',choices:['60','92','120','240'],choiceMath:true,answer:2,explanation:{steps:[{text:'Multiply base by height.',math:'15(8)=120'}],trap:'No one-half factor applies.',takeaway:'A parallelogram uses base times perpendicular height.'}},
        {id:'area-trapezoid',difficulty:'Core',skill:'Trapezoid',title:'Average the bases',stem:'A trapezoid has bases 5 and 13 and height 7. Find its area.',choices:['49','63','91','126'],choiceMath:true,answer:1,explanation:{steps:[{text:'Average bases and multiply.',math:'((5+13)/2)(7)=9(7)=63'}],trap:'Add only the parallel sides in the formula.',takeaway:'Trapezoid area is average base length times height.'}},
        {id:'area-shaded',difficulty:'Core',skill:'Composite area',title:'Subtract a triangle',stem:'A 10-by-8 rectangle contains a triangular cutout with base 6 and height 4. Find the remaining area.',choices:['56','68','72','80'],choiceMath:true,answer:1,explanation:{steps:[{text:'Rectangle minus triangle.',math:'80-\\frac12(6)(4)=80-12=68'}],trap:'The cutout area is twelve, not twenty-four.',takeaway:'Calculate complete component regions.'}},
        {id:'area-fixed-perim',difficulty:'Advanced',skill:'Optimization',title:'Maximize a rectangle',stem:'A rectangle has perimeter 40. What is its maximum possible area?',choices:['80','96','100','400'],choiceMath:true,answer:2,explanation:{steps:[{text:'Length plus width is twenty.'},{text:'The product is greatest when the sides are equal.',math:'10\\cdot10=100'}],trap:'Forty is the full perimeter.',takeaway:'For fixed perimeter, a square maximizes rectangular area.'}},
        {id:'area-regular',difficulty:'Advanced',skill:'Regular polygons',title:'Use apothem and perimeter',stem:'A regular polygon has apothem 6 and perimeter 40. Find its area.',choices:['120','180','240','480'],choiceMath:true,answer:0,explanation:{steps:[{text:'Apply one-half apothem times perimeter.',math:'A=\\frac12(6)(40)=120'}],trap:'The one-half accounts for triangular decomposition.',takeaway:'Regular polygon area is half aP.'}},
    ]},
};

const surfaceAreaAndVolume = {
    slug:'surface-area-and-volume',moduleId:'area-volume-trig',title:'Surface Area & Volume',eyebrow:'Geometry and Trigonometry',minutes:'42 min',
    summary:'Model prisms, cylinders, pyramids, cones, spheres, and composite solids while distinguishing capacity from exterior material.',
    goals:['Choose surface area or volume from context.','Use base area and perpendicular height in solid formulas.','Solve backward for a missing dimension.','Compare or combine solids using ratios and displaced volume.'],
    facts:[{label:'Prism or cylinder',math:'V=Bh',note:'constant cross section'},{label:'Pyramid or cone',math:'V=\\frac13Bh',note:'same base and height gives one third'},{label:'Sphere',math:'V=\\frac43\\pi r^3',note:'surface area 4 pi r squared'},{label:'Rectangular prism',math:'V=lwh',note:'surface area 2lw+2lh+2wh'}],
    sections:[
        {heading:'Big idea 1: volume fills; surface area wraps',paragraphs:['Volume measures capacity in cubic units. Surface area totals exposed faces in square units. Words such as holds, filled, displaced, or capacity suggest volume; paint, label, metal, or exterior suggest surface area.','Open containers omit a face from surface area, so read the description carefully.']},
        {heading:'Big idea 2: B is an area, not a side length',paragraphs:['In V equals B h, B is the full base area. For a cylinder B is pi r squared; for a triangular prism B may be one-half base times triangle height.','The solid height is perpendicular distance between bases or from vertex to base.']},
        {heading:'Big idea 3: pointed solids carry a one-third factor',paragraphs:['A cone or pyramid with the same base and height as a cylinder or prism has one third the volume. This relationship is often faster than computing two full formulas.','Do not use slant height in a volume formula.']},
        {heading:'Big idea 4: hard questions reverse or combine formulas',paragraphs:['Set the given volume equal to the correct formula and solve for the missing dimension, taking a cube root or square root only when required.','Composite volumes add nonoverlapping solids or subtract holes. Displacement equates object volume with the increase in container volume.']},
    ],
    formulas:[
        {label:'Prism and cylinder volume',math:'V=Bh',note:'For a cylinder, B equals pi r squared.',meaning:'A constant cross-sectional area extends through height h.',useWhen:'The solid has matching parallel bases.'},
        {label:'Pyramid and cone volume',math:'V=\\frac13Bh',note:'Height is perpendicular, not slanted.',meaning:'A pointed solid occupies one third of its matching prism or cylinder.',useWhen:'The solid narrows to one vertex.'},
        {label:'Sphere measures',math:'V=\\frac43\\pi r^3,\\qquad S=4\\pi r^2',note:'Volume uses cubic radius; surface uses squared radius.',meaning:'The two targets scale differently with size.',useWhen:'A ball, globe, or spherical cavity appears.'},
        {label:'Cylinder surface area',math:'S=2\\pi r^2+2\\pi rh',note:'For an open cylinder, remove the missing base term.',meaning:'Two circular bases plus an unwrapped rectangular side.',useWhen:'Material covers the outside of a cylinder.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find cylinder volume',prompt:'A cylinder has radius 4 and height 9. Find its volume.',math:'V=\\pi(4)^2(9)',steps:[{text:'Evaluate.',math:'V=144\\pi'}],insight:'The radius belongs inside the square.',trap:'Do not use diameter eight as r.'},
        {level:'Core SAT',title:'Reverse a cone formula',prompt:'A cone has volume 100 pi and height 12. Find its radius.',math:'100\\pi=\\frac13\\pi r^2(12)',steps:[{text:'Simplify.',math:'100=4r^2'},{text:'Take the positive root.',math:'r=5'}],insight:'Pi cancels before arithmetic.',trap:'The equation first gives r squared equals twenty-five.'},
        {level:'Advanced',title:'Use displacement',prompt:'A solid sphere of radius 3 is submerged in a cylinder of radius 6. By how much does the water height rise?',math:'\\pi(6)^2\\Delta h=\\frac43\\pi(3)^3',steps:[{text:'Simplify volumes.',math:'36\\pi\\Delta h=36\\pi'},{text:'Solve.',math:'\\Delta h=1'}],insight:'Displaced water volume equals object volume.',trap:'The final cylinder height is not needed; only its change is.'},
    ],
    strategyCards:[{title:'Read the noun',items:['Capacity or displacement: volume.','Paint or wrapper: surface area.','Open top: omit one face.']},{title:'Build the base first',items:['Circle base: pi r squared.','Triangle base: one-half b h.','Then multiply by solid height.']},{title:'Reverse safely',items:['Isolate the power of the dimension.','Take the positive root.','Check units and physical constraints.']}],
    studyTips:[{title:'Write B explicitly',summary:'Expanding the base area prevents missing a square or one-half.',items:['Cylinder: B equals pi r squared.','Triangular prism: B equals one-half triangle base times triangle altitude.','Then apply the solid formula.']}],
    adaptiveDemo:{title:'Cone or cylinder?',prompt:'A cone and cylinder share radius and height.',options:[{id:'third',label:'Cone is 1/3',result:'Correct.',advice:'The shared base and height make the comparison immediate.'},{id:'same',label:'Volumes are equal',result:'The cone narrows to a point.',advice:'Include the one-third factor.'}]},
    quickCheck:{prompt:'A cube has volume 216. What is its surface area?',choices:['36','72','216','1,296'],choiceMath:true,answer:2,explanation:'The edge is the cube root of two hundred sixteen, or six. Six square faces each have area thirty-six, for total surface area two hundred sixteen.'},
    practiceSet:{title:'Surface area and volume',intro:'Identify the solid, target, base area, and perpendicular height.',questions:[
        {id:'volume-prism',difficulty:'Foundation',skill:'Rectangular prism',title:'Multiply dimensions',stem:'A rectangular prism is 3 by 5 by 8. Find its volume.',choices:['40','80','120','240'],choiceMath:true,answer:2,explanation:{steps:[{text:'Multiply length, width, and height.',math:'3(5)(8)=120'}],trap:'Volume uses cubic units.',takeaway:'A rectangular prism has constant rectangular cross section.'}},
        {id:'volume-pyramid',difficulty:'Core',skill:'Pyramid',title:'Include one third',stem:'A pyramid has base area 54 and height 10. Find its volume.',choices:['180','270','540','1,620'],choiceMath:true,answer:0,explanation:{steps:[{text:'Apply one third B h.',math:'V=\\frac13(54)(10)=180'}],trap:'Do not use the prism formula.',takeaway:'Pointed solids use one third.'}},
        {id:'surface-cylinder',difficulty:'Core',skill:'Surface area',title:'Wrap a closed cylinder',stem:'A closed cylinder has radius 3 and height 5. Find total surface area.',choices:['30π','39π','48π','90π'],choiceMath:true,answer:2,explanation:{steps:[{text:'Add bases and side.',math:'2\\pi(3)^2+2\\pi(3)(5)=18\\pi+30\\pi=48\\pi'}],trap:'Closed means include both bases.',takeaway:'Cylinder surface is two disks plus one rectangular wrap.'}},
        {id:'volume-sphere-ratio',difficulty:'Advanced',skill:'Scaling',title:'Compare spheres',stem:'Sphere B has twice the radius of sphere A. What is the volume ratio B to A?',choices:['2:1','4:1','6:1','8:1'],answer:3,explanation:{steps:[{text:'Volume follows radius cubed.',math:'2^3=8'}],trap:'Four is the surface-area scale.',takeaway:'Volume uses the cube of linear scale.'}},
        {id:'volume-composite',difficulty:'Advanced',skill:'Composite solids',title:'Subtract a cylindrical hole',stem:'A cylinder of radius 5 and height 8 has a cylindrical hole of radius 2 drilled through the full height. Find remaining volume.',choices:['32π','168π','200π','232π'],choiceMath:true,answer:1,explanation:{steps:[{text:'Subtract volumes with shared height.',math:'\\pi(5^2-2^2)(8)=\\pi(21)(8)=168\\pi'}],trap:'Subtract squared radii, not radii before squaring.',takeaway:'Composite volume is outer minus removed volume.'}},
    ]},
};

const scaleFactorsAndGeometryUnits = {
    slug:'scale-factors-and-geometry-units',moduleId:'area-volume-trig',title:'Scale Factors & Geometry Units',eyebrow:'Geometry and Trigonometry',minutes:'37 min',
    summary:'Track how length, area, surface area, and volume change under scaling and convert squared or cubed units without linear-unit mistakes.',
    goals:['Apply k, k squared, and k cubed to geometric measures.','Recover a length factor from area or volume ratios.','Convert square and cubic units correctly.','Use density and capacity units in geometry contexts.'],
    facts:[{label:'Length',math:'\\times k',note:'also perimeter'},{label:'Area',math:'\\times k^2',note:'also surface area'},{label:'Volume',math:'\\times k^3',note:'cubic measure'},{label:'Unit conversion',math:'(a\\text{ units})^n',note:'raise the conversion factor to the dimension'}],
    sections:[
        {heading:'Big idea 1: count independent dimensions',paragraphs:['Lengths and perimeters are one-dimensional, areas and surface areas are two-dimensional, and volumes are three-dimensional. That count becomes the exponent on the scale factor.','A ten percent length increase uses k equals 1.10, so area multiplies by 1.21 and volume by 1.331.']},
        {heading:'Big idea 2: reverse scaling with roots',paragraphs:['Take a square root of an area ratio to recover a length ratio and a cube root of a volume ratio to recover a length ratio. Use positive roots for physical dimensions.','Do not subtract percentages until after finding the new multiplier.']},
        {heading:'Big idea 3: unit conversions also use powers',paragraphs:['If one foot equals twelve inches, one square foot equals 144 square inches and one cubic foot equals 1,728 cubic inches.','Write the conversion factor as a fraction whose unwanted unit cancels, then square or cube the entire fraction.']},
        {heading:'Big idea 4: derived quantities link geometry to rates',paragraphs:['Density is mass per volume. Cost can be price per area, and flow can be volume per time. Track both numerator and denominator units.','Convert quantities to compatible units before using a rate.']},
    ],
    formulas:[
        {label:'Similarity scaling',math:'L_2=kL_1,\\quad A_2=k^2A_1,\\quad V_2=k^3V_1',note:'Surface area follows the area rule.',meaning:'Each independent dimension contributes one factor of k.',useWhen:'All dimensions of similar figures change uniformly.'},
        {label:'Reverse scale',math:'k=\\sqrt{A_2/A_1}=\\sqrt[3]{V_2/V_1}',note:'Choose the expression matching the given measure.',meaning:'Roots undo dimensional powers.',useWhen:'Area or volume ratio is known but side ratio is requested.'},
        {label:'Powered conversion',math:'1\\text{ ft}^2=(12\\text{ in})^2=144\\text{ in}^2',note:'Cube the factor for cubic units.',meaning:'Every coordinate direction requires the unit conversion.',useWhen:'Converting area or volume units.'},
        {label:'Density',math:'\\rho=\\frac{m}{V}',note:'Rearrange to m equals rho V or V equals m over rho.',meaning:'Density links an object’s mass with the space it occupies.',useWhen:'A geometric solid has mass or material density.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Scale area',prompt:'Every side of a figure triples. By what factor does area change?',math:'k^2=3^2',steps:[{text:'Evaluate.',math:'9'}],insight:'Area has two dimensions.',trap:'Tripling sides does not merely triple area.'},
        {level:'Core SAT',title:'Convert square units',prompt:'Convert 5 square yards to square feet.',math:'5\\text{ yd}^2\\left(\\frac{3\\text{ ft}}{1\\text{ yd}}\\right)^2',steps:[{text:'Square the linear factor.',math:'5(9)=45\\text{ ft}^2'}],insight:'Each yard dimension becomes three feet.',trap:'Multiplying by three only converts a length.'},
        {level:'Advanced',title:'Reverse a volume increase',prompt:'Two similar solids have volume ratio 125 to 27. Find the side ratio.',math:'k=\\sqrt[3]{125/27}',steps:[{text:'Take cube roots.',math:'k=5/3'}],insight:'Volume ratios hide a cubic length relationship.',trap:'Do not take a square root of a volume ratio.'},
    ],
    strategyCards:[{title:'Label the dimension',items:['Length or perimeter: power one.','Area or surface area: power two.','Volume: power three.']},{title:'For percent scaling',items:['Convert percent change to multiplier k.','Raise k to the correct power.','Subtract one only to report percent change.']},{title:'For units',items:['Write a cancelling fraction.','Raise the full conversion to the dimension.','Check final unit exponent.']}],
    studyTips:[{title:'Use a one-unit model',summary:'Imagine a one-by-one square or one-by-one-by-one cube.',items:['Scale each edge by k.','Count how many k factors multiply.','This reconstructs k squared or k cubed.']}],
    adaptiveDemo:{title:'Select the exponent',prompt:'A model car is built at one-fourth the real car’s linear dimensions.',options:[{id:'volume',label:'Volume is 1/64',result:'Correct: one fourth cubed is one sixty-fourth.',advice:'Three-dimensional capacity uses k cubed.'},{id:'area',label:'Volume is 1/16',result:'One sixteenth is the surface-area scale.',advice:'Volume has three independent dimensions.'}]},
    quickCheck:{prompt:'A square’s side increases by 20 percent. By what percent does its area increase?',choices:['20%','40%','44%','144%'],answer:2,explanation:'The length factor is one point two. Squaring gives one point four four, which is a forty-four percent increase.'},
    practiceSet:{title:'Scale and geometry units',intro:'Attach a dimensional exponent to every scale or conversion.',questions:[
        {id:'scale-perim',difficulty:'Foundation',skill:'Length scale',title:'Scale a perimeter',stem:'All lengths double. By what factor does perimeter change?',choices:['2','4','6','8'],choiceMath:true,answer:0,explanation:{steps:[{text:'Perimeter is linear.',math:'k=2'}],trap:'Do not square a length sum.',takeaway:'Perimeter follows k.'}},
        {id:'scale-surface',difficulty:'Core',skill:'Area scale',title:'Scale surface area',stem:'A cube’s edge triples. By what factor does surface area change?',choices:['3','6','9','27'],choiceMath:true,answer:2,explanation:{steps:[{text:'Surface area is two-dimensional.',math:'3^2=9'}],trap:'Twenty-seven is the volume factor.',takeaway:'Surface area follows k squared.'}},
        {id:'scale-cubic-unit',difficulty:'Core',skill:'Unit conversion',title:'Convert cubic feet',stem:'How many cubic inches are in 2 cubic feet?',choices:['24','288','1,728','3,456'],choiceMath:true,answer:3,explanation:{steps:[{text:'Cube the twelve-inch conversion.',math:'2(12^3)=2(1728)=3456'}],trap:'The conversion factor must be cubed.',takeaway:'Cubic units require three conversion factors.'}},
        {id:'scale-percent-volume',difficulty:'Advanced',skill:'Percent scaling',title:'Scale volume by a percent',stem:'Every dimension increases by 10 percent. By what percent does volume increase?',choices:['10%','21%','30%','33.1%'],answer:3,explanation:{steps:[{text:'Cube the length multiplier.',math:'1.1^3=1.331'},{text:'Convert to increase.',math:'33.1\\%'}],trap:'Thirty percent simply adds three ten-percent changes and misses interaction.',takeaway:'Raise the multiplier before converting back to percent.'}},
        {id:'scale-density',difficulty:'Advanced',skill:'Density',title:'Find mass from geometry',stem:'A rectangular solid has volume 24 cubic centimeters and density 2.5 grams per cubic centimeter. Find its mass.',choices:['9.6 g','26.5 g','60 g','600 g'],answer:2,explanation:{steps:[{text:'Multiply density by volume.',math:'m=(2.5)(24)=60\\text{ g}'}],trap:'Cubic-centimeter units cancel.',takeaway:'Track numerator and denominator units.'}},
    ]},
};

const sineCosineAndTangent = {
    slug:'sine-cosine-and-tangent',moduleId:'area-volume-trig',title:'Sine, Cosine & Tangent',eyebrow:'Geometry and Trigonometry',minutes:'40 min',
    summary:'Use right-triangle ratios as side relationships, connect complementary angles, and solve for missing sides or angles efficiently.',
    goals:['Label opposite, adjacent, and hypotenuse relative to an angle.','Choose sine, cosine, or tangent from known and requested sides.','Use complementary-angle identities and similar-triangle invariance.','Use inverse trig for an angle and preserve calculator mode.'],
    facts:[{label:'Sine',math:'\\sin\\theta=\\frac{opp}{hyp}',note:'SOH'},{label:'Cosine',math:'\\cos\\theta=\\frac{adj}{hyp}',note:'CAH'},{label:'Tangent',math:'\\tan\\theta=\\frac{opp}{adj}',note:'TOA'},{label:'Complements',math:'\\sin\\theta=\\cos(90^\\circ-\\theta)',note:'opposite and adjacent swap'}],
    sections:[
        {heading:'Big idea 1: side names depend on the chosen angle',paragraphs:['The hypotenuse is fixed opposite the right angle. Opposite and adjacent swap when you switch between the two acute angles.','Mark the reference angle before labeling sides.']},
        {heading:'Big idea 2: choose the ratio containing exactly what you need',paragraphs:['If opposite and hypotenuse are involved, use sine; adjacent and hypotenuse use cosine; opposite and adjacent use tangent.','Write the symbolic ratio first, then substitute. This prevents calculator-first guessing.']},
        {heading:'Big idea 3: similar right triangles share trig ratios',paragraphs:['All right triangles with the same acute angle are similar, so their side ratios are constant. SAT questions can ask for a trig value from side relationships without asking for the angle.','Simplify the ratio exactly before using decimals.']},
        {heading:'Big idea 4: inverse trig returns an angle',paragraphs:['Use inverse sine, cosine, or tangent after isolating a side ratio. Keep the calculator in degree mode unless radians are explicitly requested.','Round only at the end and to the requested precision.']},
    ],
    formulas:[
        {label:'Right-triangle ratios',math:'\\sin\\theta=\\frac{o}{h},\\quad\\cos\\theta=\\frac{a}{h},\\quad\\tan\\theta=\\frac{o}{a}',note:'All side roles are relative to theta.',meaning:'Trig records proportions in similar right triangles.',useWhen:'A right triangle connects an angle and sides.'},
        {label:'Complementary ratios',math:'\\sin\\theta=\\cos(90^\\circ-\\theta),\\quad\\tan\\theta=\\frac1{\\tan(90^\\circ-\\theta)}',note:'The two acute angles are complementary.',meaning:'Switching angles swaps opposite and adjacent.',useWhen:'A question gives one ratio and asks about the other acute angle.'},
        {label:'Pythagorean identity',math:'\\sin^2\\theta+\\cos^2\\theta=1',note:'SAT may use this in exact-value questions.',meaning:'It is the unit-circle form of the Pythagorean theorem.',useWhen:'One of sine or cosine is known and the other is requested for an acute angle.'},
        {label:'Inverse trig',math:'\\theta=\\tan^{-1}\\left(\\frac{o}{a}\\right)',note:'Use the inverse matching the known ratio.',meaning:'Inverse trig converts a side ratio into an angle.',useWhen:'The target is an acute angle measure.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find a sine ratio',prompt:'Relative to angle A, opposite side is 8 and hypotenuse is 17. Find sine A.',math:'\\sin A=8/17',steps:[{text:'Use opposite over hypotenuse.'}],insight:'No angle calculation is required.',trap:'Side names depend on angle A.'},
        {level:'Core SAT',title:'Solve for a side',prompt:'A right triangle has angle 35 degrees, adjacent leg 12, and opposite leg x. Find x.',math:'\\tan35^\\circ=x/12',steps:[{text:'Multiply.',math:'x=12\\tan35^\\circ'},{text:'Approximate at the end.',math:'x\\approx8.4'}],insight:'Tangent avoids the unused hypotenuse.',trap:'Use degree mode.'},
        {level:'Advanced',title:'Use a complement without a triangle',prompt:'If sine 28 degrees equals k, what is cosine 62 degrees?',math:'62^\\circ=90^\\circ-28^\\circ',steps:[{text:'Apply the cofunction identity.',math:'\\cos62^\\circ=\\sin28^\\circ=k'}],insight:'Complementary ratios can remove all computation.',trap:'The values are equal, not reciprocal.'},
    ],
    strategyCards:[{title:'Label from theta',items:['Hypotenuse: opposite 90 degrees.','Opposite: across from theta.','Adjacent: touching theta but not hypotenuse.']},{title:'Choose the ratio',items:['Circle the known side.','Circle the requested side.','Use the ratio containing both.']},{title:'Calculator discipline',items:['Check degree or radian mode.','Keep full precision through steps.','Round only to requested place.']}],
    studyTips:[{title:'Say SOH-CAH-TOA with nouns',summary:'Words prevent letter-pattern confusion.',items:['Sine is opposite over hypotenuse.','Cosine is adjacent over hypotenuse.','Tangent is opposite over adjacent.']}],
    adaptiveDemo:{title:'Choose the efficient ratio',prompt:'You know the adjacent and opposite legs and need the angle.',options:[{id:'tan',label:'Inverse tangent',result:'Correct.',advice:'Tangent connects the two legs directly.'},{id:'sin',label:'Inverse sine',result:'That would require the hypotenuse.',advice:'Choose a ratio using only known quantities.'}]},
    quickCheck:{prompt:'In a right triangle, sin A = 5/13. What is cos B for the other acute angle B?',choices:['5/13','12/13','5/12','12/5'],choiceMath:true,answer:0,explanation:'A and B are complementary, so cosine B equals sine A, which is five thirteenths.'},
    practiceSet:{title:'Right-triangle trig',intro:'Mark the reference angle, side roles, and calculator mode.',questions:[
        {id:'trig-ratio',difficulty:'Foundation',skill:'Cosine',title:'Build a ratio',stem:'Adjacent leg is 9 and hypotenuse is 15. Find cosine theta.',choices:['3/5','5/3','9/6','12/15'],choiceMath:true,answer:0,explanation:{steps:[{text:'Cosine is adjacent over hypotenuse.',math:'9/15=3/5'}],trap:'Simplify the ratio.',takeaway:'CAH means adjacent over hypotenuse.'}},
        {id:'trig-side',difficulty:'Core',skill:'Sine',title:'Find an opposite side',stem:'A right triangle has hypotenuse 20 and angle 30 degrees. Find the opposite side.',choices:['5','10','10√3','20√3'],answer:1,explanation:{steps:[{text:'Use sine.',math:'\\sin30^\\circ=x/20'},{text:'Since sine thirty is one half.',math:'x=10'}],trap:'The opposite-thirty side is the short leg.',takeaway:'Trig and special-triangle ratios agree.'}},
        {id:'trig-complement',difficulty:'Core',skill:'Complements',title:'Swap sine and cosine',stem:'If cos 37 degrees equals p, which expression also equals p?',choices:['sin 37°','sin 53°','cos 53°','tan 53°'],answer:1,explanation:{steps:[{text:'Find the complement.',math:'90-37=53'},{text:'Use cosine theta equals sine complement.',math:'\\cos37^\\circ=\\sin53^\\circ'}],trap:'Complementary, not equal, angle measures swap sine and cosine.',takeaway:'Cofunctions match across complementary angles.'}},
        {id:'trig-identity',difficulty:'Advanced',skill:'Exact values',title:'Recover cosine',stem:'For acute theta, sine theta equals 7 over 25. Find cosine theta.',choices:['18/25','24/25','7/24','25/24'],choiceMath:true,answer:1,explanation:{steps:[{text:'Use a right triangle or identity.',math:'a=\\sqrt{25^2-7^2}=24'},{text:'Form cosine.',math:'24/25'}],trap:'Acute angle makes cosine positive.',takeaway:'Pythagorean structure connects sine and cosine.'}},
        {id:'trig-parameter',difficulty:'Advanced',skill:'Similar triangles',title:'Use a shared angle ratio',stem:'Two right triangles share acute angle theta. In the first, opposite and adjacent sides are 6 and 8. In the second, adjacent side is 20. Find its opposite side.',choices:['12','15','16','26'],choiceMath:true,answer:1,explanation:{steps:[{text:'Tangent is constant.',math:'6/8=x/20'},{text:'Solve.',math:'x=15'}],trap:'Use corresponding side roles, not raw side order.',takeaway:'Equal acute angles create similar right triangles.'}},
    ]},
};

const trigInContextAndUnitCircle = {
    slug:'trig-in-context-and-unit-circle',moduleId:'area-volume-trig',title:'Trig in Context & the Unit Circle',eyebrow:'Geometry and Trigonometry',minutes:'43 min',
    summary:'Model elevation and depression, combine trig with geometry, and use the SAT-level unit circle for radians and exact sine or cosine values.',
    goals:['Draw right triangles from elevation and depression contexts.','Account for eye height and other offsets.','Use unit-circle coordinates for exact values.','Connect radians, reference angles, signs, and multistep geometry.'],
    facts:[{label:'Elevation',value:'angle above horizontal',note:'from observer'},{label:'Depression',value:'angle below horizontal',note:'parallel horizontals create alternate-interior equality'},{label:'Unit circle',math:'(\\cos\\theta,\\sin\\theta)',note:'radius one'},{label:'Quadrant signs',value:'I (+,+), II (-,+), III (-,-), IV (+,-)',note:'cosine is x, sine is y'}],
    sections:[
        {heading:'Big idea 1: translate words into a right triangle',paragraphs:['Draw a horizontal reference through the observer. Angle of elevation lies above it; angle of depression lies below it. The ground or another horizontal line is parallel, so alternate-interior angles often transfer the angle.','Label line of sight as the hypotenuse only when the triangle is right.']},
        {heading:'Big idea 2: the triangle may model only a height difference',paragraphs:['An observer’s eye height, platform height, or building base offset may lie outside the trig triangle. Add or subtract that amount after solving the triangle.','Write what each side represents before calculating.']},
        {heading:'Big idea 3: the unit circle extends right-triangle ratios',paragraphs:['At angle theta on a radius-one circle, the point is cosine theta comma sine theta. Familiar special-triangle values give exact coordinates at 30, 45, and 60 degree reference angles.','The reference angle gives magnitude; the quadrant gives sign. SAT scope can include this unit-circle interpretation but not advanced trig identities.']},
        {heading:'Big idea 4: radians measure traveled angle naturally',paragraphs:['Radians connect angle, radius, and arc length through s equals r theta. A rotation question may combine unit-circle position with an arc or sector.','Convert only if the requested representation requires it.']},
    ],
    formulas:[
        {label:'Elevation model',math:'\\tan\\theta=\\frac{\\text{vertical change}}{\\text{horizontal distance}}',note:'Add eye or platform height afterward if necessary.',meaning:'Tangent compares rise with horizontal run.',useWhen:'Observer distance and an elevation or depression angle are given.'},
        {label:'Unit-circle point',math:'P(\\theta)=(\\cos\\theta,\\sin\\theta)',note:'Coordinates can be negative by quadrant.',meaning:'Cosine is horizontal position and sine is vertical position on radius one.',useWhen:'An angle or radian measure asks for exact sine, cosine, or a coordinate.'},
        {label:'Reference values',math:'\\begin{array}{c|ccc}\\theta&30^\\circ&45^\\circ&60^\\circ\\\\\\sin\\theta&1/2&\\sqrt2/2&\\sqrt3/2\\\\\\cos\\theta&\\sqrt3/2&\\sqrt2/2&1/2\\end{array}',note:'Use reference angles for other quadrants.',meaning:'Special-triangle ratios become unit-circle coordinates.',useWhen:'Exact common-angle values are needed.'},
        {label:'Arc-radian link',math:'s=r\\theta',note:'Theta must be in radians.',meaning:'A radian is the angle subtending an arc equal to the radius.',useWhen:'Rotation, wheel, or circular path context combines length and angle.'},
    ],
    workedExamples:[
        {level:'Foundation/Core',title:'Find a building height',prompt:'From 30 meters away, the angle of elevation to a roof is 40 degrees. The observer’s eye is 1.6 meters high. Find building height.',math:'\\tan40^\\circ=x/30',steps:[{text:'Find height above eye level.',math:'x=30\\tan40^\\circ\\approx25.17'},{text:'Add eye height.',math:'H\\approx26.77\\text{ m}'}],insight:'The trig triangle begins at eye level.',trap:'Do not forget the 1.6-meter offset.'},
        {level:'Core SAT',title:'Read a unit-circle coordinate',prompt:'Find cosine 150 degrees.',math:'150^\\circ=180^\\circ-30^\\circ',steps:[{text:'Reference angle is 30 degrees.'},{text:'Quadrant II has negative x-coordinate.',math:'\\cos150^\\circ=-\\sqrt3/2'}],insight:'Magnitude comes from 30 degrees; sign comes from quadrant.',trap:'Sine is positive in quadrant II, but cosine is negative.'},
        {level:'Advanced',title:'Combine an arc with rotation',prompt:'A point travels 15 pi units along a circle of radius 10. Find its rotation in degrees.',math:'\\theta=s/r=15\\pi/10=3\\pi/2',steps:[{text:'Use radians directly.'},{text:'Convert.',math:'\\frac{3\\pi}{2}\\cdot\\frac{180^\\circ}{\\pi}=270^\\circ'}],insight:'Arc length divided by radius gives the radian angle.',trap:'The path length is not the circumference fraction until divided appropriately.'},
    ],
    strategyCards:[{title:'Draw the context',items:['Add a horizontal through the observer.','Label vertical change and horizontal distance.','Mark offsets outside the triangle.']},{title:'For unit-circle values',items:['Find the reference angle.','Recall the first-quadrant magnitude.','Apply the quadrant sign.']},{title:'Stay in scope',items:['Know common 30-45-60 values.','Use coordinate meaning and radians.','Do not memorize advanced identities the SAT does not require.']}],
    studyTips:[{title:'Separate triangle height from total height',summary:'Write two variables when an observer or platform creates an offset.',items:['Trig solves the vertical difference.','Context supplies the starting height.','Add or subtract only after the triangle is solved.']}],
    adaptiveDemo:{title:'Choose the sign',prompt:'An angle lies in quadrant III.',options:[{id:'bothneg',label:'sin and cos negative',result:'Correct: both x and y coordinates are negative.',advice:'Cosine is x; sine is y.'},{id:'sinpos',label:'sin positive',result:'Quadrant III lies below the x-axis.',advice:'Use coordinate signs rather than a memorized phrase if unsure.'}]},
    quickCheck:{prompt:'What is sin 225 degrees?',choices:['-\\frac{\\sqrt2}{2}','-\\frac12','\\frac12','\\frac{\\sqrt2}{2}'],choiceMath:true,answer:0,explanation:'Two hundred twenty-five degrees has 45-degree reference angle in quadrant III, where sine is negative.'},
    practiceSet:{title:'Context trig and SAT-level unit circle',intro:'Model the right triangle or unit-circle coordinate before calculating.',questions:[
        {id:'trig-context-elev',difficulty:'Foundation',skill:'Elevation',title:'Choose a tangent equation',stem:'From 50 feet away, the angle of elevation to a point is theta and vertical rise is h. Which equation is correct?',choices:['sin θ=h/50','cos θ=h/50','tan θ=h/50','tan θ=50/h'],choiceMath:true,answer:2,explanation:{steps:[{text:'Vertical rise is opposite and horizontal distance is adjacent.',math:'\\tan\\theta=h/50'}],trap:'Tangent connects the two legs.',takeaway:'Translate side roles from context.'}},
        {id:'trig-context-depression',difficulty:'Core',skill:'Depression',title:'Transfer an angle',stem:'A horizontal line of sight and level ground are parallel. An angle of depression is 32 degrees. What is the equal angle of elevation from the ground point?',choices:['32°','58°','148°','180°'],answer:0,explanation:{steps:[{text:'Alternate-interior angles formed by parallel horizontals are equal.'}],trap:'Do not take the complement.',takeaway:'Elevation and depression angles match in the standard parallel setup.'}},
        {id:'trig-unit-coordinate',difficulty:'Core',skill:'Unit circle',title:'Read a coordinate',stem:'What is the unit-circle point at 90 degrees?',choices:['(1,0)','(0,1)','(-1,0)','(0,-1)'],answer:1,explanation:{steps:[{text:'At the top of the unit circle, x is zero and y is one.',math:'(\\cos90^\\circ,\\sin90^\\circ)=(0,1)'}],trap:'Cosine is x and sine is y.',takeaway:'Coordinates encode trig values.'}},
        {id:'trig-unit-exact',difficulty:'Advanced',skill:'Reference angles',title:'Find an exact cosine',stem:'What is cosine 300 degrees?',choices:['-\\frac{\\sqrt3}{2}','-\\frac12','\\frac12','\\frac{\\sqrt3}{2}'],choiceMath:true,answer:2,explanation:{steps:[{text:'Reference angle is sixty degrees.'},{text:'Quadrant IV cosine is positive.',math:'\\cos300^\\circ=\\frac12'}],trap:'Square root three over two is sine magnitude for sixty degrees.',takeaway:'Match both function and quadrant.'}},
        {id:'trig-context-two-step',difficulty:'Advanced',skill:'Multistep modeling',title:'Include an offset',stem:'From a 6-foot platform, a cable rises at 30 degrees over a horizontal distance of 8√3 feet. What is the cable endpoint’s height above ground?',choices:['8','10','14','16'],choiceMath:true,answer:2,explanation:{steps:[{text:'Find vertical rise.',math:'h=(8\\sqrt3)\\tan30^\\circ=(8\\sqrt3)(1/\\sqrt3)=8'},{text:'Add platform height.',math:'8+6=14'}],trap:'Eight is rise above the platform, not total height.',takeaway:'Apply contextual offsets after trig.'}},
    ]},
};

export const AREA_VOLUME_TRIG_LESSONS = [
    perimeterAreaAndCompositeFigures,
    surfaceAreaAndVolume,
    scaleFactorsAndGeometryUnits,
    sineCosineAndTangent,
    trigInContextAndUnitCircle,
];
