const graphingSystemsAndIntersections = {
    slug:'graphing-systems-and-intersections',moduleId:'calculator-mixed-review',title:'Graphing Systems & Intersections',eyebrow:'Calculator Strategy',minutes:'38 min',
    summary:'Use the embedded Desmos graphing calculator for zeros, intersections, systems, and parameter exploration while keeping algebraic meaning in control.',
    goals:['Translate equations into graphable expressions.','Read zeros and intersections as equation solutions.','Recognize one, none, infinitely many, and tangent cases.','Use sliders and restricted views to investigate parameters without replacing proof.'],
    facts:[{label:'Zero',math:'f(x)=0',note:'x-axis intersection'},{label:'Intersection',math:'f(x)=g(x)',note:'shared ordered pair'},{label:'System solution',value:'both equations true',note:'intersection coordinate'},{label:'Calculator',value:'available throughout Math',note:'embedded Desmos or an approved handheld'}],
    sections:[
        {heading:'Big idea 1: graph the two sides of an equation',paragraphs:['For an equation such as x squared plus two equals five x, graph y equals x squared plus two and y equals five x. Their intersection x-coordinates solve the equation.','For an equation already equal to zero, graph the left side and read its x-intercepts.']},
        {heading:'Big idea 2: coordinates answer different questions',paragraphs:['At an intersection, x is the input that solves the equation and y is the shared output. Read the exact noun requested before copying a coordinate.','A system answer may request x plus y, a parameter, or the number of solutions rather than the full point.']},
        {heading:'Big idea 3: the graph shape checks solution count',paragraphs:['Distinct crossings give multiple real solutions; tangency gives one repeated solution; no visible crossing suggests no real solution only after checking the window. Identical lines represent infinitely many solutions.','Use algebra when exact symbolic values or proof are required.']},
        {heading:'Big idea 4: parameter sliders reveal boundaries',paragraphs:['Typing a variable not assigned a number creates a slider. Move it to see when graphs change from two intersections to one to none, then use algebra to determine the exact boundary.','Sliders are excellent for conjecture and checking but do not replace a parameter equation such as a zero discriminant.']},
    ],
    formulas:[
        {label:'Equation as intersection',math:'L(x)=R(x)\\Longleftrightarrow y=L(x)\\text{ intersects }y=R(x)',note:'Read requested x- or y-coordinate.',meaning:'Both sides have the same value at a solution.',useWhen:'Direct algebra is messy but both sides graph cleanly.'},
        {label:'Equation as zero',math:'F(x)=0\\Longleftrightarrow(x,0)\\text{ is an x-intercept}',note:'Factor or algebra may still be faster for exact roots.',meaning:'The function output vanishes at each root.',useWhen:'An equation is already in zero form.'},
        {label:'Tangency boundary',math:'\\text{one contact}\\Longleftrightarrow\\text{one repeated solution}',note:'Confirm exact parameter algebraically.',meaning:'A parameter boundary often occurs when two intersections merge.',useWhen:'A hard question asks when a line and curve meet once.'},
        {label:'Domain restriction',math:'y=f(x)\\{a\\le x\\le b\\}',note:'Curly braces restrict a Desmos graph.',meaning:'Only the contextually valid interval is shown.',useWhen:'A model is valid on a stated time or quantity range.'},
    ],
    workedExamples:[
        {level:'Foundation/Core',title:'Solve by intersection',prompt:'Solve x squared plus 1 equals 4x.',math:'y=x^2+1,\\qquad y=4x',steps:[{text:'Graph both expressions.'},{text:'Read intersection x-values.',math:'x=2\\pm\\sqrt3'},{text:'Use decimals only if the choices are decimal.'}],insight:'The intersection y-coordinate is not the requested solution x.',trap:'Zoom enough to see both crossings.'},
        {level:'Core SAT',title:'Solve a linear system',prompt:'Find x plus y for y equals 2x plus 1 and y equals negative x plus 7.',math:'(x,y)=(2,5)',steps:[{text:'Graph both lines and select their intersection.'},{text:'Use the requested expression.',math:'x+y=7'}],insight:'The calculator supplies a point; the question may ask for a transformation of it.',trap:'Do not report five just because it is the visible y-coordinate.'},
        {level:'Advanced',title:'Investigate tangency',prompt:'For which positive m is y equals mx tangent to y equals x squared plus 9?',math:'x^2-mx+9=0',steps:[{text:'Use a slider to see tangency near m equals 6.'},{text:'Prove exactness with discriminant.',math:'m^2-36=0'},{text:'Use the positive condition.',math:'m=6'}],insight:'Graph for structure; algebra for the exact parameter.',trap:'A zoomed graph can make near-tangency look exact.'},
    ],
    strategyCards:[{title:'Graph when',items:['A system or nonlinear intersection is messy.','A root or extremum is numerical.','You want a fast visual solution-count check.']},{title:'Use algebra when',items:['Factoring is immediate.','The answer is symbolic or asks why.','A parameter boundary needs exact proof.']},{title:'Verify the readout',items:['Check the requested coordinate.','Check the valid domain.','Substitute the value into the original equation.']}],
    studyTips:[{title:'Practice the embedded version',summary:'Use Bluebook Test Preview or practice tests so calculator placement and controls are familiar.',items:['Know how to add expressions and tables.','Know how to zoom and select a point.','Know how to close or move the calculator quickly.']}],
    adaptiveDemo:{title:'Pick the representation',prompt:'You need the solutions of f(x) equals g(x).',options:[{id:'both',label:'Graph y=f and y=g',result:'Correct.',advice:'The intersection x-values solve the equation.'},{id:'product',label:'Graph y=fg',result:'That finds where either function equals zero.',advice:'Equality is represented by intersections or by graphing f minus g.'}]},
    quickCheck:{prompt:'Two graphs intersect at (-3,8). If the question asks for the solution to f(x)=g(x), what should you enter?',choices:['-3','8','5','(-3,8)'],answer:0,explanation:'The equation asks for the input x at which the outputs match, so enter negative three unless the prompt requests the full ordered pair.'},
    practiceSet:{title:'Graphing decisions',intro:'Translate the math target before reading a calculator point.',questions:[
        {id:'calc-graph-zero',difficulty:'Foundation',skill:'Zeros',title:'Interpret an intercept',stem:'The graph of f crosses the x-axis at x equals 4. Which statement is true?',choices:['f(0)=4','f(4)=0','f(4)=4','f(0)=0'],answer:1,explanation:{steps:[{text:'An x-intercept has output zero.',math:'f(4)=0'}],trap:'The point is four comma zero.',takeaway:'Zeros are x-coordinates of x-intercepts.'}},
        {id:'calc-graph-system',difficulty:'Core',skill:'Systems',title:'Read the target',stem:'A system intersects at (6,-2). What is 2x minus y?',choices:['4','8','10','14'],choiceMath:true,answer:3,explanation:{steps:[{text:'Substitute both coordinates.',math:'2(6)-(-2)=14'}],trap:'Use negative two with its sign.',takeaway:'Process the point through the requested expression.'}},
        {id:'calc-graph-count',difficulty:'Core',skill:'Solution count',title:'Interpret tangency',stem:'A line touches a parabola at exactly one point. How many distinct real solutions does the system have?',choices:['0','1','2','Infinitely many'],answer:1,explanation:{steps:[{text:'Each intersection is one system solution.'}],trap:'Tangency counts as one distinct point.',takeaway:'Graph contact count equals system solution count.'}},
        {id:'calc-graph-domain',difficulty:'Advanced',skill:'Restrictions',title:'Respect a model domain',stem:'Graphs intersect at x equals negative 2 and x equals 7, but the model requires x at least zero. Which solution is valid?',choices:['-2','0','7','Both'],choiceMath:true,answer:2,explanation:{steps:[{text:'Apply the domain.',math:'x\\ge0'},{text:'Keep only seven.'}],trap:'The calculator shows mathematical intersections beyond context.',takeaway:'Filter graph results through the stated domain.'}},
    ]},
};

const tablesListsAndRegression = {
    slug:'tables-lists-and-regression',moduleId:'calculator-mixed-review',title:'Tables, Lists & Regression',eyebrow:'Calculator Strategy',minutes:'37 min',
    summary:'Use Desmos tables and lists to evaluate functions, inspect patterns, fit models, and check statistics without confusing prediction with proof.',
    goals:['Build and read function-value tables.','Enter data lists and choose linear, quadratic, or exponential regression.','Interpret fitted coefficients and residuals in context.','Use calculator statistics as a check while preserving exact reasoning.'],
    facts:[{label:'Table',value:'paired x and y values',note:'fast function evaluation'},{label:'Linear regression',math:'y_1\\sim mx_1+b',note:'use tilde, not equals'},{label:'Quadratic regression',math:'y_1\\sim ax_1^2+bx_1+c',note:'curved data'},{label:'Exponential regression',math:'y_1\\sim ab^{x_1}',note:'constant factor pattern'}],
    sections:[
        {heading:'Big idea 1: tables turn repeated substitution into one setup',paragraphs:['Enter a function, open its table, and inspect outputs at answer-choice inputs or around a vertex, zero, or threshold.','A table samples points; it does not prove what happens between them unless the function’s structure supplies that reasoning.']},
        {heading:'Big idea 2: regression matches a model family to data',paragraphs:['Enter x-values and y-values in a table, then use a tilde expression with x sub one and y sub one. Choose the family the question specifies or the pattern supports.','Linear models show roughly constant differences; exponential models show roughly constant ratios; quadratic models show roughly constant second differences.']},
        {heading:'Big idea 3: coefficients still need interpretation',paragraphs:['In y equals mx plus b, m is change in y per x-unit and b is predicted y at x equals zero. In y equals a times b to the x, a is the initial value and b is the per-unit factor.','Units and realistic domain remain essential even when Desmos supplies decimals.']},
        {heading:'Big idea 4: residuals measure model error',paragraphs:['Residual equals observed minus predicted. Positive residual means the observed point lies above the model; negative means below.','A smaller residual magnitude means the prediction is closer for that point, not necessarily that the entire model is best.']},
    ],
    formulas:[
        {label:'Residual',math:'r=y_{observed}-y_{predicted}',note:'Keep subtraction order fixed.',meaning:'Residual records signed vertical prediction error.',useWhen:'Comparing a data point with a model.'},
        {label:'Linear interpretation',math:'\\hat y=mx+b',note:'m has y-units per x-unit.',meaning:'The model changes by a constant additive amount.',useWhen:'Regression or context suggests a line.'},
        {label:'Exponential interpretation',math:'\\hat y=ab^x',note:'Percent change is one hundred times b minus one percent.',meaning:'The model changes by a constant multiplicative factor.',useWhen:'Data show repeated percent growth or decay.'},
        {label:'List statistics',math:'\\operatorname{mean}(L),\\ \\operatorname{median}(L),\\ \\operatorname{stdev}(L)',note:'Know whether the question wants population or sample language; SAT usually focuses interpretation.',meaning:'Lists let the calculator summarize repeated data quickly.',useWhen:'Checking center or spread for a numerical data set.'},
    ],
    workedExamples:[
        {level:'Foundation/Core',title:'Test answer choices in a table',prompt:'Which listed x solves x cubed minus 4x equals 15?',math:'f(x)=x^3-4x',steps:[{text:'Create a table for the answer-choice x-values.'},{text:'Find the row with output fifteen.',math:'f(3)=27-12=15'},{text:'Therefore the matching input is.',math:'x=3'}],insight:'A choice table is useful when choices are few and substitution is simpler than solving.',trap:'The target output is fifteen, not zero unless you graph x cubed minus four x minus fifteen.'},
        {level:'Core SAT',title:'Interpret exponential regression',prompt:'Desmos fits y sub one tilde a times b to x sub one and returns a equals 80, b equals 1.06.',math:'\\hat y=80(1.06)^x',steps:[{text:'Read initial value.',math:'80'},{text:'Convert factor to percent growth.',math:'(1.06-1)100\\%=6\\%'}],insight:'Regression output still uses ordinary exponential-model interpretation.',trap:'One point zero six is the factor, not a 106 percent increase.'},
        {level:'Advanced',title:'Calculate a residual',prompt:'A model predicts 42.7 when the observed value is 40.1. Find the residual.',math:'40.1-42.7',steps:[{text:'Subtract predicted from observed.',math:'r=-2.6'}],insight:'Negative means the observed point is below the model.',trap:'Do not reverse the subtraction.'},
    ],
    strategyCards:[{title:'Use a table for',items:['Repeated function evaluation.','Testing numerical answer choices.','Inspecting a pattern near a target input.']},{title:'Choose a model family',items:['Constant differences: linear.','Constant ratios: exponential.','Constant second differences: quadratic.']},{title:'Sanity-check output',items:['Interpret coefficients with units.','Do not extrapolate beyond a realistic domain blindly.','Round only as requested.']}],
    studyTips:[{title:'Know the regression tilde',summary:'Desmos uses a tilde to fit coefficients to table data.',items:['Use table columns x sub one and y sub one.','Use equals for a fixed equation.','Use tilde for best-fit parameters.']}],
    adaptiveDemo:{title:'Pick a model family',prompt:'Outputs multiply by about 1.08 whenever x increases by one.',options:[{id:'exp',label:'Exponential',result:'Correct.',advice:'A roughly constant ratio signals a multiplicative model.'},{id:'linear',label:'Linear',result:'Linear data have roughly constant differences.',advice:'Compare successive ratios as well as differences.'}]},
    quickCheck:{prompt:'A model predicts 18 and the observed value is 21. What is the residual?',choices:['-3','3','18','39'],choiceMath:true,answer:1,explanation:'Residual is observed minus predicted: twenty-one minus eighteen equals three.'},
    practiceSet:{title:'Tables and model fitting',intro:'Use the calculator to organize computation, then interpret mathematically.',questions:[
        {id:'calc-table-pattern',difficulty:'Foundation',skill:'Patterns',title:'Identify a model',stem:'For equal x-steps, y-values are 5, 10, 20, 40. Which model family fits?',choices:['Linear','Quadratic','Exponential','Constant'],answer:2,explanation:{steps:[{text:'Each output doubles.',math:'10/5=20/10=40/20=2'}],trap:'Differences are not constant.',takeaway:'Constant ratios indicate exponential change.'}},
        {id:'calc-table-slope',difficulty:'Core',skill:'Linear regression',title:'Interpret a coefficient',stem:'A fitted line is y equals 3.4x plus 12, where x is hours and y is dollars. What does 3.4 mean?',choices:['$12 initially','$3.40 per hour','$3.40 total','12 hours per dollar'],answer:1,explanation:{steps:[{text:'The x coefficient is change in y per one x-unit.'}],trap:'The intercept is twelve.',takeaway:'Attach output-per-input units to slope.'}},
        {id:'calc-table-growth',difficulty:'Core',skill:'Exponential regression',title:'Read a decay factor',stem:'A fitted model has factor b equals 0.82. What percent decrease occurs per step?',choices:['8%','18%','82%','118%'],answer:1,explanation:{steps:[{text:'Subtract factor from one.',math:'1-0.82=0.18=18\\%'}],trap:'Eighty-two percent is the amount retained.',takeaway:'Decay percent equals one minus factor.'}},
        {id:'calc-table-residual',difficulty:'Advanced',skill:'Residuals',title:'Interpret a sign',stem:'A data point has residual negative 4. Which statement is true?',choices:['Observed is 4 above predicted.','Observed is 4 below predicted.','Prediction is negative 4.','The model has no fit.'],answer:1,explanation:{steps:[{text:'Observed minus predicted equals negative four.'}],trap:'Residual sign describes vertical direction.',takeaway:'Negative residual means model overpredicts that point by four.'}},
    ]},
};

const answerTestingAndModeling = {
    slug:'answer-testing-and-modeling',moduleId:'calculator-mixed-review',title:'Answer Testing & Modeling',eyebrow:'Calculator Strategy',minutes:'35 min',
    summary:'Backsolve numerical choices, test symbolic claims, and use Desmos restrictions or sliders to verify models without losing context or exactness.',
    goals:['Recognize when backsolving beats deriving a formula.','Test choices in an efficient order.','Verify symbolic choices with strategic inputs or graphs.','Respect domains, units, and extraneous candidates.'],
    facts:[{label:'Backsolve',value:'choices → condition',note:'start with a middle value when ordered'},{label:'Identity check',value:'several safe inputs',note:'one match is not proof'},{label:'Restriction',math:'\\{a\\le x\\le b\\}',note:'show model domain'},{label:'Verification',value:'original condition',note:'always use the untransformed problem'}],
    sections:[
        {heading:'Big idea 1: answer choices are usable information',paragraphs:['When choices are numeric and the prompt asks which value satisfies a condition, substitute choices instead of solving a messy equation. For ordered choices, begin near the middle to eliminate a direction when behavior is monotonic.','Backsolving is especially effective for integer dimensions, percent totals, and word-problem constraints.']},
        {heading:'Big idea 2: test the quantity the choice actually represents',paragraphs:['A choice may represent an original value, a change, a side length, or a parameter. Substitute it into the corresponding part of the model rather than wherever x appears automatically.','Translate each noun before opening the calculator.']},
        {heading:'Big idea 3: symbolic choices require more than one lucky point',paragraphs:['To compare expressions, graph their difference or test several safe inputs, including zero, one, a negative value, and a noninteger when allowed. A single input cannot establish identity because different expressions can coincide once.','Algebraic transformation remains the strongest exact proof.']},
        {heading:'Big idea 4: checking must use the original problem',paragraphs:['Squaring, multiplying by variable expressions, and graph-window restrictions can introduce or hide candidates. Test final values in the original equation and context.','A calculator verifies arithmetic; it does not decide whether negative time or an excluded denominator is valid.']},
    ],
    formulas:[
        {label:'Backsolve loop',math:'\\text{choice}\\rightarrow\\text{substitute}\\rightarrow\\text{compare target}',note:'Stop as soon as one choice satisfies every condition.',meaning:'Multiple-choice options become a small candidate set.',useWhen:'Choices are concrete and direct solving is longer.'},
        {label:'Expression comparison',math:'D(x)=E_1(x)-E_2(x)',note:'Equivalent expressions give D(x) equal to zero for all allowed x.',meaning:'A difference graph exposes where expressions agree or disagree.',useWhen:'Answer choices are algebraic forms.'},
        {label:'Original-equation check',math:'L(x_{cand})\\stackrel{?}=R(x_{cand})',note:'Also check domain and units.',meaning:'A candidate is valid only if it satisfies the starting condition.',useWhen:'Operations may create extraneous solutions or a graph supplies decimals.'},
        {label:'Percent-choice model',math:'\\text{new}=\\text{original}(1\\pm r)',note:'Identify whether choices list original or new amounts.',meaning:'Testing a choice must preserve the question’s reference base.',useWhen:'Backsolving percent increase or decrease problems.'},
    ],
    workedExamples:[
        {level:'Foundation/Core',title:'Backsolve a percent problem',prompt:'After a 20 percent discount, an item costs 72 dollars. Which original price is correct?',math:'0.80P=72',steps:[{text:'Test the likely choice 90.',math:'0.8(90)=72'},{text:'Stop: every condition is satisfied.'}],insight:'The choice represents original price, so apply the discount to it.',trap:'Adding twenty percent of seventy-two does not reverse a twenty percent discount.'},
        {level:'Core SAT',title:'Test a dimension choice',prompt:'A rectangle has perimeter 30 and area 56. Choices list possible longer sides.',math:'l(15-l)=56',steps:[{text:'Test l equals eight.',math:'8(7)=56'},{text:'Confirm eight is the longer of eight and seven.'}],insight:'One choice can reveal the paired side through half-perimeter.',trap:'Use length plus width equals fifteen.'},
        {level:'Advanced',title:'Disprove an identity quickly',prompt:'Is x squared plus 1 equivalent to (x plus 1) squared?',math:'x=1',steps:[{text:'Test a safe input.',math:'1^2+1=2,\\quad(1+1)^2=4'},{text:'One mismatch disproves identity.'}],insight:'One counterexample disproves a universal claim; several matches do not prove it.',trap:'At x equals zero, both expressions equal one, a misleading coincidence.'},
    ],
    strategyCards:[{title:'Backsolve when',items:['Choices are numerical.','The condition is easy to evaluate.','Derivation would create messy algebra.']},{title:'Test smart',items:['Start with a middle ordered choice.','Use estimation to skip impossible magnitudes.','Stop only when all conditions match.']},{title:'Protect validity',items:['Avoid excluded denominators.','Check original equations after radicals or squares.','Apply realistic domains and units.']}],
    studyTips:[{title:'Separate solving from verifying',summary:'A graph or choice test can find a candidate; the original condition certifies it.',items:['Copy enough precision to test.','Prefer exact choices when available.','Reject candidates that violate context.']}],
    adaptiveDemo:{title:'Choose a test input',prompt:'Two expressions both equal one at x equals zero. Are they proven equivalent?',options:[{id:'no',label:'No',result:'Correct.',advice:'Different expressions can meet at one point; test more values or use algebra.'},{id:'yes',label:'Yes',result:'One matching input is insufficient.',advice:'Identity means agreement for every allowed input.'}]},
    quickCheck:{prompt:'A value increased by 25 percent becomes 60. Which original value should you test?',choices:['45','48','75','80'],choiceMath:true,answer:1,explanation:'Testing forty-eight gives one point two five times forty-eight equals sixty.'},
    practiceSet:{title:'Answer testing decisions',intro:'Test choices in the exact role named by the question.',questions:[
        {id:'calc-test-percent',difficulty:'Foundation',skill:'Backsolving',title:'Reverse a markup',stem:'After a 50 percent markup, a price is 90. What was the original price?',choices:['45','60','90','135'],choiceMath:true,answer:1,explanation:{steps:[{text:'Test sixty as original.',math:'1.5(60)=90'}],trap:'A fifty-percent markup uses factor one point five.',takeaway:'Apply the change to the candidate original.'}},
        {id:'calc-test-root',difficulty:'Core',skill:'Verification',title:'Reject an extraneous root',stem:'Squaring an equation produces candidates x equals 1 and x equals 9. In the original equation, only x equals 9 works. What is the solution?',choices:['1','9','1 and 9','No solution'],choiceMath:true,answer:1,explanation:{steps:[{text:'Final solutions must satisfy the original equation.'}],trap:'Squared equations can contain extra candidates.',takeaway:'Verify after nonreversible operations.'}},
        {id:'calc-test-symbolic',difficulty:'Core',skill:'Counterexamples',title:'Disprove equivalence',stem:'Which input is especially useful for detecting a missing constant term?',choices:['x=0','x=1','x=10','x=100'],answer:0,explanation:{steps:[{text:'At zero, nonconstant terms vanish and constants remain.'}],trap:'No single test proves identity, but one mismatch disproves it.',takeaway:'Choose inputs that isolate structure.'}},
        {id:'calc-test-context',difficulty:'Advanced',skill:'Domains',title:'Filter a graph solution',stem:'A model for side length produces x equals negative 3 and x equals 8. Which can represent the side?',choices:['-3 only','8 only','Both','Neither'],answer:1,explanation:{steps:[{text:'A physical side length must be positive.'}],trap:'Both may be algebraic roots.',takeaway:'Context narrows calculator output.'}},
    ]},
};

const calculatorTrapsAndExactValues = {
    slug:'calculator-traps-and-exact-values',moduleId:'calculator-mixed-review',title:'Calculator Traps & Exact Values',eyebrow:'Calculator Strategy',minutes:'35 min',
    summary:'Avoid mode, syntax, window, rounding, and interpretation errors—and know when exact algebra is faster than any calculator path.',
    goals:['Control parentheses, fractions, exponents, and negative signs.','Use degrees or radians intentionally.','Recognize misleading graph windows and rounded coordinates.','Preserve exact values and choose algebra when it is shorter.'],
    facts:[{label:'Negative square',math:'(-3)^2=9',note:'but -3 squared typed without grouping may mean negative nine'},{label:'Fraction scope',math:'\\frac{a+b}{c+d}',note:'group numerator and denominator'},{label:'Angle mode',value:'match the problem',note:'degrees unless radians are stated'},{label:'Exact first',value:'round once at end',note:'keep pi and radicals when possible'}],
    sections:[
        {heading:'Big idea 1: syntax is mathematics',paragraphs:['Parentheses determine which terms are squared, divided, or placed in a function. Enter the complete numerator and denominator before leaving a fraction.','Distinguish a negative input squared from the negative of a square.']},
        {heading:'Big idea 2: angle mode changes trig output',paragraphs:['A calculator cannot infer whether 30 means degrees or radians. For SAT geometry, degrees are common; unit-circle or arc questions may explicitly use radians.','Estimate familiar values: sine 30 degrees should be one half, which makes a fast mode check.']},
        {heading:'Big idea 3: the viewing window can lie by omission',paragraphs:['No visible intersection may mean no real solution, or simply that the intersection lies outside the current window. Zoom out, use a table, or use algebra before concluding.','A curve can also appear linear or tangent under an extreme zoom.']},
        {heading:'Big idea 4: decimals can destroy an exact answer',paragraphs:['Keep pi, radicals, and fractions exact when the answer choices are exact. Copying a rounded intersection into later calculations can shift a final answer.','One-step algebra, factoring, exponent rules, and structural parameter questions are often faster and more reliable by hand.']},
    ],
    formulas:[
        {label:'Order and grouping',math:'-(x^2)\\ne(-x)^2',note:'Parentheses change the base of the exponent.',meaning:'An exponent applies only to its grouped base.',useWhen:'Negative numbers or expressions are raised to powers.'},
        {label:'Degree-radian check',math:'180^\\circ=\\pi\\text{ rad}',note:'Confirm mode before trig or inverse trig.',meaning:'The same numeric input represents different angles in different modes.',useWhen:'Using trig functions.'},
        {label:'Exact-value principle',math:'\\text{exact inputs}\\rightarrow\\text{exact work}\\rightarrow\\text{round once}',note:'Follow any rounding direction in the prompt.',meaning:'Delaying approximation prevents accumulated error.',useWhen:'Several calculation steps depend on one another.'},
        {label:'Window verification',math:'\\text{graph evidence}+\\text{table/algebra check}',note:'A picture alone may omit remote behavior.',meaning:'Independent representations protect against display artifacts.',useWhen:'A solution count or intersection is not visually clear.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Group a negative base',prompt:'Evaluate negative four squared versus the square of negative four.',math:'-4^2=-16,\\qquad(-4)^2=16',steps:[{text:'Exponent applies before the leading negative in the first expression.'},{text:'Parentheses include the negative in the squared base for the second.'}],insight:'Calculator syntax reflects standard order of operations.',trap:'The expressions are not interchangeable.'},
        {level:'Core SAT',title:'Catch the wrong angle mode',prompt:'Your calculator reports sine 30 approximately negative 0.988. Diagnose the issue.',math:'\\sin30^\\circ=1/2',steps:[{text:'The reported value corresponds to treating 30 as radians.'},{text:'Switch to degree mode for this degree-labeled angle.'}],insight:'A familiar benchmark exposes the mode error.',trap:'Do not alter the problem’s angle to fit the calculator.'},
        {level:'Advanced',title:'Preserve a radical',prompt:'A side is square root 13 and another calculation requires its square.',math:'(\\sqrt{13})^2=13',steps:[{text:'Keep the exact radical.'},{text:'Square exactly instead of entering a rounded 3.606.'}],insight:'Exact structure can eliminate calculation entirely.',trap:'Rounding before squaring can produce 13.003 or another inaccurate value.'},
    ],
    strategyCards:[{title:'Before pressing enter',items:['Check grouping and fraction bars.','Check degree or radian mode.','Estimate the answer’s sign and size.']},{title:'Before trusting a graph',items:['Inspect the window.','Check a table or algebra.','Apply any domain restriction.']},{title:'When algebra wins',items:['One or two clean steps finish the problem.','Exact symbolic structure matters.','A parameter condition needs proof.']}],
    studyTips:[{title:'Use a three-second estimate',summary:'Predict sign, scale, and rough location before reading output.',items:['A probability stays between zero and one.','A length is positive.','A percent factor near one should not create a hundredfold jump.']}],
    adaptiveDemo:{title:'Exact or decimal?',prompt:'Answer choices contain 3√5 and nearby decimals.',options:[{id:'exact',label:'Keep 3√5',result:'Correct.',advice:'Exact form matches the choices and avoids rounding.'},{id:'decimal',label:'Round immediately',result:'Early rounding adds error.',advice:'Approximate only if comparison requires it.'}]},
    quickCheck:{prompt:'A trig question gives an angle of π/6 with no degree symbol. Which mode matches the given measure?',choices:['Degree','Radian','Percent','Either always gives the same result'],answer:1,explanation:'An angle written with pi over six is in radians, so use radian mode.'},
    practiceSet:{title:'Calculator error prevention',intro:'Predict, enter carefully, and verify independently.',questions:[
        {id:'calc-trap-parentheses',difficulty:'Foundation',skill:'Syntax',title:'Square a negative',stem:'Which expression equals 25?',choices:['-5²','(-5)²','-(5²+1)','-(-5)²'],choiceMath:true,answer:1,explanation:{steps:[{text:'Parentheses make negative five the base.',math:'(-5)^2=25'}],trap:'Without parentheses, the exponent applies to five before the negative.',takeaway:'Group negative bases.'}},
        {id:'calc-trap-mode',difficulty:'Core',skill:'Angle mode',title:'Choose a mode',stem:'A problem asks for tan 45 degrees. Which setup is correct?',choices:['Radian mode with input 45','Degree mode with input 45','Degree mode with input π/4','Mode never matters'],answer:1,explanation:{steps:[{text:'The angle is explicitly labeled degrees.'}],trap:'Pi over four would be the radian equivalent, not a degree input.',takeaway:'Match calculator mode to notation.'}},
        {id:'calc-trap-window',difficulty:'Core',skill:'Graph window',title:'Interpret an empty view',stem:'Two graphs do not intersect in the visible window. What can you conclude immediately?',choices:['No real solution','Exactly one solution','Exactly two solutions','Nothing until the window or algebra is checked'],answer:3,explanation:{steps:[{text:'Intersections may lie outside the display.'}],trap:'The graph window is not the entire coordinate plane.',takeaway:'Verify solution count beyond the current view.'}},
        {id:'calc-trap-rounding',difficulty:'Advanced',skill:'Precision',title:'Delay approximation',stem:'A multistep exact calculation contains √7. When should you normally round?',choices:['Replace it with 2.6 immediately','After every operation','Only at the final requested result','Never, even if decimals are requested'],answer:2,explanation:{steps:[{text:'Keep full precision until the final step.'}],trap:'Early rounding compounds error.',takeaway:'Round once and as directed.'}},
    ]},
};

const hardModule2Workflow = {
    slug:'hard-module-2-workflow',moduleId:'calculator-mixed-review',title:'Hard Module 2 Workflow',eyebrow:'Calculator Strategy',minutes:'40 min',
    summary:'Handle difficult mixed questions with a repeatable sequence: triage, translate, expose structure, choose a method, verify, and protect the finish.',
    goals:['Triage questions by solvability rather than appearance.','Translate the target and constraints before manipulating.','Choose among algebra, graphing, backsolving, and estimation.','Use a two-pass finish and verify high-risk answers.'],
    facts:[{label:'Module time',value:'35 min',note:'22 Math questions per module'},{label:'Average pace',value:'about 95 seconds',note:'not a per-question limit'},{label:'Pass 1',value:'collect clean points',note:'mark time sinks'},{label:'Pass 2',value:'return with remaining time',note:'prioritize solvable hard questions'}],
    sections:[
        {heading:'Big idea 1: difficulty often comes from packaging',paragraphs:['Hard questions usually combine standard content, hide the target behind a parameter, or require interpreting a familiar feature. Underline the final noun and list given constraints.','Rewrite the question as an equation, graph feature, ratio, or geometric relationship before calculating.']},
        {heading:'Big idea 2: choose the shortest reliable representation',paragraphs:['Graph intersections or roots when numerical structure is messy; use algebra for exact parameters and equivalent expressions; backsolve concrete choices; estimate to eliminate impossible magnitudes.','Switch methods when your current path grows without producing new information.']},
        {heading:'Big idea 3: protect total score with triage',paragraphs:['If no setup has emerged after a reasonable attempt, mark the question, make a provisional choice, and move. A later question may be much faster.','The average pace is flexible: easy questions should create time for a few long questions.']},
        {heading:'Big idea 4: finish with targeted verification',paragraphs:['Return first to questions where you know the concept and only need time, not those with no visible path. Recheck signs, requested coordinate, units, domain, and typed-response format.','Never leave a question blank; there is no guessing penalty.']},
    ],
    formulas:[
        {label:'Target-first translation',math:'\\text{requested noun}\\rightarrow\\text{mathematical object}\\rightarrow\\text{method}',note:'Example: “how many solutions” becomes intersection count.',meaning:'A clear target prevents solving the wrong quantity.',useWhen:'A prompt feels dense or indirect.'},
        {label:'Method menu',math:'\\{\\text{algebra, graph, table, backsolve, estimate}\\}',note:'Choose based on representation, not habit.',meaning:'Different tools expose different structures.',useWhen:'The first approach becomes cumbersome.'},
        {label:'Two-pass rule',math:'\\text{secure points first}+\\text{return to marked questions}',note:'Use Bluebook Mark for Review and Question Menu.',meaning:'Pacing optimizes total correct answers, not order completion.',useWhen:'A question becomes a time sink.'},
        {label:'Final check',math:'\\text{sign}+\\text{units}+\\text{domain}+\\text{requested form}',note:'Include a reasonable magnitude check.',meaning:'Most avoidable misses survive computation but fail interpretation.',useWhen:'Before committing a difficult answer.'},
    ],
    workedExamples:[
        {level:'Core SAT',title:'Choose graphing over expansion',prompt:'Two complicated functions are given and the question asks where their outputs are equal.',math:'f(x)=g(x)',steps:[{text:'Graph y equals f of x and y equals g of x.'},{text:'Read intersection x-values in the valid domain.'},{text:'Substitute or estimate to verify.'}],insight:'The target is an intersection, which graphing exposes directly.',trap:'Do not copy the y-coordinate when x is requested.'},
        {level:'Advanced',title:'Choose algebra for a parameter',prompt:'A quadratic has exactly one real solution and contains parameter k.',math:'D=b^2-4ac=0',steps:[{text:'Translate exactly one solution into zero discriminant.'},{text:'Solve the parameter equation exactly.'},{text:'Use Desmos only to visualize or check tangency.'}],insight:'A graph suggests the boundary, but discriminant proves it.',trap:'Do not rely on pixel-level tangency.'},
        {level:'Advanced',title:'Abandon a bad path',prompt:'After expanding three large expressions, no cancellation appears and all choices are numerical.',math:'\\text{switch to answer testing}',steps:[{text:'Estimate to remove impossible choices.'},{text:'Test a middle remaining candidate.'},{text:'Verify the satisfying choice in the original condition.'}],insight:'Changing methods is strategic, not a failure.',trap:'Sunk time is not a reason to keep an inefficient method.'},
    ],
    strategyCards:[{title:'First 20 seconds',items:['Name the target.','List constraints and units.','Identify likely topic and representation.']},{title:'If stuck',items:['Look for structure or a substitution.','Try graphing or answer choices.','Mark and move if no setup appears.']},{title:'Last minutes',items:['Use Question Menu for blanks and marked items.','Check typed responses and signs.','Guess on every unresolved question.']}],
    studyTips:[{title:'Practice mixed, not only blocked',summary:'The real section does not label topics for you.',items:['Use targeted sets to learn.','Use mixed sets to practice recognition.','Review whether method choice—not concept—caused each miss.']}],
    adaptiveDemo:{title:'Triage a hard question',prompt:'After 75 seconds you have no equation or useful graph setup.',options:[{id:'move',label:'Mark and move',result:'Best choice for total-score protection.',advice:'Make a provisional selection and return if time remains.'},{id:'grind',label:'Keep grinding',result:'That may sacrifice easier later points.',advice:'Persistence helps only when a viable path is developing.'}]},
    quickCheck:{prompt:'A graph shows an intersection at (4,11), and the question asks for f(4). What is the answer?',choices:['4','7','11','15'],choiceMath:true,answer:2,explanation:'At x equals four, the shared output is eleven, so f of four equals eleven.'},
    practiceSet:{title:'Method-choice finish round',intro:'The skill is deciding what to do before doing it.',questions:[
        {id:'calc-flow-method',difficulty:'Core',skill:'Method choice',title:'Pick a fast method',stem:'Four numerical choices are offered for a variable in a complicated word equation, and substitution is quick. What method is most promising?',choices:['Complete the square','Backsolve choices','Prove by induction','Convert to radians'],answer:1,explanation:{steps:[{text:'Concrete choices and cheap evaluation favor backsolving.'}],trap:'Choose a method tied to the representation.',takeaway:'Answer choices can reduce the search space.'}},
        {id:'calc-flow-target',difficulty:'Core',skill:'Translation',title:'Translate a target',stem:'A question asks when two populations are equal. What graph feature represents the answer?',choices:['Either y-intercept','Either vertex','Their intersection x-coordinate','Their slopes'],answer:2,explanation:{steps:[{text:'Equal outputs occur at graph intersections.'}],trap:'When asks for input, not shared output.',takeaway:'Translate the target before calculating.'}},
        {id:'calc-flow-skip',difficulty:'Advanced',skill:'Pacing',title:'Protect later questions',stem:'You are stuck with no setup and several questions remain. What is the best move?',choices:['Leave it blank forever','Mark it, choose provisionally, and move','Restart the module','Spend all remaining time on it'],answer:1,explanation:{steps:[{text:'Secure accessible points before returning.'}],trap:'There is no benefit to leaving a blank.',takeaway:'Two-pass pacing maximizes total opportunities.'}},
        {id:'calc-flow-check',difficulty:'Advanced',skill:'Verification',title:'Choose the final check',stem:'A quadratic context produces roots negative 2 and 6 for elapsed time. What should you report?',choices:['-2','6','Both','Their sum 4'],choiceMath:true,answer:1,explanation:{steps:[{text:'Elapsed time must be nonnegative.'}],trap:'Mathematical roots must pass the context domain.',takeaway:'Domain is part of the answer.'}},
    ]},
};

export const CALCULATOR_STRATEGY_LESSONS = [
    graphingSystemsAndIntersections,
    tablesListsAndRegression,
    answerTestingAndModeling,
    calculatorTrapsAndExactValues,
    hardModule2Workflow,
];
