const arcsCentralAnglesAndSectors = {
    slug:'arcs-central-angles-and-sectors',moduleId:'circles-coordinate-geometry',title:'Arcs, Central Angles & Sectors',eyebrow:'Geometry and Trigonometry',minutes:'38 min',
    summary:'Treat an arc or sector as a fraction of a whole circle, and move cleanly among degrees, radians, length, and area.',
    goals:['Connect central-angle measure to intercepted-arc measure.','Calculate arc length and sector area as circle fractions.','Convert between degrees and radians.','Reverse arc or sector information to find a radius, angle, or circumference.'],
    facts:[{label:'Full circle',math:'360^\\circ=2\\pi\\text{ radians}',note:'one revolution'},{label:'Central angle',value:'equals intercepted arc measure',note:'in degrees'},{label:'Arc length',math:'s=r\\theta',note:'theta must be in radians'},{label:'Sector area',math:'A=\\frac12r^2\\theta',note:'theta must be in radians'}],
    sections:[
        {heading:'Big idea 1: central angle means fraction of a revolution',paragraphs:['A central angle has its vertex at the center. Its degree measure matches its intercepted arc’s degree measure.','The fraction theta over 360 multiplies circumference for arc length and circle area for sector area.']},
        {heading:'Big idea 2: radians package the same fraction differently',paragraphs:['A radian measure equals arc length divided by radius. Because the full circumference is two pi r, one revolution is two pi radians.','In s equals r theta and one-half r squared theta, theta must be in radians. Degree-based fraction formulas work equally well if used consistently.']},
        {heading:'Big idea 3: reverse problems are proportion problems',paragraphs:['If an arc length and angle are known, solve for the full circumference or radius. If a sector area is known, compare it to the whole area.','Keep pi exact unless a decimal is requested. Many SAT answer choices distinguish radius from diameter or arc length from arc measure.']},
        {heading:'Big idea 4: hard questions mix representations',paragraphs:['A question may state a degree measure, ask for a radian measure, then use it to find an arc length. Another may give an arc fraction and ask for total area.','Write the circle fraction first; it makes the chain visible.']},
    ],
    formulas:[
        {label:'Degree fraction',math:'f=\\frac{\\theta}{360^\\circ}',note:'Theta is a central angle or arc measure.',meaning:'The angle selects the same fraction of every circle quantity.',useWhen:'Degrees are given.'},
        {label:'Arc length',math:'L=\\frac{\\theta}{360^\\circ}(2\\pi r)=r\\theta_{rad}',note:'Do not confuse linear arc length with degree arc measure.',meaning:'Arc length is a fraction of circumference.',useWhen:'Finding curved distance.'},
        {label:'Sector area',math:'A=\\frac{\\theta}{360^\\circ}(\\pi r^2)=\\frac12r^2\\theta_{rad}',note:'Use the same unit system for theta throughout.',meaning:'Sector area is a fraction of total circle area.',useWhen:'Finding a wedge-shaped region.'},
        {label:'Degree-radian conversion',math:'\\theta_{rad}=\\theta_{deg}\\frac{\\pi}{180^\\circ}',note:'Reverse the factor to convert radians to degrees.',meaning:'Pi radians corresponds to 180 degrees.',useWhen:'The requested angle unit differs from the given unit.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find an arc length',prompt:'A circle has radius 10 and a 72-degree central angle. Find the intercepted arc length.',math:'L=\\frac{72}{360}(2\\pi\\cdot10)',steps:[{text:'Simplify the fraction.',math:'72/360=1/5'},{text:'Take one fifth of the circumference.',math:'L=4\\pi'}],insight:'Angle fraction and arc fraction match.',trap:'Four pi is a length, not an angle.'},
        {level:'Core SAT',title:'Reverse an arc proportion',prompt:'A 45-degree arc has length 3. Find the circle’s circumference.',math:'\\frac{45}{360}=\\frac3C',steps:[{text:'One eighth of the circle measures three.'},{text:'Multiply.',math:'C=24'}],insight:'No radius is needed when the target is circumference.',trap:'Do not square anything; arc length is linear.'},
        {level:'Advanced',title:'Find a radius from sector area',prompt:'A sector with angle pi over three radians has area 24 pi. Find the radius.',math:'24\\pi=\\frac12r^2\\left(\\frac\\pi3\\right)',steps:[{text:'Cancel pi and simplify.',math:'24=r^2/6'},{text:'Solve for positive radius.',math:'r^2=144\\Rightarrow r=12'}],insight:'The radian formula avoids converting to 60 degrees.',trap:'Radius is the positive square root of r squared.'},
    ],
    strategyCards:[{title:'Choose one language',items:['Degrees: use theta over 360.','Radians: use s equals r theta.','Do not mix formulas midstep.']},{title:'Name the target',items:['Arc measure uses degrees or radians.','Arc length uses linear units.','Sector area uses square units.']},{title:'Keep exact form',items:['Leave pi unless told to approximate.','Reduce circle fractions early.','Check radius versus diameter.']}],
    studyTips:[{title:'Anchor conversions at 180 degrees',summary:'Build unfamiliar conversions from pi radians equals 180 degrees.',items:['Thirty degrees is pi over six.','Forty-five degrees is pi over four.','Sixty degrees is pi over three.','Ninety degrees is pi over two.']}],
    adaptiveDemo:{title:'Pick the direct formula',prompt:'Radius and a radian central angle are known; arc length is requested.',options:[{id:'direct',label:'s = rθ',result:'Correct.',advice:'The angle is already in the unit this formula requires.'},{id:'sector',label:'½r²θ',result:'That calculates sector area.',advice:'Match linear target to a linear formula.'}]},
    quickCheck:{prompt:'What is 150 degrees in radians?',choices:['5π/6','3π/4','2π/3','5π/3'],choiceMath:true,answer:0,explanation:'Multiply one hundred fifty by pi over one hundred eighty and reduce to five pi over six.'},
    practiceSet:{title:'Arcs and sectors from foundation to hard Module 2',intro:'Identify the circle fraction and the target’s units first.',questions:[
        {id:'circle-arc-fraction',difficulty:'Foundation',skill:'Central angles',title:'Find a circle fraction',stem:'A 90-degree central angle intercepts what fraction of a circle?',choices:['1/2','1/3','1/4','1/6'],choiceMath:true,answer:2,explanation:{steps:[{text:'Divide by a full revolution.',math:'90/360=1/4'}],trap:'Use 360 for a full circle.',takeaway:'Central-angle fraction equals arc fraction.'}},
        {id:'circle-sector',difficulty:'Core',skill:'Sector area',title:'Find a sector area',stem:'A circle has radius 6. Find the area of a 120-degree sector.',choices:['6π','12π','18π','36π'],choiceMath:true,answer:1,explanation:{steps:[{text:'Take one third of the circle area.',math:'\\frac{120}{360}\\pi(6)^2=12\\pi'}],trap:'Sector area uses radius squared.',takeaway:'Multiply total area by the angle fraction.'}},
        {id:'circle-radian',difficulty:'Core',skill:'Radians',title:'Convert an angle',stem:'What is 7π over 6 radians in degrees?',choices:['150°','180°','210°','240°'],answer:2,explanation:{steps:[{text:'Multiply by 180 over pi.',math:'\\frac{7\\pi}{6}\\cdot\\frac{180}{\\pi}=210^\\circ'}],trap:'Cancel pi before multiplying.',takeaway:'Pi radians equals 180 degrees.'}},
        {id:'circle-arc-reverse',difficulty:'Advanced',skill:'Reverse arc',title:'Recover a radius',stem:'An arc of length 8π has central angle 120 degrees. Find the radius.',choices:['6','8','12','24'],choiceMath:true,answer:2,explanation:{steps:[{text:'Use one third of circumference.',math:'8\\pi=\\frac13(2\\pi r)'},{text:'Solve.',math:'24\\pi=2\\pi r\\Rightarrow r=12'}],trap:'Eight pi is only one third of the circumference.',takeaway:'Reverse the circle fraction.'}},
        {id:'circle-sector-ratio',difficulty:'Advanced',skill:'Sector ratios',title:'Compare sectors',stem:'In the same circle, sector A has twice the area of sector B. If B has angle 54 degrees, what is A’s angle?',choices:['27°','54°','108°','216°'],answer:2,explanation:{steps:[{text:'Same-radius sector areas are proportional to central angles.',math:'\\theta_A=2(54)=108^\\circ'}],trap:'The radius cancels in a within-circle comparison.',takeaway:'Sector fraction tracks central angle.'}},
    ]},
};

const tangentsChordsAndInscribedAngles = {
    slug:'tangents-chords-and-inscribed-angles',moduleId:'circles-coordinate-geometry',title:'Tangents, Chords & Inscribed Angles',eyebrow:'Geometry and Trigonometry',minutes:'42 min',
    summary:'Use the circle theorems most likely to power difficult geometry questions: radius-tangent right angles, half-arc angles, equal tangents, and chord products.',
    goals:['Apply radius-tangent perpendicularity.','Relate inscribed angles to intercepted arcs.','Use diameter and semicircle angle consequences.','Solve equal-tangent and intersecting-chord problems.'],
    facts:[{label:'Tangent radius',math:'OT\\perp PT',note:'at the point of tangency'},{label:'Inscribed angle',math:'m\\angle=\\frac12m\\widehat{arc}',note:'vertex lies on circle'},{label:'Diameter angle',math:'90^\\circ',note:'an inscribed angle subtending a diameter'},{label:'Equal tangents',math:'PA=PB',note:'from the same external point'}],
    sections:[
        {heading:'Big idea 1: a tangent creates a right triangle',paragraphs:['A radius to the point of tangency is perpendicular to the tangent line. Connect the center to the tangent point if the segment is not drawn.','This often unlocks the Pythagorean theorem, special triangles, or trig.']},
        {heading:'Big idea 2: an inscribed angle sees half its arc',paragraphs:['A central angle equals its intercepted arc, while an inscribed angle equals half its intercepted arc. Identify the vertex location before choosing the multiplier.','All inscribed angles intercepting the same arc are equal. An angle intercepting a diameter is 90 degrees because the arc is 180 degrees.']},
        {heading:'Big idea 3: equal geometry creates algebraic equations',paragraphs:['Tangent segments drawn from one external point have equal lengths. Equal chords also intercept equal arcs, and equal arcs subtend equal central angles.','These facts often appear with side expressions or parameters.']},
        {heading:'Big idea 4: product theorems handle intersecting segments',paragraphs:['For chords intersecting inside a circle, the product of the two pieces of one chord equals the product of the two pieces of the other. A tangent-secant problem uses tangent length squared equals external secant part times whole secant.','Use the whole secant, not only its internal portion.']},
    ],
    formulas:[
        {label:'Inscribed-angle theorem',math:'m\\angle APB=\\frac12m\\widehat{AB}',note:'P must lie on the circle.',meaning:'An on-circle viewpoint sees half the central arc measure.',useWhen:'An angle’s vertex is on the circumference.'},
        {label:'Equal tangents',math:'PA=PB',note:'A and B are tangent points from external point P.',meaning:'The two tangent paths from one point have equal length.',useWhen:'Two tangents meet outside a circle.'},
        {label:'Intersecting chords',math:'AE\\cdot EB=CE\\cdot ED',note:'E is inside the circle.',meaning:'The products of the two chord-piece pairs are equal.',useWhen:'Two chords cross inside.'},
        {label:'Tangent-secant power',math:'PT^2=PA\\cdot PB',note:'PA is external; PB is the entire secant.',meaning:'Both paths from P share the same circle power.',useWhen:'A tangent and secant start at the same external point.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Use half an arc',prompt:'An inscribed angle intercepts a 136-degree arc. Find the angle.',math:'m\\angle=136^\\circ/2',steps:[{text:'Halve the arc.',math:'m\\angle=68^\\circ'}],insight:'The angle’s vertex is on the circle.',trap:'A central angle would equal 136 degrees.'},
        {level:'Core SAT',title:'Build a tangent right triangle',prompt:'A circle has radius 5. From external point P, OP equals 13 and PT is tangent. Find PT.',math:'5^2+PT^2=13^2',steps:[{text:'OT is perpendicular to PT.'},{text:'Solve.',math:'PT^2=144\\Rightarrow PT=12'}],insight:'The circle theorem creates a 5-12-13 triangle.',trap:'OP is the hypotenuse.'},
        {level:'Advanced',title:'Use a tangent-secant product',prompt:'A tangent from P has length x. A secant has external part 4 and whole length 25. Find x.',math:'x^2=4(25)',steps:[{text:'Multiply external by whole.',math:'x^2=100'},{text:'Use positive length.',math:'x=10'}],insight:'The theorem is a geometric mean relationship.',trap:'The internal secant portion is 21, but the product uses 25.'},
    ],
    strategyCards:[{title:'Locate the vertex',items:['At center: angle equals arc.','On circle: angle is half the arc.','Outside or inside intersections require other relationships.']},{title:'Add useful segments',items:['Draw radius to tangent point.','Draw a diameter when a semicircle is involved.','Mark whole secant as external plus internal.']},{title:'Check theorem conditions',items:['Tangents share one external point.','Chord intersection is inside.','Tangent-secant starts from the same external point.']}],
    studyTips:[{title:'Write “whole” over the secant',summary:'Most tangent-secant misses use only the inside length.',items:['Whole equals external plus internal.','External is the segment before entering the circle.','Tangent length is squared.']}],
    adaptiveDemo:{title:'Central or inscribed?',prompt:'An angle’s vertex lies on the circle and intercepts an 80-degree arc.',options:[{id:'inscribed',label:'40°',result:'Correct: an inscribed angle is half its arc.',advice:'Vertex location controls the relationship.'},{id:'central',label:'80°',result:'That would be a central angle.',advice:'A central angle’s vertex is at the center.'}]},
    quickCheck:{prompt:'Two tangent segments from point P measure 3x plus 4 and 5x minus 10. What is x?',choices:['3','7','14','21'],choiceMath:true,answer:1,explanation:'Tangent segments from one point are equal: three x plus four equals five x minus ten, giving fourteen equals two x and x equals seven.'},
    practiceSet:{title:'Circle theorems from foundation to hard Module 2',intro:'Identify the vertex or segment configuration before selecting a theorem.',questions:[
        {id:'circle-inscribed',difficulty:'Foundation',skill:'Inscribed angles',title:'Double the angle',stem:'An inscribed angle measures 47 degrees. Find its intercepted arc.',choices:['23.5°','47°','94°','133°'],answer:2,explanation:{steps:[{text:'The arc is twice the inscribed angle.',math:'2(47)=94^\\circ'}],trap:'The angle is half the arc.',takeaway:'Reverse the inscribed-angle theorem by doubling.'}},
        {id:'circle-diameter',difficulty:'Foundation',skill:'Semicircles',title:'Use a diameter',stem:'An inscribed angle intercepts a diameter. What is its measure?',choices:['45°','60°','90°','180°'],answer:2,explanation:{steps:[{text:'A diameter intercepts a 180-degree semicircle.',math:'180/2=90^\\circ'}],trap:'The angle is half the arc.',takeaway:'A diameter creates a right angle on the circle.'}},
        {id:'circle-tangent',difficulty:'Core',skill:'Tangents',title:'Use equal lengths',stem:'Tangent segments from P are 4x minus 1 and 2x plus 11. Find their common length.',choices:['6','12','17','23'],choiceMath:true,answer:3,explanation:{steps:[{text:'Set equal.',math:'4x-1=2x+11\\Rightarrow x=6'},{text:'Evaluate.',math:'4(6)-1=23'}],trap:'Six is x, not the tangent length.',takeaway:'Equal tangents create an equation.'}},
        {id:'circle-chords',difficulty:'Advanced',skill:'Intersecting chords',title:'Use chord products',stem:'Intersecting chord pieces are 3 and 8 on one chord, and 4 and x on the other. Find x.',choices:['2','6','8','12'],choiceMath:true,answer:1,explanation:{steps:[{text:'Set products equal.',math:'3(8)=4x'},{text:'Solve.',math:'x=6'}],trap:'Pair pieces on the same chord in each product.',takeaway:'Inside intersection uses chord-piece products.'}},
        {id:'circle-tangent-secant',difficulty:'Advanced',skill:'Power of a point',title:'Find a tangent',stem:'A secant has external length 5 and internal length 15. Find the tangent length from the same point.',choices:['10','10√2','15','20'],answer:0,explanation:{steps:[{text:'Find the whole secant.',math:'5+15=20'},{text:'Apply the theorem.',math:'t^2=5(20)=100\\Rightarrow t=10'}],trap:'Use external times whole, not external times internal.',takeaway:'Label every secant part before multiplying.'}},
    ]},
};

const circumferenceAreaAndCompositeCircles = {
    slug:'circumference-area-and-composite-circles',moduleId:'circles-coordinate-geometry',title:'Circumference, Area & Composite Circles',eyebrow:'Geometry and Trigonometry',minutes:'35 min',
    summary:'Choose radius or diameter correctly, model wheel motion, and solve shaded annulus and composite-region questions with exact units.',
    goals:['Use circumference and area formulas in both directions.','Distinguish radius, diameter, linear units, and square units.','Find annulus and shaded composite areas.','Connect revolutions to distance and solve parameterized circle measures.'],
    facts:[{label:'Circumference',math:'C=2\\pi r=\\pi d',note:'linear units'},{label:'Area',math:'A=\\pi r^2',note:'square units'},{label:'Diameter',math:'d=2r',note:'passes through center'},{label:'Annulus',math:'A=\\pi(R^2-r^2)',note:'outer disk minus inner disk'}],
    sections:[
        {heading:'Big idea 1: identify which length was given',paragraphs:['A radius runs center to circle; a diameter runs across the circle through its center and is twice as long. Label r or d before substituting.','Circumference measures boundary length, while area measures the filled interior. Their units reveal which formula belongs.']},
        {heading:'Big idea 2: reverse formulas carefully',paragraphs:['Given circumference, divide by two pi for radius or by pi for diameter. Given area, divide by pi and then take the positive square root.','Keep pi symbolic because it often cancels.']},
        {heading:'Big idea 3: composite regions use addition or subtraction',paragraphs:['An annulus is an outer circle minus an inner circle. A shaded figure may also be a square minus inscribed circle or a circle minus polygon.','Calculate each complete region separately, then combine them. Do not subtract radii before squaring.']},
        {heading:'Big idea 4: rolling turns circumference into distance',paragraphs:['One full wheel revolution travels one circumference when rolling without slipping. Multiply revolutions by circumference, or divide total distance by circumference to find revolutions.','Convert units before combining quantities.']},
    ],
    formulas:[
        {label:'Circle boundary',math:'C=2\\pi r=\\pi d',note:'Either version is equally valid.',meaning:'Circumference grows linearly with radius.',useWhen:'Finding boundary, wheel travel, or diameter from circumference.'},
        {label:'Disk area',math:'A=\\pi r^2',note:'Square the radius, not the diameter.',meaning:'A circle’s area grows with the square of its radius.',useWhen:'Finding interior or reversing from a known area.'},
        {label:'Annulus area',math:'A=\\pi R^2-\\pi r^2=\\pi(R^2-r^2)',note:'R is outer radius and r is inner radius.',meaning:'A ring is the difference of two concentric disks.',useWhen:'A circular border or track surrounds a disk.'},
        {label:'Rolling distance',math:'D=nC',note:'n is the number of complete revolutions.',meaning:'Each turn advances one boundary length.',useWhen:'A wheel, gear, or circular object rolls without slipping.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Reverse from circumference',prompt:'A circle has circumference 18 pi. Find its radius.',math:'18\\pi=2\\pi r',steps:[{text:'Cancel two pi.',math:'r=9'}],insight:'The diameter is eighteen, while the radius is nine.',trap:'Do not report the coefficient of pi automatically as radius.'},
        {level:'Core SAT',title:'Find an annulus area',prompt:'A circular path has outer radius 10 and inner radius 7. Find its area.',math:'A=\\pi(10^2-7^2)',steps:[{text:'Square before subtracting.',math:'A=\\pi(100-49)=51\\pi'}],insight:'The difference of squares can speed the arithmetic.',trap:'Pi times the square of three is not the same result.'},
        {level:'Advanced',title:'Count wheel revolutions',prompt:'A wheel with diameter 0.8 meter travels 120 pi meters. How many revolutions?',math:'n=\\frac{120\\pi}{0.8\\pi}',steps:[{text:'Circumference per turn is zero point eight pi.'},{text:'Divide.',math:'n=150'}],insight:'Using C equals pi d is direct when diameter is given.',trap:'Do not use area for rolling distance.'},
    ],
    strategyCards:[{title:'Use units as labels',items:['Circumference: units.','Area: square units.','Distance traveled: units.']},{title:'For shaded regions',items:['Identify the full outer shape.','Identify the removed shape.','Subtract completed formulas.']},{title:'For reverse problems',items:['Undo pi first.','Undo the numeric coefficient.','Take a square root only for area.']}],
    studyTips:[{title:'Keep pi until the end',summary:'Exact form is usually cleaner and makes cancellation visible.',items:['Do not replace pi with 3.14 unless asked.','Cancel pi in ratios.','Type exact pi forms when permitted.']}],
    adaptiveDemo:{title:'Choose the measure',prompt:'A circular wheel makes five full turns. What circle quantity controls travel distance?',options:[{id:'circ',label:'Circumference',result:'Correct.',advice:'One turn traces one boundary length.'},{id:'area',label:'Area',result:'Area measures the wheel’s face, not its travel.',advice:'Match linear distance to a linear circle measure.'}]},
    quickCheck:{prompt:'A circle’s area is 81π. What is its diameter?',choices:['9','18','40.5','81'],choiceMath:true,answer:1,explanation:'Radius squared is eighty-one, so radius is nine and diameter is eighteen.'},
    practiceSet:{title:'Circle measure and composite regions',intro:'Name radius or diameter and check target units.',questions:[
        {id:'circle-circ',difficulty:'Foundation',skill:'Circumference',title:'Use a diameter',stem:'A circle has diameter 14. Find its circumference.',choices:['7π','14π','28π','196π'],choiceMath:true,answer:1,explanation:{steps:[{text:'Use pi times diameter.',math:'C=\\pi(14)=14\\pi'}],trap:'No factor of two is needed when diameter is used.',takeaway:'Choose the matching circumference form.'}},
        {id:'circle-area',difficulty:'Foundation',skill:'Area',title:'Square the radius',stem:'A circle has radius 6. Find its area.',choices:['6π','12π','36π','72π'],choiceMath:true,answer:2,explanation:{steps:[{text:'Apply area.',math:'A=\\pi(6)^2=36\\pi'}],trap:'Area uses a squared radius.',takeaway:'Check square units.'}},
        {id:'circle-square-shade',difficulty:'Core',skill:'Composite area',title:'Subtract an inscribed circle',stem:'A circle of radius 5 is inscribed in a square. Find the area inside the square but outside the circle.',choices:['25-10π','25-25π','100-25π','100-100π'],choiceMath:true,answer:2,explanation:{steps:[{text:'The square side equals the diameter.',math:'s=10\\Rightarrow A_s=100'},{text:'Subtract circle area.',math:'100-25\\pi'}],trap:'The square side is ten, not five.',takeaway:'Use shared geometry to find missing dimensions.'}},
        {id:'circle-area-scale',difficulty:'Advanced',skill:'Scaling',title:'Scale circle area',stem:'A circle’s circumference is increased by 30 percent. By what percent does its area increase?',choices:['30%','60%','69%','90%'],answer:2,explanation:{steps:[{text:'Circumference scales linearly, so radius factor is one point three.'},{text:'Square for area.',math:'1.3^2=1.69'},{text:'Convert growth.',math:'69\\%'}],trap:'Area does not scale linearly with circumference.',takeaway:'Circle area follows the square of the length factor.'}},
        {id:'circle-roll',difficulty:'Advanced',skill:'Revolutions',title:'Reverse rolling distance',stem:'A wheel of radius 4 inches travels 96π inches. How many revolutions?',choices:['6','12','24','48'],choiceMath:true,answer:1,explanation:{steps:[{text:'Find circumference per turn.',math:'C=8\\pi'},{text:'Divide distance.',math:'96\\pi/(8\\pi)=12'}],trap:'Radius four gives circumference eight pi.',takeaway:'Revolutions equal distance over circumference.'}},
    ]},
};

const circleEquations = {
    slug:'circle-equations',moduleId:'circles-coordinate-geometry',title:'Circle Equations',eyebrow:'Geometry and Trigonometry',minutes:'43 min',
    summary:'Read and build circle equations, complete the square, locate intercepts, and combine coordinate algebra with tangent and distance conditions.',
    goals:['Identify a circle’s center and radius from standard form.','Write an equation from a center and point.','Complete the square to convert general form.','Test points and solve line-circle or tangency conditions.'],
    facts:[{label:'Standard form',math:'(x-h)^2+(y-k)^2=r^2',note:'center (h,k)'},{label:'Signs',value:'opposite inside parentheses',note:'x plus 3 means h is negative 3'},{label:'Radius',math:'r=\\sqrt{r^2}',note:'positive root'},{label:'On circle',math:'(x-h)^2+(y-k)^2=r^2',note:'distance from center equals r'}],
    sections:[
        {heading:'Big idea 1: the equation is a distance statement',paragraphs:['The squared horizontal and vertical changes from center h,k add to radius squared. This is the distance formula without its square root.','A point inside produces a smaller left side; a point outside produces a larger left side.']},
        {heading:'Big idea 2: signs are reversed in standard form',paragraphs:['The center coordinates are the values that make each squared expression zero. Thus x plus four means x minus negative four and center x-coordinate negative four.','The number on the right is radius squared, not radius.']},
        {heading:'Big idea 3: build radius from a point when needed',paragraphs:['If a center and point on the circle are given, use the distance formula to compute r squared directly. Substituting that value avoids an unnecessary square root.','Intercepts come from setting the other coordinate to zero.']},
        {heading:'Big idea 4: complete the square in x and y separately',paragraphs:['Group x terms and y terms. Add the square of half each linear coefficient to both sides, then factor each perfect-square trinomial.','If the resulting radius squared is negative, the equation has no real circle.']},
    ],
    formulas:[
        {label:'Circle standard form',math:'(x-h)^2+(y-k)^2=r^2',note:'Center is h comma k.',meaning:'Every point is distance r from one center.',useWhen:'Reading, graphing, or writing a circle.'},
        {label:'Radius from a point',math:'r^2=(x_1-h)^2+(y_1-k)^2',note:'Use squared distance directly.',meaning:'The center-to-point segment is a radius.',useWhen:'A center and one point on the circle are known.'},
        {label:'Completing-square pattern',math:'u^2+bu=\\left(u+\\frac b2\\right)^2-\\left(\\frac b2\\right)^2',note:'Apply separately to x and y.',meaning:'A linear term reveals a shifted square.',useWhen:'The circle is given in expanded general form.'},
        {label:'Tangent-line condition',math:'d(\\text{center},\\text{line})=r',note:'Equivalently, the radius to contact is perpendicular.',meaning:'A tangent line touches the circle at exactly one point.',useWhen:'A parameterized line must be tangent.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Read center and radius',prompt:'Identify the center and radius.',math:'(x+3)^2+(y-5)^2=49',steps:[{text:'Reverse the x sign and keep the y value.',math:'(h,k)=(-3,5)'},{text:'Take the positive root.',math:'r=7'}],insight:'The equation stores radius squared.',trap:'The x-coordinate is negative three.'},
        {level:'Core SAT',title:'Write a circle through a point',prompt:'A circle has center (2,-1) and passes through (8,7). Write its equation.',math:'r^2=(8-2)^2+(7+1)^2',steps:[{text:'Compute squared distance.',math:'r^2=36+64=100'},{text:'Write standard form.',math:'(x-2)^2+(y+1)^2=100'}],insight:'There is no need to calculate r separately.',trap:'Use opposite signs inside the parentheses.'},
        {level:'Advanced',title:'Complete both squares',prompt:'Find the center and radius.',math:'x^2+y^2-6x+8y-11=0',steps:[{text:'Move constant.',math:'x^2-6x+y^2+8y=11'},{text:'Add nine and sixteen to both sides.',math:'(x-3)^2+(y+4)^2=36'},{text:'Read features.',math:'\\text{center }(3,-4),\\ r=6'}],insight:'Each completed square contributes its added value to the right side.',trap:'Do not add only one completion constant.'},
    ],
    strategyCards:[{title:'Read standard form',items:['Center signs reverse.','Right side is r squared.','Compare a point’s squared distance with r squared.']},{title:'Write an equation',items:['Place center into shifted squares.','Find r squared from a point.','Keep exact integer or radical values.']},{title:'Complete the square',items:['Group x and y terms.','Add two completion constants to both sides.','Factor and verify positive radius squared.']}],
    studyTips:[{title:'Plug in the center',summary:'The correct center makes both squared expressions zero.',items:['This checks sign reading instantly.','The right side remains r squared.','A candidate point can be tested the same way.']}],
    adaptiveDemo:{title:'Classify a point',prompt:'For a circle centered at the origin with radius five, a point has x squared plus y squared equal to sixteen.',options:[{id:'inside',label:'Inside',result:'Correct: sixteen is less than radius squared twenty-five.',advice:'Compare squared distances; no square roots are needed.'},{id:'on',label:'On',result:'On the circle would require twenty-five.',advice:'Use equality only for boundary points.'}]},
    quickCheck:{prompt:'What is the radius of x² + y² + 4x - 10y + 13 = 0?',choices:['2','4','16','\\sqrt{13}'],choiceMath:true,answer:1,explanation:'Completing squares gives x plus two squared plus y minus five squared equals sixteen, so the radius is four.'},
    practiceSet:{title:'Circle equations from foundation to hard Module 2',intro:'Treat every equation as a squared-distance condition.',questions:[
        {id:'circle-eq-center',difficulty:'Foundation',skill:'Standard form',title:'Read a center',stem:'What is the center?',math:'(x-7)^2+(y+2)^2=36',choices:['(-7,2)','(-7,-2)','(7,2)','(7,-2)'],answer:3,explanation:{steps:[{text:'Reverse the signs inside.',math:'(h,k)=(7,-2)'}],trap:'The y center is negative two.',takeaway:'Center values make the squared expressions zero.'}},
        {id:'circle-eq-point',difficulty:'Core',skill:'Point testing',title:'Choose a point on a circle',stem:'Which point lies on x squared plus y squared equals 25?',choices:['(1,5)','(3,4)','(4,4)','(5,5)'],answer:1,explanation:{steps:[{text:'Test three comma four.',math:'3^2+4^2=9+16=25'}],trap:'Coordinates do not individually need to equal the radius.',takeaway:'On-circle points satisfy the equation exactly.'}},
        {id:'circle-eq-build',difficulty:'Core',skill:'Equation construction',title:'Use a diameter endpoint',stem:'A circle has center (1,2) and passes through (4,6). What is r squared?',choices:['5','7','12','25'],choiceMath:true,answer:3,explanation:{steps:[{text:'Find squared distance.',math:'(4-1)^2+(6-2)^2=9+16=25'}],trap:'The radius is five, but the equation uses twenty-five.',takeaway:'Compute r squared directly.'}},
        {id:'circle-eq-complete',difficulty:'Advanced',skill:'Completing square',title:'Find a radius',stem:'What is the radius?',math:'x^2+y^2+10x-4y+13=0',choices:['3','4','9','16'],choiceMath:true,answer:1,explanation:{steps:[{text:'Complete squares.',math:'(x+5)^2+(y-2)^2=16'},{text:'Take the positive root.',math:'r=4'}],trap:'Sixteen is r squared.',takeaway:'Complete both variables and read standard form.'}},
        {id:'circle-eq-intercept',difficulty:'Advanced',skill:'Intersections',title:'Find y-axis intercepts',stem:'A circle is (x minus 3) squared plus y squared equals 25. Which y-values occur where it crosses the y-axis?',choices:['±3','±4','±5','0 only'],choiceMath:true,answer:1,explanation:{steps:[{text:'Set x equal to zero.',math:'9+y^2=25'},{text:'Solve.',math:'y^2=16\\Rightarrow y=\\pm4'}],trap:'Both intercepts must be included.',takeaway:'Axis intersections come from setting the other coordinate to zero.'}},
    ]},
};

const distanceMidpointAndCoordinateProof = {
    slug:'distance-midpoint-and-coordinate-proof',moduleId:'circles-coordinate-geometry',title:'Distance, Midpoint & Coordinate Proof',eyebrow:'Geometry and Trigonometry',minutes:'37 min',
    summary:'Translate geometric claims into slope, midpoint, and distance calculations, then use them to verify shapes, centers, and circle relationships.',
    goals:['Calculate distance and midpoint accurately.','Use slope to prove parallel, perpendicular, or collinear relationships.','Recognize equal-distance and perpendicular-bisector conditions.','Classify coordinate figures without relying on appearance.'],
    facts:[{label:'Distance',math:'d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}',note:'Pythagorean theorem'},{label:'Midpoint',math:'M=(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2})',note:'average coordinates separately'},{label:'Parallel slopes',math:'m_1=m_2',note:'including separate vertical lines'},{label:'Perpendicular',math:'m_1m_2=-1',note:'plus horizontal-vertical case'}],
    sections:[
        {heading:'Big idea 1: distance is a hidden right triangle',paragraphs:['Horizontal and vertical coordinate changes are the legs. Squaring removes direction, so consistent subtraction order is all that matters.','Use squared distance when only comparing lengths; square roots may be unnecessary.']},
        {heading:'Big idea 2: midpoint averages positions',paragraphs:['Average x-coordinates and y-coordinates separately. A midpoint also acts as the center of a segment, rectangle diagonal pair, or circle diameter.','Given an endpoint and midpoint, double the midpoint then subtract the known endpoint to recover the other endpoint.']},
        {heading:'Big idea 3: slopes prove direction relationships',paragraphs:['Equal slopes show parallel or collinear direction; negative reciprocal slopes show perpendicular direction. Then use a shared point or intercept information to distinguish same line from separate parallels.','Horizontal and vertical lines form the special perpendicular pair.']},
        {heading:'Big idea 4: classify shapes with the minimum evidence',paragraphs:['Four equal side distances prove a rhombus; one right angle can upgrade it to a square. Equal diagonals and a common midpoint help prove a rectangle.','For a circle diameter, midpoint gives center and half the endpoint distance gives radius.']},
    ],
    formulas:[
        {label:'Squared distance',math:'d^2=(\\Delta x)^2+(\\Delta y)^2',note:'Compare d squared values without taking roots.',meaning:'Pythagorean theorem measures the straight-line separation.',useWhen:'Checking equal sides, radii, or nearest points.'},
        {label:'Midpoint',math:'M=\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2}\\right)',note:'Average coordinate components independently.',meaning:'The midpoint lies halfway in both horizontal and vertical directions.',useWhen:'Finding centers, bisectors, or missing endpoints.'},
        {label:'Slope',math:'m=\\frac{y_2-y_1}{x_2-x_1}',note:'Undefined when x coordinates match.',meaning:'Slope records direction and rate of vertical change.',useWhen:'Checking collinearity, parallelism, or perpendicularity.'},
        {label:'Missing endpoint',math:'x_2=2M_x-x_1,\\qquad y_2=2M_y-y_1',note:'Rearrange the midpoint formula.',meaning:'The midpoint is the average of the two endpoints.',useWhen:'One endpoint and the midpoint are known.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find a distance',prompt:'Find the distance from (-2,3) to (4,11).',math:'d=\\sqrt{6^2+8^2}',steps:[{text:'Compute coordinate changes.',math:'\\Delta x=6,\\ \\Delta y=8'},{text:'Evaluate.',math:'d=\\sqrt{100}=10'}],insight:'The coordinate differences form a 6-8-10 triangle.',trap:'Do not add signed changes before squaring.'},
        {level:'Core SAT',title:'Recover an endpoint',prompt:'One endpoint is (3,-5) and the midpoint is (8,2). Find the other endpoint.',math:'(x_2,y_2)=(2(8)-3,2(2)-(-5))',steps:[{text:'Compute each coordinate.',math:'(x_2,y_2)=(13,9)'}],insight:'The midpoint lies halfway from the known point to the unknown point.',trap:'Subtract the known coordinate after doubling the midpoint.'},
        {level:'Advanced',title:'Prove a right angle',prompt:'Points A(0,0), B(6,2), and C(4,8) form angle B. Show the angle is right.',math:'m_{AB}=\\frac13,\\qquad m_{BC}=\\frac{8-2}{4-6}=-3',steps:[{text:'Calculate the two slopes meeting at B.'},{text:'Multiply.',math:'(1/3)(-3)=-1'}],insight:'Negative reciprocal directions meet at 90 degrees.',trap:'Use segments that actually meet at the named vertex.'},
    ],
    strategyCards:[{title:'For distances',items:['Compute delta x and delta y.','Compare squared distances if possible.','Take the positive root only when needed.']},{title:'For coordinate proofs',items:['Slope proves direction.','Distance proves equal length.','Midpoint proves bisection or shared center.']},{title:'For circle connections',items:['Diameter endpoints average to center.','Radius is half the diameter distance.','A perpendicular bisector contains equal-distance centers.']}],
    studyTips:[{title:'Make a proof checklist',summary:'Use only the calculations that establish the requested property.',items:['Parallel: matching slopes.','Perpendicular: negative reciprocal slopes.','Equal sides: matching squared distances.','Bisected diagonals: matching midpoint.']}],
    adaptiveDemo:{title:'Choose the efficient calculation',prompt:'You need only decide whether two segments have equal length.',options:[{id:'squared',label:'Compare squared distances',result:'Correct.',advice:'Equal positive distances have equal squares, so skip radicals.'},{id:'root',label:'Simplify both radicals',result:'That works but may add arithmetic.',advice:'Stop at the earliest decisive comparison.'}]},
    quickCheck:{prompt:'What is the midpoint of (-6,8) and (10,-4)?',choices:['(2,2)','(4,4)','(8,-12)','(-16,12)'],answer:0,explanation:'Average x-coordinates to get two and y-coordinates to get two.'},
    practiceSet:{title:'Coordinate geometry and proof',intro:'Use slope for direction, distance for length, and midpoint for centers.',questions:[
        {id:'coord-distance',difficulty:'Foundation',skill:'Distance',title:'Find a horizontal distance',stem:'Find the distance between (-3,7) and (9,7).',choices:['6','12','14','18'],choiceMath:true,answer:1,explanation:{steps:[{text:'The y-values match, so use horizontal change.',math:'9-(-3)=12'}],trap:'Subtracting a negative becomes addition.',takeaway:'Axis-aligned distance needs no radical.'}},
        {id:'coord-midpoint',difficulty:'Foundation',skill:'Midpoint',title:'Average coordinates',stem:'Find the midpoint of (2,-6) and (8,4).',choices:['(3,-1)','(5,-1)','(5,5)','(10,-2)'],answer:1,explanation:{steps:[{text:'Average each pair.',math:'((2+8)/2,(-6+4)/2)=(5,-1)'}],trap:'Do not average all four numbers together.',takeaway:'Midpoint is componentwise average.'}},
        {id:'coord-collinear',difficulty:'Core',skill:'Slope',title:'Test collinearity',stem:'Which point lies on the line through (0,1) and (2,5)?',choices:['(3,6)','(3,7)','(4,8)','(5,9)'],answer:1,explanation:{steps:[{text:'Find slope.',math:'(5-1)/(2-0)=2'},{text:'Build line.',math:'y=2x+1'},{text:'Test choices.',math:'x=3\\Rightarrow y=7'}],trap:'Collinear points share the same line equation.',takeaway:'Slope plus a point determines the line.'}},
        {id:'coord-diameter',difficulty:'Advanced',skill:'Circle diameter',title:'Build a circle from a diameter',stem:'A circle diameter has endpoints (-2,1) and (4,9). What is the radius?',choices:['5','10','\\sqrt{20}','\\sqrt{52}'],choiceMath:true,answer:0,explanation:{steps:[{text:'Find diameter length.',math:'\\sqrt{6^2+8^2}=10'},{text:'Halve it.',math:'r=5'}],trap:'The endpoint distance is the diameter, not radius.',takeaway:'Diameter endpoints determine center and radius.'}},
        {id:'coord-perp-bisector',difficulty:'Advanced',skill:'Equidistance',title:'Use a perpendicular bisector',stem:'Points equidistant from A and B lie on which set?',choices:['The segment AB only','The line through A and B','The perpendicular bisector of AB','A circle centered at A'],answer:2,explanation:{steps:[{text:'The locus of points with equal distances to two fixed endpoints is their perpendicular bisector.'}],trap:'The midpoint is only one of infinitely many such points.',takeaway:'Equal-distance conditions identify a perpendicular bisector.'}},
    ]},
};

export const CIRCLES_COORDINATE_LESSONS = [
    arcsCentralAnglesAndSectors,
    tangentsChordsAndInscribedAngles,
    circumferenceAreaAndCompositeCircles,
    circleEquations,
    distanceMidpointAndCoordinateProof,
];
