const factoringPatterns = {
    slug: 'factoring-patterns',
    moduleId: 'quadratic-foundations',
    title: 'Factoring Patterns',
    eyebrow: 'Advanced Math',
    minutes: '36 min',
    summary: 'Factoring reverses multiplication. Use a reliable pattern scan to expose zeros, cancel valid factors, and solve parameter questions without blind guessing.',
    goals: [
        'Factor out a greatest common factor before using another pattern.',
        'Recognize difference-of-squares and perfect-square identities.',
        'Factor monic and nonmonic trinomials efficiently.',
        'Use roots, coefficients, and substitution on advanced structure questions.',
    ],
    facts: [
        {label: 'First scan', math: '\\operatorname{GCF}', note: 'every later step is easier after common factors leave'},
        {label: 'Two terms', math: 'A^2-B^2', note: 'difference of squares; a sum of squares does not factor over the reals'},
        {label: 'Three terms', math: 'ax^2+bx+c', note: 'test perfect-square structure, then use product and sum'},
        {label: 'Equation rule', math: 'uv=0', note: 'only a zero product lets you set factors equal to zero'},
    ],
    sections: [
        {
            heading: 'Big idea 1: factoring is reverse distribution',
            paragraphs: [
                'A factorization is correct only if multiplying it returns the original expression. That gives you a built-in check: compare the leading term, constant term, and middle term after a quick expansion.',
                'Always remove the greatest common factor first. Missing it can hide a difference of squares or make a trinomial look harder than it is.',
            ],
            math: 'ab+ac=a(b+c)',
        },
        {
            heading: 'Big idea 2: identities should be recognized as whole shapes',
            paragraphs: [
                'A difference of squares has exactly two squared terms separated by subtraction. A perfect-square trinomial has squared outer terms and a middle term equal to twice their product.',
                'Signs matter. A sum of squares does not split into real linear factors, while a perfect square with a negative middle term uses two matching negative signs.',
            ],
            math: '\\begin{aligned}A^2-B^2&=(A-B)(A+B)\\\\A^2\\pm2AB+B^2&=(A\\pm B)^2\\end{aligned}',
        },
        {
            heading: 'Big idea 3: nonmonic trinomials use product ac and sum b',
            paragraphs: [
                'When the leading coefficient is one, find two numbers whose product is the constant and whose sum is the linear coefficient. When the leading coefficient is not one, find two numbers whose product is the first coefficient times the constant.',
                'Split the middle term using those numbers, then factor by grouping. This method is systematic and avoids guessing factor pairs at random.',
            ],
            math: 'ax^2+bx+c,\\qquad mn=ac,\\quad m+n=b',
        },
        {
            heading: 'Big idea 4: structure can hide behind a substitution',
            paragraphs: [
                'An expression may be quadratic in a repeated chunk rather than in x itself. Rename the chunk, factor the simpler quadratic, then substitute back.',
                'On advanced questions, you may not need the full factorization. Root relationships or coefficient comparison can determine a missing parameter directly.',
            ],
            math: 'x^4-5x^2+4\\xrightarrow{u=x^2}u^2-5u+4',
        },
    ],
    formulas: [
        {
            label: 'Greatest common factor',
            math: 'ka+kb=k(a+b)',
            note: 'Include a negative common factor when it makes the leading term inside positive.',
            meaning: 'Every term shares the same multiplier k.',
            useWhen: 'Always scan for this before any special pattern.',
        },
        {
            label: 'Difference of squares',
            math: 'A^2-B^2=(A-B)(A+B)',
            note: 'The conjugate factors have opposite middle signs.',
            meaning: 'The cross terms cancel when the factors multiply.',
            useWhen: 'There are two perfect-square terms separated by subtraction.',
        },
        {
            label: 'Perfect-square trinomials',
            math: 'A^2+2AB+B^2=(A+B)^2,\\qquad A^2-2AB+B^2=(A-B)^2',
            note: 'Check both the outer squares and the exact middle term.',
            meaning: 'The quadratic has one repeated linear factor and one repeated root.',
            useWhen: 'The first and last terms are squares and the middle is twice their signed product.',
        },
        {
            label: 'Monic trinomial pattern',
            math: 'x^2+sx+p=(x+m)(x+n),\\qquad m+n=s,\\quad mn=p',
            note: 'The product controls same or opposite signs; the sum selects the pair.',
            meaning: 'The two factor constants add to the middle coefficient and multiply to the constant.',
            useWhen: 'The coefficient of the squared term is one.',
        },
        {
            label: 'AC grouping method',
            math: 'ax^2+bx+c=ax^2+mx+nx+c,\\qquad mn=ac,\\quad m+n=b',
            note: 'After splitting the middle term, factor the two pairs.',
            meaning: 'The chosen split creates a shared binomial factor.',
            useWhen: 'The leading coefficient is not one and no identity applies.',
        },
        {
            label: 'Zero-product property',
            math: 'UV=0\\Rightarrow U=0\\text{ or }V=0',
            note: 'First move every term to one side so the other side equals zero.',
            meaning: 'A product is zero only when at least one factor is zero.',
            useWhen: 'A factored equation, not merely an expression, must be solved.',
        },
        {
            label: 'Factor theorem',
            math: 'f(r)=0\\Longleftrightarrow(x-r)\\text{ is a factor of }f(x)',
            note: 'The root sign reverses inside its factor.',
            meaning: 'Zeros and linear factors are two descriptions of the same structure.',
            useWhen: 'A problem gives a root and asks for a factor or parameter.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Take the greatest common factor first',
            prompt: 'Factor the expression completely.',
            math: '6x^2-24',
            steps: [
                {text: 'Remove the common factor.', math: '6x^2-24=6(x^2-4)'},
                {text: 'Recognize the remaining difference of squares.', math: 'x^2-4=(x-2)(x+2)'},
                {text: 'Write the complete factorization.', math: '6(x-2)(x+2)'},
            ],
            insight: 'One expression can require more than one factoring pattern.',
            trap: 'Stopping at six times x squared minus four is not fully factored.',
        },
        {
            level: 'Foundation',
            title: 'Recognize a perfect-square trinomial',
            prompt: 'Factor the expression.',
            math: 'x^2-14x+49',
            steps: [
                {text: 'The outer terms are squares.', math: 'x^2=(x)^2,\\qquad49=7^2'},
                {text: 'Check the middle term.', math: '-2(x)(7)=-14x'},
                {text: 'Use the matching negative identity.', math: 'x^2-14x+49=(x-7)^2'},
            ],
            insight: 'A perfect square signals a repeated root.',
            trap: 'The square on the binomial is essential; the factor occurs twice.',
        },
        {
            level: 'Core SAT',
            title: 'Factor a monic trinomial by sign logic',
            prompt: 'Factor the expression.',
            math: 'x^2-3x-28',
            steps: [
                {text: 'The negative product requires opposite signs.', math: 'mn=-28'},
                {text: 'Choose the pair with sum negative three.', math: 'm=-7,\\qquad n=4'},
                {text: 'Write and verify the factors.', math: '(x-7)(x+4)'},
            ],
            insight: 'Product determines the sign pattern before the sum determines order.',
            trap: 'Seven and negative four sum to positive three, not negative three.',
        },
        {
            level: 'Core SAT',
            title: 'Use the AC method',
            prompt: 'Factor the nonmonic trinomial.',
            math: '6x^2+11x+3',
            steps: [
                {text: 'Multiply the first and last coefficients.', math: 'ac=6(3)=18'},
                {text: 'Find a pair with product eighteen and sum eleven.', math: '9+2=11,\\qquad9(2)=18'},
                {text: 'Split and group.', math: '6x^2+9x+2x+3=3x(2x+3)+1(2x+3)'},
                {text: 'Factor the shared binomial.', math: '(3x+1)(2x+3)'},
            ],
            insight: 'Grouping turns one four-term expression into two copies of the same binomial.',
            trap: 'Using factors of c alone works only when the leading coefficient is one.',
        },
        {
            level: 'Advanced',
            title: 'Find a parameter from a known factor',
            prompt: 'The displayed binomial is a factor. Find k.',
            math: 'x-3\\text{ is a factor of }x^2+kx-18',
            steps: [
                {text: 'A factor x minus three gives root three.', math: 'f(3)=0'},
                {text: 'Substitute the root.', math: '3^2+3k-18=0'},
                {text: 'Solve the linear equation.', math: '3k-9=0\\Rightarrow k=3'},
            ],
            insight: 'The factor theorem replaces a factoring problem with one substitution.',
            trap: 'Substitute positive three, not negative three.',
        },
        {
            level: 'Advanced',
            title: 'Factor a quadratic in disguise',
            prompt: 'Factor the expression completely over the real numbers.',
            math: 'x^4-13x^2+36',
            steps: [
                {text: 'Rename the repeated square.', math: 'u=x^2\\Rightarrow u^2-13u+36'},
                {text: 'Factor the quadratic in u.', math: 'u^2-13u+36=(u-4)(u-9)'},
                {text: 'Substitute back.', math: '(x^2-4)(x^2-9)'},
                {text: 'Finish both differences of squares.', math: '(x-2)(x+2)(x-3)(x+3)'},
            ],
            insight: 'Repeated structure matters more than the highest exponent.',
            trap: 'Stopping after substituting back leaves two real-factor patterns unfinished.',
        },
    ],
    strategyCards: [
        {
            title: 'Use the factoring scan',
            items: ['GCF first', 'Two terms: test a difference of squares', 'Three terms: test a perfect square, then product-and-sum'],
        },
        {
            title: 'Control signs before numbers',
            items: ['Positive product and negative sum: both signs negative', 'Positive product and positive sum: both signs positive', 'Negative product: opposite signs'],
        },
        {
            title: 'Know when to stop',
            items: ['Every nonconstant factor is irreducible over the requested number system', 'An equation is solved only after applying the zero-product property', 'A correct answer expands back to the original expression'],
        },
    ],
    studyTips: [
        {
            title: 'Build a pattern reflex, not a factor-pair list',
            summary: 'Classify the expression before searching for numbers.',
            items: ['Count terms', 'Circle a shared factor', 'Mark squared outer terms and the sign between them'],
        },
        {
            title: 'Check three coefficients',
            summary: 'A full expansion is usually unnecessary.',
            items: ['Multiply the first terms', 'Multiply the last terms', 'Add the two cross products for the middle term'],
        },
        {
            title: 'Keep zero visible when solving',
            summary: 'Factors can be set equal to zero only after the equation has zero on one side.',
            items: ['Move all terms first', 'Factor second', 'Solve every factor and check restrictions if denominators were present'],
        },
    ],
    adaptiveDemo: {
        title: 'Choose the first move',
        prompt: 'You see a quadratic with all coefficients divisible by four. What should happen first?',
        options: [
            {id: 'gcf', label: 'Factor out four', result: 'Correct: simplify the structure first.', advice: 'The remaining quadratic may reveal a special identity or smaller factor pair.'},
            {id: 'pairs', label: 'List factor pairs', result: 'Premature.', advice: 'Ignoring the common factor creates larger numbers and can hide the next pattern.'},
            {id: 'formula', label: 'Use the quadratic formula', result: 'Valid only for solving, but inefficient here.', advice: 'Factoring preserves structure and is usually faster when integer patterns are visible.'},
        ],
    },
    quickCheck: {
        prompt: 'Which expression is the complete factorization?',
        math: '9x^2-25',
        choices: ['(9x-5)(x+5)', '(3x-5)(3x+5)', '(3x-5)^2', '(9x-25)(x+1)'],
        choiceMath: true,
        answer: 1,
        explanation: 'Both terms are squares separated by subtraction. Use the conjugate factors three x minus five and three x plus five.',
    },
    practiceSet: {
        title: 'Factoring patterns from foundation to hard Module 2',
        intro: 'The set rewards classification, sign control, and structural shortcuts more than trial-and-error expansion.',
        questions: [
            {
                id: 'gcf', difficulty: 'Foundation', skill: 'GCF', title: 'Remove the common factor',
                stem: 'Which expression is equivalent?', math: '15x^2-10x',
                choices: ['5x(3x-2)', '5(3x-2)', '10x(5x-1)', '15x(x-10)'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Both terms share five x.', math: '15x^2-10x=5x(3x-2)'}], trap: 'Factoring out five alone is valid but not the greatest common factor.', takeaway: 'Include every shared numerical and variable factor.'},
            },
            {
                id: 'difference-squares', difficulty: 'Foundation', skill: 'Identity', title: 'Use conjugates',
                stem: 'Factor completely.', math: 'x^2-81',
                choices: ['(x-9)(x+9)', '(x-9)^2', '(x-81)(x+1)', 'Cannot be factored'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Recognize both squares.', math: 'x^2-81=x^2-9^2=(x-9)(x+9)'}], trap: 'A difference of squares uses opposite signs.', takeaway: 'Two squares with subtraction factor into conjugates.'},
            },
            {
                id: 'perfect-square', difficulty: 'Foundation', skill: 'Identity', title: 'Match the middle term',
                stem: 'Factor the trinomial.', math: 'x^2+12x+36',
                choices: ['(x+6)^2', '(x-6)^2', '(x+3)(x+12)', '(x+4)(x+9)'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'The constant is six squared and the middle is twice six x.', math: 'x^2+2(x)(6)+6^2=(x+6)^2'}], trap: 'Numbers that multiply to thirty-six must also add to twelve.', takeaway: 'Verify the exact middle term before declaring a perfect square.'},
            },
            {
                id: 'monic-negative', difficulty: 'Core', skill: 'Trinomial', title: 'Control opposite signs',
                stem: 'Factor the expression.', math: 'x^2+5x-24',
                choices: ['(x+8)(x-3)', '(x-8)(x+3)', '(x+6)(x-4)', '(x-6)(x+4)'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Find product negative twenty-four and sum five.', math: '8(-3)=-24,\\qquad8+(-3)=5'}], trap: 'Reversing the signs changes the middle coefficient to negative five.', takeaway: 'For a negative product, give the larger magnitude the sum’s sign.'},
            },
            {
                id: 'nonmonic', difficulty: 'Core', skill: 'AC method', title: 'Split the middle term',
                stem: 'Factor the expression.', math: '4x^2+12x+5',
                choices: ['(2x+1)(2x+5)', '(4x+1)(x+5)', '(2x-1)(2x-5)', '(4x+5)(x+1)'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Use product twenty and sum twelve.', math: '10+2=12'}, {text: 'Group.', math: '4x^2+10x+2x+5=(2x+1)(2x+5)'}], trap: 'The constant pair alone does not determine the middle coefficient.', takeaway: 'For nonmonic trinomials, use product a times c.'},
            },
            {
                id: 'gcf-identity', difficulty: 'Core', skill: 'Multiple patterns', title: 'Factor twice',
                stem: 'Factor completely.', math: '3x^3-27x',
                choices: ['3x(x-3)(x+3)', '3x(x-9)', '3(x^3-9x)', 'x(3x-9)(x+3)'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Remove three x.', math: '3x(x^2-9)'}, {text: 'Factor the difference of squares.', math: '3x(x-3)(x+3)'}], trap: 'Stopping after the GCF leaves a factorable quadratic.', takeaway: 'Repeat the scan after every factoring step.'},
            },
            {
                id: 'solve-zero-product', difficulty: 'Core', skill: 'Solving', title: 'Set the equation equal to zero',
                stem: 'What is the positive solution?', math: 'x^2-7x=18',
                choices: ['2', '3', '9', '18'], choiceMath: true, answer: 2,
                explanation: {steps: [{text: 'Move eighteen left.', math: 'x^2-7x-18=0'}, {text: 'Factor and solve.', math: '(x-9)(x+2)=0\\Rightarrow x=9,-2'}], trap: 'Factoring the left side before moving eighteen does not create a zero product.', takeaway: 'The zero-product property requires zero on one side.'},
            },
            {
                id: 'known-factor-parameter', difficulty: 'Advanced', skill: 'Factor theorem', title: 'Use a supplied factor',
                stem: 'If x plus two is a factor, what is k?', math: 'f(x)=x^2+kx-10',
                choices: ['-7', '-3', '3', '7'], choiceMath: true, answer: 1,
                explanation: {steps: [{text: 'The factor gives root negative two.', math: 'f(-2)=0'}, {text: 'Substitute and solve.', math: '4-2k-10=0\\Rightarrow-2k=6\\Rightarrow k=-3'}], trap: 'The factor x plus two corresponds to negative two.', takeaway: 'Use the factor theorem to turn the parameter problem linear.'},
            },
            {
                id: 'missing-constant-square', difficulty: 'Advanced', skill: 'Perfect square', title: 'Complete a factor pattern',
                stem: 'For what positive value of c is the expression a perfect-square trinomial?', math: '9x^2-30x+c',
                choices: ['10', '25', '50', '100'], choiceMath: true, answer: 1,
                explanation: {steps: [{text: 'Match the first term to three x squared.', math: '(3x-d)^2=9x^2-6dx+d^2'}, {text: 'Match the middle coefficient.', math: '-6d=-30\\Rightarrow d=5'}, {text: 'Square the constant.', math: 'c=d^2=25'}], trap: 'Half of thirty is not enough because the leading square is three x, not x.', takeaway: 'Match the identity before halving coefficients mechanically.'},
            },
            {
                id: 'quadratic-disguise', difficulty: 'Advanced', skill: 'Substitution', title: 'Rename a repeated power',
                stem: 'Which is a factor of the expression?', math: 'x^4-10x^2+9',
                choices: ['x-1', 'x-2', 'x-4', 'x-10'], choiceMath: true, answer: 0,
                explanation: {steps: [{text: 'Use u equal to x squared.', math: 'u^2-10u+9=(u-1)(u-9)'}, {text: 'Substitute back.', math: '(x^2-1)(x^2-9)'}], trap: 'Treating the fourth-degree expression as an ordinary x-quadratic hides the repeated square.', takeaway: 'A polynomial can be quadratic in x squared.'},
            },
            {
                id: 'coefficient-comparison', difficulty: 'Advanced', skill: 'Parameters', title: 'Compare a factored identity',
                stem: 'The identity holds for every x. What is p?', math: '6x^2+px-20=(3x-5)(2x+4)',
                choices: ['-22', '2', '8', '22'], choiceMath: true, answer: 1,
                explanation: {steps: [{text: 'Add the cross products for the linear coefficient.', math: '(3x)(4)+(-5)(2x)=12x-10x=2x'}, {text: 'Match coefficients.', math: 'p=2'}], trap: 'Multiplying twelve and negative ten instead of adding them confuses the middle-term rule.', takeaway: 'The linear coefficient is the sum of the cross products.'},
            },
            {
                id: 'root-expression', difficulty: 'Advanced', skill: 'Structure', title: 'Use roots without fully solving',
                stem: 'The positive numbers r and s satisfy the equation shown. What is the value of their product?', math: '(x-r)(x-s)=x^2-11x+24',
                choices: ['11', '12', '24', '35'], choiceMath: true, answer: 2,
                explanation: {steps: [{text: 'Expand only the structural coefficients.', math: '(x-r)(x-s)=x^2-(r+s)x+rs'}, {text: 'Match constant terms.', math: 'rs=24'}], trap: 'Eleven is the root sum, not the product.', takeaway: 'Factored-to-standard coefficient matching can answer symmetric root questions instantly.'},
            },
        ],
    },
};

export default factoringPatterns;
