const interceptsAsStartingValues = {
    slug: 'intercepts-as-starting-values',
    moduleId: 'linear-functions-systems',
    title: 'Intercepts as Starting Values',
    eyebrow: 'Algebra',
    minutes: '30 min',
    summary: 'Intercepts mark what happens when one variable is zero, but their real meaning depends on the quantities, units, and allowed domain.',
    goals: [
        'Find x- and y-intercepts from equations, tables, and contexts.',
        'Explain what an intercept means—and when it has no practical meaning.',
        'Build a linear equation from its intercepts or use intercept form directly.',
        'Solve harder parameter and coordinate-geometry questions with intercept shortcuts.',
    ],
    facts: [
        {label: 'y-intercept', value: 'x = 0', note: 'the output before any input has accumulated'},
        {label: 'x-intercept', value: 'y = 0', note: 'the input where the output reaches zero'},
        {label: 'Function notation', value: 'f(0)', note: 'another name for the y-intercept value'},
        {label: 'Context check', value: 'domain matters', note: 'an algebraic intercept may lie outside the realistic inputs'},
    ],
    sections: [
        {
            heading: 'Big idea 1: an intercept is a zero-input condition',
            paragraphs: [
                'The y-intercept occurs where x = 0, so it often represents an initial amount, base fee, starting height, or value before time passes. In function notation, its y-value is f(0).',
                'The x-intercept occurs where y = 0, so it often represents a break-even point, an emptying time, a stopping distance, or the input that makes an output disappear.',
            ],
        },
        {
            heading: 'Big idea 2: setting a variable to zero is safer than memorizing',
            paragraphs: [
                'To find the y-intercept, set x = 0 and solve for y. To find the x-intercept, set y = 0 and solve for x. This axis rule works in slope-intercept form, standard form, and unfamiliar equations.',
                'Remember the full coordinate: a y-intercept is (0, b), not just b, and an x-intercept is (a, 0). SAT questions sometimes switch between asking for the value and asking for the point.',
            ],
        },
        {
            heading: 'Big idea 3: algebraic and practical meaning can differ',
            paragraphs: [
                'A model may have an x-intercept at a negative input even when the real situation allows only nonnegative time, distance, or item counts. The intercept exists on the full line but may have no meaning in the model.',
                'Always check the domain and units before interpreting. A negative time or a fractional number of people may be algebraically valid but physically impossible.',
            ],
        },
        {
            heading: 'Big idea 4: intercepts reveal geometry and parameters',
            paragraphs: [
                'Two intercepts are two points, so they determine a nonvertical line. You can find the slope between them, use intercept form, or build an equation from either point.',
                'On harder questions, parameter values may be hidden in a required intercept. Substitute the intercept point into the original equation; this is usually faster and safer than deriving the entire line first.',
            ],
        },
    ],
    formulas: [
        {
            label: 'Slope-intercept form',
            math: 'y=mx+b \\Rightarrow \\text{y-intercept }(0,b)',
            note: 'Set x = 0 and the mx term disappears.',
            meaning: 'b is the output at input zero, while m controls every later change.',
            useWhen: 'The equation is already solved for y or the question asks for an initial value.',
        },
        {
            label: 'x-intercept from slope-intercept form',
            math: '0=mx+b \\Rightarrow x=-\\frac{b}{m},\\quad m\\ne0',
            note: 'Set the output to zero and solve for the input.',
            meaning: 'The starting amount b is canceled after -b/m input units of change.',
            useWhen: 'A line crosses the x-axis and its equation is y = mx + b.',
        },
        {
            label: 'Standard-form intercept shortcuts',
            math: 'Ax+By=C \\Rightarrow \\left(\\frac{C}{A},0\\right),\\ \\left(0,\\frac{C}{B}\\right)',
            note: 'The first point is the x-intercept and the second is the y-intercept.',
            meaning: 'Setting one variable to zero leaves a one-step equation in the other.',
            useWhen: 'A, B, and C are convenient divisors and neither A nor B is zero.',
        },
        {
            label: 'Intercept form',
            math: '\\frac{x}{a}+\\frac{y}{b}=1',
            note: 'The intercepts are (a, 0) and (0, b).',
            meaning: 'Each coordinate is measured as a fraction of the way to its axis intercept.',
            useWhen: 'Both intercepts are given or can be read quickly from a graph.',
        },
        {
            label: 'Triangle area from intercepts',
            math: '\\text{Area}=\\frac{1}{2}|ab|',
            note: 'This is the area enclosed by the coordinate axes and a line with intercepts (a, 0) and (0, b).',
            meaning: 'The absolute intercept lengths are the base and height of a right triangle.',
            useWhen: 'A coordinate-geometry problem asks for the region bounded by a line and the axes.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Find both intercepts from y = mx + b',
            prompt: 'Find both intercepts of y = -3x + 12.',
            math: 'y=-3x+12',
            steps: [
                'For the y-intercept, set x = 0: y = 12, so the point is (0, 12).',
                'For the x-intercept, set y = 0: 0 = -3x + 12.',
                'Solve 3x = 12 to get x = 4, so the point is (4, 0).',
            ],
            insight: 'The line begins at y = 12 and loses 3 y-units per x-unit, so it takes 4 x-units to reach zero.',
            trap: 'The x-intercept is not the constant 12; it is the input that makes the entire output zero.',
        },
        {
            level: 'Core SAT',
            title: 'Use standard-form shortcuts',
            prompt: 'Find the intercepts of 3x + 2y = 18.',
            math: '3x+2y=18',
            steps: [
                'Set y = 0: 3x = 18, so x = 6 and the x-intercept is (6, 0).',
                'Set x = 0: 2y = 18, so y = 9 and the y-intercept is (0, 9).',
                'Equivalently, use C/A = 18/3 and C/B = 18/2.',
            ],
            insight: 'You do not need to solve for y to find intercepts in standard form.',
            trap: 'Keep the coordinate order straight: (6, 0) is the x-intercept, not (0, 6).',
        },
        {
            level: 'Applied',
            title: 'Decide whether an intercept is realistic',
            prompt: 'A taxi fare for m miles is C = 4.50 + 2.20m dollars. Interpret both algebraic intercepts for the domain m ≥ 0.',
            math: 'C=4.50+2.20m',
            steps: [
                'At m = 0, C = 4.50, so the y-intercept is a $4.50 starting fee.',
                'Set C = 0: 0 = 4.50 + 2.20m, giving m ≈ -2.05.',
                'The x-intercept exists on the extended line but lies outside the domain m ≥ 0.',
            ],
            insight: 'The y-intercept has a useful practical meaning; the negative-mile x-intercept does not.',
            trap: 'Do not force every algebraic feature to represent a possible real event.',
        },
        {
            level: 'Core SAT',
            title: 'Interpret when a quantity reaches zero',
            prompt: 'A tank contains V = 150 - 12t liters after t minutes. Find and interpret both intercepts.',
            math: 'V=150-12t',
            steps: [
                'At t = 0, V = 150, so the tank starts with 150 liters.',
                'Set V = 0: 150 - 12t = 0.',
                'Solve 12t = 150 to get t = 12.5 minutes.',
            ],
            insight: 'The x-intercept is often the answer to “when will none remain?” in a decreasing model.',
            trap: 'The slope -12 is the draining rate, not the emptying time.',
        },
        {
            level: 'Advanced',
            title: 'Use a required intercept to find a parameter',
            prompt: 'The line y = (k - 1)x + 6 has x-intercept 2. Find k.',
            math: '0=(k-1)(2)+6',
            steps: [
                'An x-intercept of 2 means the point (2, 0) lies on the line.',
                'Substitute x = 2 and y = 0: 0 = 2(k - 1) + 6.',
                'Expand: 0 = 2k + 4, so k = -2.',
                'Check: y = -3x + 6 reaches zero at x = 2.',
            ],
            insight: 'Substituting the known intercept point is faster than finding a general intercept formula in k.',
            trap: 'An x-intercept of 2 means x = 2 and y = 0, not x = 0 and y = 2.',
        },
        {
            level: 'Advanced',
            title: 'Find an enclosed area without graphing',
            prompt: 'The line 2x + 3y = 12 and the coordinate axes enclose a triangle. Find its area.',
            math: '2x+3y=12',
            steps: [
                'Set y = 0 to get the x-intercept x = 6.',
                'Set x = 0 to get the y-intercept y = 4.',
                'The triangle has base 6 and height 4.',
                'Area = (1/2)(6)(4) = 12 square units.',
            ],
            insight: 'Intercepts convert an algebra question into a right-triangle area question.',
            trap: 'Multiplying 6 by 4 gives the surrounding rectangle; the triangle is half that area.',
        },
    ],
    strategyCards: [
        {
            title: 'The axis rule',
            items: ['For a y-intercept, set x = 0', 'For an x-intercept, set y = 0', 'Report a point if the question asks where the graph crosses'],
        },
        {
            title: 'Interpret before accepting',
            items: ['Attach the intercept value to its units', 'Check whether zero input is allowed', 'Check whether the other intercept lies inside the model domain'],
        },
        {
            title: 'Advanced shortcuts',
            items: ['In Ax + By = C, use C/A and C/B', 'Substitute a required intercept directly to find a parameter', 'Use one-half times the intercept lengths for an axes-bounded triangle'],
        },
    ],
    studyTips: [
        {
            title: 'Say “set the other variable to zero”',
            summary: 'This sentence is more reliable than trying to remember which intercept uses which variable.',
            items: [
                'An axis consists of points where the other coordinate is zero.',
                'Write the zero substitution before doing arithmetic.',
                'Finish with an ordered pair when the question asks for a point.',
            ],
        },
        {
            title: 'Separate mathematical and contextual answers',
            summary: 'A line extends forever, but most real models do not.',
            items: [
                'Find the algebraic intercept first.',
                'Compare its input with the stated or implied domain.',
                'If it is outside the domain, say that the intercept exists mathematically but is not meaningful in context.',
            ],
        },
        {
            title: 'Connect intercepts back to slope',
            summary: 'Using both features together makes line questions much faster.',
            items: [
                'Sketch the two intercepts and predict the slope sign before calculating.',
                'Compute slope between (a, 0) and (0, b) as -b/a.',
                'Check whether the sign agrees with the direction of your sketch.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Choose the useful intercept',
        prompt: 'A gym charges C = 25 + 8m dollars for m months. Which intercept deserves a real-world interpretation?',
        options: [
            {
                id: 'y-intercept',
                label: 'The y-intercept',
                result: 'At 0 months, the cost is $25.',
                advice: 'The y-intercept is the one-time joining fee before monthly charges accumulate.',
            },
            {
                id: 'x-intercept',
                label: 'The x-intercept',
                result: 'It occurs at m = -25/8.',
                advice: 'Negative months are outside the model domain, so this algebraic intercept is not a possible gym scenario.',
            },
        ],
    },
    quickCheck: {
        prompt: 'What is the y-intercept of 4x + 3y = 24?',
        choices: ['(0, 6)', '(0, 8)', '(6, 0)', '(8, 0)'],
        answer: 1,
        explanation: 'Set x = 0: 3y = 24, so y = 8. Because the question asks for the y-intercept point, the answer is (0, 8).',
    },
    practiceSet: {
        title: 'Intercepts from foundation to hard Module 2',
        intro: 'The set progresses from direct intercepts to domain interpretation, equation building, geometry, and parameter reconstruction.',
        questions: [
            {
                id: 'read-y-intercept',
                difficulty: 'Foundation',
                skill: 'Slope-intercept form',
                title: 'Read the constant term',
                stem: 'What is the y-intercept of y = 5x - 7?',
                choices: ['(-7, 0)', '(0, -7)', '(0, 5)', '(5, 0)'],
                answer: 1,
                explanation: {
                    steps: ['The equation is in y = mx + b form with b = -7.', 'The y-intercept point is (0, -7).'],
                    trap: 'The coefficient 5 is the slope, not the y-intercept.',
                    takeaway: 'In y = mx + b, the y-intercept is (0, b).',
                },
            },
            {
                id: 'solve-x-intercept',
                difficulty: 'Foundation',
                skill: 'Zero output',
                title: 'Set y equal to zero',
                stem: 'What is the x-intercept of y = 2x - 10?',
                choices: ['(0, -10)', '(0, 5)', '(5, 0)', '(10, 0)'],
                answer: 2,
                explanation: {
                    steps: ['Set y = 0: 0 = 2x - 10.', 'Then 2x = 10, so x = 5.', 'The point is (5, 0).'],
                    trap: 'The constant -10 is not the x-intercept.',
                    takeaway: 'An x-intercept always has y-coordinate zero.',
                },
            },
            {
                id: 'standard-x-intercept',
                difficulty: 'Core',
                skill: 'Standard form',
                title: 'Remove the y-term',
                stem: 'What is the x-intercept of 3x + 2y = 18?',
                choices: ['(0, 6)', '(0, 9)', '(6, 0)', '(9, 0)'],
                answer: 2,
                explanation: {
                    steps: ['Set y = 0: 3x = 18.', 'Solve x = 6, giving (6, 0).'],
                    trap: 'Dividing by the y-coefficient 2 finds the y-intercept instead.',
                    takeaway: 'For the x-intercept of Ax + By = C, compute C/A.',
                },
            },
            {
                id: 'standard-y-intercept',
                difficulty: 'Core',
                skill: 'Standard form',
                title: 'Remove the x-term',
                stem: 'What is the y-intercept of -4x + 5y = 20?',
                choices: ['(-5, 0)', '(0, -5)', '(0, 4)', '(4, 0)'],
                answer: 2,
                explanation: {
                    steps: ['Set x = 0: 5y = 20.', 'Solve y = 4, giving (0, 4).'],
                    trap: 'The negative x-coefficient disappears when x = 0; it does not make the intercept negative.',
                    takeaway: 'For the y-intercept of Ax + By = C, compute C/B.',
                },
            },
            {
                id: 'table-intercept',
                difficulty: 'Core',
                skill: 'Table',
                title: 'Find the zero-input row',
                stem: 'A linear table contains (-2, -1), (0, 3), and (4, 11). What is the y-intercept?',
                choices: ['(-2, -1)', '(0, 3)', '(3, 0)', '(4, 11)'],
                answer: 1,
                explanation: {
                    steps: ['The y-intercept occurs when x = 0.', 'The table row with x = 0 is (0, 3).'],
                    trap: 'The y-intercept is not the row where y is closest to zero.',
                    takeaway: 'Look for x = 0 in a table before doing any calculations.',
                },
            },
            {
                id: 'context-initial-fee',
                difficulty: 'Applied',
                skill: 'Interpretation',
                title: 'Explain a starting value',
                stem: 'Equipment rental costs C = 40 + 15h dollars for h hours. What does the y-intercept represent?',
                choices: ['A $15 starting fee', 'A $40 starting fee', 'The rental lasts 15 hours', 'The rental lasts 40 hours'],
                answer: 1,
                explanation: {
                    steps: ['At h = 0, C = 40.', 'Therefore the y-intercept represents a $40 fee before hourly charges.'],
                    trap: 'The coefficient 15 is the hourly rate, not the initial fee.',
                    takeaway: 'The y-intercept is the output before the input begins accumulating.',
                },
            },
            {
                id: 'context-empty',
                difficulty: 'Applied',
                skill: 'Interpretation',
                title: 'When the output reaches zero',
                stem: 'A battery has D = 96 - 8t percent-charge units remaining after t hours. What does the x-intercept represent?',
                choices: ['The battery starts at 8', 'The battery starts at 96', 'The battery reaches zero after 8 hours', 'The battery reaches zero after 12 hours'],
                answer: 3,
                explanation: {
                    steps: ['Set D = 0: 96 - 8t = 0.', 'Then 8t = 96, so t = 12.', 'The x-intercept represents when no charge remains.'],
                    trap: 'The rate 8 is not the time required to reach zero.',
                    takeaway: 'In a decreasing model, the x-intercept often gives a depletion time.',
                },
            },
            {
                id: 'outside-domain',
                difficulty: 'Applied',
                skill: 'Domain',
                title: 'Reject an impossible interpretation',
                stem: 'A model y = 6x + 18 applies only for x ≥ 0. Which statement about its x-intercept is correct?',
                choices: ['It is x = 3 and is meaningful', 'It is x = -3 and is meaningful', 'It is x = -3 but lies outside the model domain', 'The line has no x-intercept'],
                answer: 2,
                explanation: {
                    steps: ['Set y = 0: 0 = 6x + 18.', 'Solve x = -3.', 'Because the model requires x ≥ 0, -3 is outside its domain.'],
                    trap: 'A restricted model can exclude an intercept that exists on the full algebraic line.',
                    takeaway: 'Find the mathematical feature, then test it against the context domain.',
                },
            },
            {
                id: 'equation-from-intercepts',
                difficulty: 'Advanced',
                skill: 'Equation building',
                title: 'Turn two intercepts into a line',
                stem: 'Which equation has x-intercept (4, 0) and y-intercept (0, -2)?',
                choices: ['y = -2x + 4', 'y = -(1/2)x + 2', 'y = (1/2)x - 2', 'y = 2x - 4'],
                answer: 2,
                explanation: {
                    steps: ['The slope is (0 - (-2))/(4 - 0) = 2/4 = 1/2.', 'The y-intercept is -2.', 'Therefore y = (1/2)x - 2.'],
                    trap: 'A positive slope is required because the line rises from (0, -2) to (4, 0).',
                    takeaway: 'Two intercepts provide both a slope and the constant term.',
                },
            },
            {
                id: 'parameter-intercept',
                difficulty: 'Advanced',
                skill: 'Parameter',
                title: 'Force the line through an axis point',
                stem: 'The line y = (k + 2)x - 15 has x-intercept 3. What is k?',
                math: '0=3(k+2)-15',
                choices: ['1', '2', '3', '5'],
                answer: 2,
                explanation: {
                    steps: ['Substitute the x-intercept point (3, 0).', 'Then 0 = 3(k + 2) - 15.', 'So 3(k + 2) = 15, k + 2 = 5, and k = 3.'],
                    trap: 'Setting x = 0 would use the y-intercept instead of the given x-intercept.',
                    takeaway: 'Substitute a known intercept as a full ordered pair.',
                },
            },
            {
                id: 'triangle-area',
                difficulty: 'Advanced',
                skill: 'Coordinate geometry',
                title: 'Use intercepts as base and height',
                stem: 'The line 5x + 2y = 20 and the coordinate axes enclose a triangle. What is its area?',
                choices: ['10', '14', '20', '40'],
                answer: 2,
                explanation: {
                    steps: ['The x-intercept is 20/5 = 4.', 'The y-intercept is 20/2 = 10.', 'Area = (1/2)(4)(10) = 20.'],
                    trap: 'The product 4 × 10 is the rectangle area; the axes-bounded region is a triangle.',
                    takeaway: 'Use half the product of the absolute intercept lengths.',
                },
            },
            {
                id: 'two-parameter-reconstruction',
                difficulty: 'Advanced',
                skill: 'Parameters',
                title: 'Reconstruct coefficients from intercepts',
                stem: 'The line px + qy = 12 has intercepts (3, 0) and (0, -4). What is p + q?',
                choices: ['-7', '1', '7', '12'],
                answer: 1,
                explanation: {
                    steps: ['Substitute (3, 0): 3p = 12, so p = 4.', 'Substitute (0, -4): -4q = 12, so q = -3.', 'Therefore p + q = 4 + (-3) = 1.'],
                    trap: 'The negative y-intercept makes q negative.',
                    takeaway: 'Each intercept eliminates one variable and isolates one coefficient.',
                },
            },
        ],
    },
};

export default interceptsAsStartingValues;
