const diagnoseEveryMiss = {
    slug:'diagnose-every-miss',moduleId:'review-system',title:'Diagnose Every Miss',eyebrow:'Mistake Review',minutes:'32 min',
    summary:'Turn every wrong, guessed, or slow question into a precise diagnosis that tells you what to study and what habit to change.',
    goals:['Review wrong, guessed, and unusually slow answers.','Separate concept, translation, process, reading, calculator, and timing errors.','Find the first incorrect decision rather than the last arithmetic symptom.','Write one specific prevention rule for each reviewed question.'],
    facts:[{label:'Review set',value:'wrong + guessed + slow',note:'correct does not always mean mastered'},{label:'Root cause',value:'first wrong decision',note:'not merely final arithmetic'},{label:'Useful label',value:'specific and actionable',note:'for example “used diameter as radius”'},{label:'Output',value:'one prevention rule',note:'short enough to use next time'}],
    sections:[
        {heading:'Big idea 1: score hides fragile correct answers',paragraphs:['A lucky guess, an answer reached with an invalid step, or a four-minute success belongs in review alongside misses. Mark confidence and time during practice so these questions are visible.','Mastery means you can reproduce a valid method within a reasonable time.']},
        {heading:'Big idea 2: classify the first failure',paragraphs:['Concept errors mean the rule or formula was unknown. Translation errors misread what variables or relationships meant. Process errors include algebra, arithmetic, or incomplete checking. Reading errors miss a qualifier, unit, or requested quantity. Calculator and timing errors deserve their own labels.','A final sign error may have begun earlier with poor equation setup, so replay the solution from the start.']},
        {heading:'Big idea 3: make labels narrow enough to prescribe action',paragraphs:['“Careless” does not identify a fix. “Reported x instead of the requested 3x,” “used area scale k instead of k squared,” and “read y-coordinate instead of x-coordinate” each suggest a concrete checkpoint.','Tag both content skill and error type so patterns can be counted.']},
        {heading:'Big idea 4: end with a rule, not a copied solution',paragraphs:['Write a prevention rule that can transfer: “Circle the requested quantity before solving” or “Check degree mode before trig.” Then write the clean solution in your own words.','If you cannot explain why your answer failed and why the correct method works, the review is not complete.']},
    ],
    formulas:[
        {label:'Review priority',math:'\\text{wrong}\\cup\\text{guessed}\\cup\\text{slow}',note:'Include correct answers with low confidence.',meaning:'Hidden weaknesses matter before they become scored misses.',useWhen:'Choosing questions for an error log.'},
        {label:'Diagnosis chain',math:'\\text{prompt}\\rightarrow\\text{first decision}\\rightarrow\\text{first failure}\\rightarrow\\text{fix}',note:'Stop at the earliest cause.',meaning:'Later arithmetic often reflects an earlier misunderstanding.',useWhen:'A solution contains several wrong steps.'},
        {label:'Actionable entry',math:'\\text{skill}+\\text{error type}+\\text{evidence}+\\text{rule}',note:'Keep the rule short and testable.',meaning:'An error log should drive future practice.',useWhen:'Recording a reviewed question.'},
        {label:'Example rule',math:'\\text{“Answer target = angle, not parameter”}',note:'Specific beats “be careful.”',meaning:'A visible cue interrupts the same mistake next time.',useWhen:'The work was correct but the reported quantity was wrong.'},
    ],
    workedExamples:[
        {level:'Review',title:'Diagnose a geometry miss',prompt:'A circle has diameter 12. A student uses pi times twelve squared for area.',math:'A=\\pi(6)^2',steps:[{text:'First failure: treated diameter as radius.'},{text:'Category: translation or formula-input error.'},{text:'Rule: label d and r before substituting; r equals d over two.'}],insight:'The arithmetic was fine; the input meaning was wrong.',trap:'Calling this “careless” would not prescribe a fix.'},
        {level:'Review',title:'Diagnose a correct but slow solution',prompt:'A student expands and solves two quadratics separately to find where their graphs are equal, taking five minutes.',math:'f(x)=g(x)',steps:[{text:'The answer may be correct, but method choice was inefficient.'},{text:'Category: strategy or timing.'},{text:'Rule: set models equal first; shared terms may cancel, or graph intersections.'}],insight:'Correct work can still reveal a scoring risk.',trap:'Do not log only questions marked wrong.'},
        {level:'Review',title:'Find the first failure',prompt:'A student correctly solves x equals 7 but selects 7 when the question asks for 2x plus 1.',math:'2(7)+1=15',steps:[{text:'The algebra is not the cause.'},{text:'Category: reading or target error.'},{text:'Rule: box the final requested expression before solving.'}],insight:'Diagnose the reporting decision rather than reteaching equation solving.',trap:'Redoing ten equations would not address this pattern.'},
    ],
    strategyCards:[{title:'Error categories',items:['Concept or formula.','Translation or setup.','Algebra or arithmetic process.','Reading, calculator, or timing.']},{title:'Evidence to record',items:['What you thought at the first wrong step.','Why that step fails.','What cue should trigger the correct move.']},{title:'Avoid vague labels',items:['Replace “careless” with the exact action.','Replace “did not know” with the missing rule.','Replace “too hard” with the first blocked step.']}],
    studyTips:[{title:'Review while memory is fresh',summary:'Record the initial diagnosis soon after the set, then retake later.',items:['Fresh review preserves your actual reasoning.','Delayed retake tests learning rather than short-term memory.','Keep the original response visible in the log, not during the retake.']}],
    adaptiveDemo:{title:'Choose the diagnosis',prompt:'A student reads intersection (3,10) and answers 10 when the question asks when the models are equal.',options:[{id:'target',label:'Target-reading error',result:'Correct.',advice:'The student needed the input x equals three, not the shared output.'},{id:'concept',label:'Unknown intersection concept',result:'The student found the intersection but copied the wrong coordinate.',advice:'Diagnose the earliest step that actually failed.'}]},
    quickCheck:{prompt:'Which error-log note is most useful?',choices:['Careless','Got it wrong','Used 360 instead of 180 for a triangle angle sum; write 180 beside every triangle','Need more math'],answer:2,explanation:'The third note identifies the exact incorrect rule and a concrete prevention cue.'},
    practiceSet:{title:'Error diagnosis scenarios',intro:'Name the first failure and the next-time rule.',questions:[
        {id:'review-diagnose-guess',difficulty:'Review',skill:'Review selection',title:'Include fragile correct answers',stem:'You guessed correctly with no setup. Should the question enter the review log?',choices:['No, because it was correct','Yes, because the skill was not demonstrated','Only if it was geometry','Only after the real SAT'],answer:1,explanation:{steps:[{text:'A correct guess does not prove repeatable knowledge.'}],trap:'Score alone hides confidence.',takeaway:'Review guessed and slow answers too.'}},
        {id:'review-diagnose-mode',difficulty:'Review',skill:'Calculator',title:'Classify a mode error',stem:'A student uses radian mode for a 40-degree trig problem. Which label is best?',choices:['Concept: quadratics','Calculator: angle mode','Reading: punctuation','Timing: skipped question'],answer:1,explanation:{steps:[{text:'The incorrect calculator setting caused the output.'}],trap:'Use the narrowest supported cause.',takeaway:'Specific categories lead to specific fixes.'}},
        {id:'review-diagnose-scale',difficulty:'Review',skill:'Concept',title:'Find the missing rule',stem:'A student doubles side lengths and says area doubles. What is the root cause?',choices:['Forgot area uses k²','Forgot the quadratic formula','Misread a y-intercept','Rounded too early'],answer:0,explanation:{steps:[{text:'Area is two-dimensional and scales by the square of the length factor.'}],trap:'The arithmetic may be simple, but the dimension rule is missing.',takeaway:'State the exact concept gap.'}},
        {id:'review-diagnose-rule',difficulty:'Review',skill:'Prevention',title:'Choose a transferable rule',stem:'You repeatedly report a solved parameter instead of the requested angle. Which rule is best?',choices:['Try harder','Use Desmos every time','Box the requested quantity and substitute back before choosing','Skip geometry'],answer:2,explanation:{steps:[{text:'The rule directly interrupts the repeated reporting error.'}],trap:'A useful rule must be actionable.',takeaway:'Connect diagnosis to a next-time behavior.'}},
    ]},
};

const retakeMissedQuestions = {
    slug:'retake-missed-questions',moduleId:'review-system',title:'Retake Missed Questions',eyebrow:'Mistake Review',minutes:'35 min',
    summary:'Use delayed, closed-solution retakes and small variants to prove that a mistake has become durable knowledge rather than temporary recognition.',
    goals:['Redo misses without viewing the prior solution.','Use spaced retakes instead of immediate copying.','Explain why each wrong choice fails.','Solve a transfer variant before marking a skill mastered.'],
    facts:[{label:'First redo',value:'after reviewing the cause',note:'from a blank page'},{label:'Delayed check',value:'1–3 days later',note:'tests recall'},{label:'Transfer',value:'same skill, changed surface',note:'tests generalization'},{label:'Mastered',value:'correct + explained + timely',note:'not recognition alone'}],
    sections:[
        {heading:'Big idea 1: close the solution before redoing',paragraphs:['Reading a solution creates familiarity, which can feel like mastery. Start from a blank page and rebuild the setup, naming the rule that applies.','If you immediately reproduce remembered steps without understanding them, explain why each step is legal.']},
        {heading:'Big idea 2: space the checks',paragraphs:['An immediate correction confirms understanding in the moment. A delayed retake checks whether the trigger and method remain available after memory fades.','A practical cycle is same-day diagnosis, a one-to-three-day retake, and a later mixed-set appearance.']},
        {heading:'Big idea 3: explain distractors and the clean path',paragraphs:['For multiple choice, identify what error each tempting choice represents. This builds recognition of traps such as radius-versus-diameter, x-versus-requested-expression, or percent-change denominator.','Then write a shorter correct solution than your original attempt when possible.']},
        {heading:'Big idea 4: use a variant to test transfer',paragraphs:['Change numbers, orientation, representation, or wording while keeping the underlying skill. If you can solve only the exact original, you may have memorized rather than learned.','Mark mastery only after a correct, justified, reasonably timed variant.']},
    ],
    formulas:[
        {label:'Retake cycle',math:'\\text{diagnose}\\rightarrow\\text{blank-page redo}\\rightarrow\\text{delay}\\rightarrow\\text{variant}',note:'Return the skill to a mixed set later.',meaning:'Each stage tests a deeper level of retrieval and transfer.',useWhen:'A reviewed question needs to become reliable.'},
        {label:'Mastery test',math:'\\text{correct}\\cap\\text{explainable}\\cap\\text{efficient}',note:'All three conditions matter.',meaning:'Durable SAT skill includes accuracy, reasoning, and usable pacing.',useWhen:'Deciding whether to close an error-log entry.'},
        {label:'Variant dimensions',math:'\\{\\text{numbers, wording, graph/table, target, context}\\}',note:'Change one or two while preserving the skill.',meaning:'Surface changes reveal whether the concept transfers.',useWhen:'Creating the next practice question.'},
        {label:'Confidence check',math:'\\text{answer first, then compare explanation}',note:'Do not read the rationale before committing.',meaning:'Retrieval must happen without solution cues.',useWhen:'Using My Practice or a question bank explanation.'},
    ],
    workedExamples:[
        {level:'Review',title:'Retake a circle mistake',prompt:'Original miss used diameter as radius. Redo: a circle has circumference 20 pi; find area.',math:'20\\pi=2\\pi r',steps:[{text:'Solve radius.',math:'r=10'},{text:'Use area.',math:'A=100\\pi'},{text:'State the cue: circumference coefficient here is diameter, then halve for radius.'}],insight:'The redo directly targets the diagnosed input confusion.',trap:'Do not peek at the original solution.'},
        {level:'Transfer',title:'Change the representation',prompt:'Original question gave an equation; variant gives a graph intersection and asks for the same system solution.',math:'\\text{intersection}=(x,y)',steps:[{text:'State that both equations are true at the point.'},{text:'Read the requested coordinate or expression.'},{text:'Substitute to verify if needed.'}],insight:'Changing representation tests whether the idea, not the steps, was learned.',trap:'Do not make every variant numerically identical.'},
        {level:'Transfer',title:'Explain a distractor',prompt:'A triangle parameter is x equals 12, but the requested angle is 65 degrees. Explain why 12 appears as a choice.',math:'x=12\\quad\\text{but target}=f(x)=65^\\circ',steps:[{text:'Twelve is the intermediate parameter.'},{text:'The final instruction requires substitution.'},{text:'Prevention cue: box the requested noun.'}],insight:'Distractor explanations reveal the test writer’s likely error path.',trap:'Knowing the correct letter is not enough.'},
    ],
    strategyCards:[{title:'Blank-page redo',items:['Hide all solution steps.','Name the governing rule.','Solve and check from the original prompt.']},{title:'Delayed retake',items:['Wait one to three days.','Use normal timing.','Record confidence before checking.']},{title:'Transfer proof',items:['Change representation or target.','Explain tempting wrong answers.','Return the skill in a mixed set.']}],
    studyTips:[{title:'Keep a “not yet” status',summary:'An entry stays open until a delayed variant is correct and explainable.',items:['Immediate correction is progress.','Delayed retrieval is stronger evidence.','Mixed-context success is the best closure signal.']}],
    adaptiveDemo:{title:'Is the skill mastered?',prompt:'You copy the official explanation correctly immediately after reading it.',options:[{id:'notyet',label:'Not yet',result:'Correct.',advice:'Close the solution, wait, and solve a variant independently.'},{id:'yes',label:'Yes',result:'Copying demonstrates recognition, not independent retrieval.',advice:'Require a blank-page delayed retake.'}]},
    quickCheck:{prompt:'Which is the strongest evidence of mastery?',choices:['Recognizing the correct answer','Remembering the answer letter','Solving a changed version correctly and explaining why','Reading the solution twice'],answer:2,explanation:'A changed version requires independent retrieval and transfer rather than recognition.'},
    practiceSet:{title:'Retake-system decisions',intro:'Choose evidence of learning, not familiarity.',questions:[
        {id:'review-retake-peek',difficulty:'Review',skill:'Retrieval',title:'Set up a real retake',stem:'What should you do with the old solution during a redo?',choices:['Keep it open beside your work','Hide it until after committing an answer','Copy its first line','Memorize the answer letter'],answer:1,explanation:{steps:[{text:'Independent retrieval requires removing solution cues.'}],trap:'Familiarity can feel like understanding.',takeaway:'Redo from a blank page.'}},
        {id:'review-retake-delay',difficulty:'Review',skill:'Spacing',title:'Test durable recall',stem:'Why redo again after one to three days?',choices:['To change the SAT score directly','To test recall after short-term memory fades','To avoid all mixed practice','To make the numbers harder'],answer:1,explanation:{steps:[{text:'Spacing distinguishes durable learning from immediate memory.'}],trap:'The goal is retrieval, not arbitrary delay.',takeaway:'Use multiple review intervals.'}},
        {id:'review-retake-variant',difficulty:'Review',skill:'Transfer',title:'Choose a useful variant',stem:'You missed circle area by using diameter as radius. Which variant best checks transfer?',choices:['The identical question with the same numbers','A new circle question giving circumference and asking area','An unrelated grammar question','Reading the same explanation'],answer:1,explanation:{steps:[{text:'The new surface still requires identifying radius before area.'}],trap:'A useful variant preserves the underlying skill.',takeaway:'Change representation while holding the concept.'}},
        {id:'review-retake-close',difficulty:'Review',skill:'Mastery',title:'Close an error entry',stem:'When should an entry be marked mastered?',choices:['After seeing the answer','After one lucky correct guess','After a correct, explained, timely delayed variant','After a week regardless of practice'],answer:2,explanation:{steps:[{text:'Accuracy, explanation, timing, and delay provide stronger evidence.'}],trap:'Time alone does not create mastery.',takeaway:'Use explicit closure criteria.'}},
    ]},
};

const buildAWeeklyWeaknessMap = {
    slug:'build-a-weekly-weakness-map',moduleId:'review-system',title:'Build a Weekly Weakness Map',eyebrow:'Mistake Review',minutes:'33 min',
    summary:'Convert a week of practice into an evidence-based plan that balances accuracy, speed, difficulty, and SAT content coverage.',
    goals:['Aggregate results by domain, skill, difficulty, error type, and time.','Distinguish low accuracy from slow but accurate performance.','Prioritize weaknesses by likely score impact and readiness.','Build a balanced next-week loop of learning, targeted practice, and mixed retrieval.'],
    facts:[{label:'Track',value:'accuracy + time + confidence',note:'score alone is incomplete'},{label:'Group by',value:'skill and error type',note:'not just broad domain'},{label:'Priority',value:'frequency × impact × fixability',note:'use judgment, not one rigid formula'},{label:'Weekly mix',value:'targeted + mixed + retake',note:'learning and recognition both matter'}],
    sections:[
        {heading:'Big idea 1: broad domain scores are only the first layer',paragraphs:['“Geometry” is too broad to prescribe a study session. Break it into lines and triangles, right-triangle trig, area and volume, and circles, then separate specific error types.','Use official domain reports and your own question log together.']},
        {heading:'Big idea 2: accuracy and speed describe different problems',paragraphs:['Low accuracy with normal speed often signals a concept or setup gap. High accuracy with excessive time suggests fluency or method-choice work. Fast low accuracy may indicate rushing or shallow reading.','Confidence adds another signal: low-confidence correct answers deserve reinforcement.']},
        {heading:'Big idea 3: prioritize patterns, not dramatic one-offs',paragraphs:['A repeated medium-skill error may cost more than one spectacular hard-question miss. Prioritize frequent errors, foundational skills that unlock several topics, and fixes you can practice deliberately.','Still include some hard mixed work so advanced recognition continues developing.']},
        {heading:'Big idea 4: every week needs three modes',paragraphs:['Learn or relearn the concept, complete targeted questions until the setup is stable, then use mixed questions to practice identifying the skill without a label.','Schedule delayed retakes from the prior week so old weaknesses do not disappear from view.']},
    ],
    formulas:[
        {label:'Accuracy',math:'\\text{accuracy}=\\frac{\\text{correct}}{\\text{attempted}}',note:'Separate guessed-correct questions when possible.',meaning:'Accuracy measures outcomes, not confidence or efficiency.',useWhen:'Comparing skill performance across sets.'},
        {label:'Average time',math:'\\bar t=\\frac{\\sum t_i}{n}',note:'Also inspect unusually slow individual questions.',meaning:'Timing data distinguishes fluency gaps from knowledge gaps.',useWhen:'A skill feels correct but expensive.'},
        {label:'Priority lens',math:'\\text{frequency}\\times\\text{score impact}\\times\\text{fixability}',note:'Treat this as a ranking lens, not fake precision.',meaning:'The best next topic is not always the hardest miss.',useWhen:'Choosing among several weaknesses.'},
        {label:'Balanced block',math:'\\text{relearn}\\rightarrow\\text{targeted reps}\\rightarrow\\text{mixed retrieval}\\rightarrow\\text{retake}',note:'Short blocks repeated beat one giant cram.',meaning:'The sequence builds knowledge, fluency, recognition, and retention.',useWhen:'Planning the next week.'},
    ],
    workedExamples:[
        {level:'Planning',title:'Choose between two weaknesses',prompt:'You missed 5 of 8 percent questions and 1 of 2 hard circle questions. Which should usually come first?',math:'\\text{percent: repeated and foundational}',steps:[{text:'Percent has more evidence and more frequent exposure.'},{text:'Repair the percent concept and setup pattern first.'},{text:'Keep one circle session later in the week.'}],insight:'Frequency and score impact can outweigh emotional difficulty.',trap:'Do not let the most intimidating single question control the whole plan.'},
        {level:'Planning',title:'Diagnose slow accuracy',prompt:'You answered 9 of 10 linear-system questions correctly but averaged three minutes.',math:'\\text{accuracy high, fluency low}',steps:[{text:'Keep concept review brief.'},{text:'Practice method choice: elimination, substitution, or graphing.'},{text:'Use timed small sets and record which method was fastest.'}],insight:'The prescription differs from a knowledge gap.',trap:'More untimed explanation reading may not fix speed.'},
        {level:'Planning',title:'Build a balanced week',prompt:'Circles are the priority skill and three old misses need retakes.',math:'\\text{learn}+\\text{target}+\\text{mix}+\\text{retake}',steps:[{text:'Day 1: theorem review plus untimed examples.'},{text:'Day 2: targeted official circle questions by difficulty.'},{text:'Day 3: mixed geometry set and delayed retakes.'},{text:'End of week: short mixed Math set to test recognition.'}],insight:'The plan alternates acquisition and retrieval.',trap:'Do not practice only labeled circle sets all week.'},
    ],
    strategyCards:[{title:'Weekly data',items:['Skill, difficulty, and source.','Correct, guessed, or wrong.','Time, confidence, and error category.']},{title:'Priority signals',items:['Repeated medium or foundational misses.','High-confidence wrong answers.','Correct answers that are consistently too slow.']},{title:'Plan balance',items:['One primary weakness.','One maintenance skill.','Delayed retakes and a mixed set.']}],
    studyTips:[{title:'Limit the priority list',summary:'One or two main skills create enough repetition to improve.',items:['Do not rotate across ten weaknesses daily.','Keep strong domains alive with a few mixed questions.','Rebuild the map from new evidence each week.']}],
    adaptiveDemo:{title:'Choose the next focus',prompt:'A skill is 90 percent accurate but very slow; another is 45 percent accurate at normal speed.',options:[{id:'lowacc',label:'Repair 45% accuracy first',result:'Usually correct.',advice:'Address the knowledge or setup gap, while adding short fluency work for the slow skill.'},{id:'slow',label:'Ignore low accuracy',result:'That leaves a larger reliability gap.',advice:'Use both accuracy and time, but severe accuracy problems usually lead.'}]},
    quickCheck:{prompt:'Which data point most strongly suggests a method-fluency problem rather than a concept gap?',choices:['Low accuracy and normal time','High accuracy and very high time','High confidence and wrong answers','No attempts'],answer:1,explanation:'Correct but consistently slow work suggests the concept is present but method selection or execution needs fluency.'},
    practiceSet:{title:'Weekly planning decisions',intro:'Match the evidence pattern to the right intervention.',questions:[
        {id:'review-map-broad',difficulty:'Planning',skill:'Granularity',title:'Make a label actionable',stem:'Which weakness label is most useful?',choices:['Math','Geometry','Circle tangent and inscribed-angle setup','Hard stuff'],answer:2,explanation:{steps:[{text:'The narrow label identifies a teachable, practiceable skill.'}],trap:'Broad domains do not prescribe a session.',takeaway:'Plan at the skill level.'}},
        {id:'review-map-rush',difficulty:'Planning',skill:'Evidence',title:'Diagnose fast low accuracy',stem:'A set shows low accuracy and unusually fast time. What should you inspect first?',choices:['Rushing and reading','Only formula memorization','Computer battery','Essay structure'],answer:0,explanation:{steps:[{text:'Fast misses often indicate skipped constraints or shallow setup.'}],trap:'Do not assume every miss is missing content.',takeaway:'Combine outcome and timing evidence.'}},
        {id:'review-map-priority',difficulty:'Planning',skill:'Prioritization',title:'Choose repeated impact',stem:'Which usually deserves higher priority?',choices:['One isolated exotic miss','A repeated algebra sign error across six questions','A correct easy question','A topic not on the SAT'],answer:1,explanation:{steps:[{text:'Frequency across questions creates repeated score risk.'}],trap:'Drama is not the same as impact.',takeaway:'Prioritize patterns.'}},
        {id:'review-map-mix',difficulty:'Planning',skill:'Practice design',title:'Add recognition practice',stem:'After mastering a skill in labeled drills, what should come next?',choices:['Only more identical drills','A mixed set without topic labels','No further practice','Memorize answer letters'],answer:1,explanation:{steps:[{text:'Mixed practice tests whether you can identify when the skill applies.'}],trap:'The real SAT does not label each question’s method.',takeaway:'Targeted fluency must transfer to mixed recognition.'}},
    ]},
};

const bluebookPracticeTestHandoff = {
    slug:'bluebook-practice-test-handoff',moduleId:'review-system',title:'Bluebook Practice Test Handoff',eyebrow:'Mistake Review',minutes:'35 min',
    summary:'Use official adaptive Bluebook tests as periodic checkpoints, then convert My Practice results into targeted Question Bank work and a new study cycle.',
    goals:['Decide when a full-length official practice test is useful.','Reproduce test-day conditions and use Bluebook tools intentionally.','Review every wrong, guessed, and slow item in My Practice.','Hand results back into targeted official practice and delayed retakes.'],
    facts:[{label:'Best checkpoint',value:'after a study block',note:'not as daily practice'},{label:'Environment',value:'realistic and uninterrupted',note:'same device type when possible'},{label:'Review source',value:'My Practice explanations',note:'inspect why every choice works or fails'},{label:'Next reps',value:'Student Question Bank',note:'filter by domain, skill, and difficulty'}],
    sections:[
        {heading:'Big idea 1: use full tests to measure integration',paragraphs:['A Bluebook practice test is most useful after you have studied several skills and need to measure pacing, stamina, mixed recognition, and adaptive-module decisions. Daily full tests consume scarce official material without enough time for repair.','Use shorter targeted or mixed sets between checkpoints.']},
        {heading:'Big idea 2: make the checkpoint realistic',paragraphs:['Use the device and calculator plan you expect on test day, follow module timing and break rules, silence distractions, and finish in one sitting when possible.','Practice Bluebook tools such as Mark for Review, Question Menu, calculator, reference sheet, and option eliminator without letting the tools interrupt your reasoning.']},
        {heading:'Big idea 3: the score starts the review',paragraphs:['In My Practice, inspect every question you missed, guessed, or solved too slowly. Read why the correct choice works and why each incorrect choice fails, then write your own diagnosis and clean solution.','Separate content weakness from pacing, interpretation, and calculator issues.']},
        {heading:'Big idea 4: hand results back into the study loop',paragraphs:['Use domain and skill evidence to choose targeted Student Question Bank questions, including hard difficulty when your score-band evidence supports it. Retake original misses after a delay and add variants.','Take the next full test only after the resulting priority work has had time to change your behavior.']},
    ],
    formulas:[
        {label:'Checkpoint loop',math:'\\text{study}\\rightarrow\\text{Bluebook test}\\rightarrow\\text{My Practice review}\\rightarrow\\text{targeted bank}\\rightarrow\\text{retest}',note:'The repair phase is the largest part of the cycle.',meaning:'A score becomes valuable when it changes the next plan.',useWhen:'Scheduling official full-length practice.'},
        {label:'Review scope',math:'\\text{wrong}\\cup\\text{guessed}\\cup\\text{slow}\\cup\\text{low confidence}',note:'Do not limit review to red marks.',meaning:'Fragile correct answers predict future misses.',useWhen:'Exporting questions from a completed test into your log.'},
        {label:'Official filtering',math:'\\text{section}\\rightarrow\\text{domain}\\rightarrow\\text{skill}\\rightarrow\\text{difficulty}',note:'Use the Student Question Bank to target the evidence.',meaning:'Filters turn a broad score report into specific practice.',useWhen:'Building the repair set.'},
        {label:'Retest condition',math:'\\text{priority work completed}+\\text{delayed retakes passed}',note:'Avoid retesting only to chase a number.',meaning:'A new checkpoint should measure changed preparation.',useWhen:'Deciding whether to use another official practice test.'},
    ],
    workedExamples:[
        {level:'Planning',title:'Decide whether to test or drill',prompt:'You took a full test two days ago and have not reviewed 18 flagged Math questions.',math:'\\text{review before another test}',steps:[{text:'Diagnose all flagged questions.'},{text:'Complete targeted skill repair and delayed retakes.'},{text:'Use a shorter mixed set before scheduling the next full test.'}],insight:'Another score would repeat measurement without intervention.',trap:'More testing is not automatically more learning.'},
        {level:'Review',title:'Use My Practice explanations actively',prompt:'You selected a distractor caused by using the full perimeter as length plus width.',math:'2l+2w=P\\Rightarrow l+w=P/2',steps:[{text:'Explain why the chosen option reflects the wrong constraint.'},{text:'Write the clean equation and solution.'},{text:'Add rule: halve perimeter before expressing the two side sum.'}],insight:'Distractor analysis becomes a reusable warning.',trap:'Do not merely copy the correct letter.'},
        {level:'Planning',title:'Build the handoff set',prompt:'Results show repeated hard misses in circles and one isolated volume miss.',math:'\\text{priority: circles}',steps:[{text:'Filter official practice to Math, Geometry and Trigonometry, Circles, then appropriate difficulty.'},{text:'Include a small area-volume maintenance item.'},{text:'Retake the original circle questions after delay.'}],insight:'The next set follows pattern strength rather than one-off emotion.',trap:'Do not drill the whole Geometry domain equally when evidence is specific.'},
    ],
    strategyCards:[{title:'Before the test',items:['Choose a realistic uninterrupted block.','Use the intended device and calculator.','Set a review date before starting.']},{title:'During the test',items:['Use Mark for Review deliberately.','Record or remember low-confidence items.','Protect later questions with two-pass pacing.']},{title:'After the test',items:['Review explanations for all choices.','Build a skill-level weakness map.','Create targeted official sets and delayed retakes.']}],
    studyTips:[{title:'Protect official material',summary:'Use full tests as spaced checkpoints and the Question Bank for frequent targeted work.',items:['A test diagnoses integration.','Targeted sets repair specific skills.','Mixed sets bridge repair back to test conditions.']}],
    adaptiveDemo:{title:'Choose the next action',prompt:'Your score report shows a circle weakness, and you have not yet reviewed the missed items.',options:[{id:'review',label:'Review, then target circles',result:'Correct.',advice:'Use explanations to diagnose the exact circle skill and error type before filtering practice.'},{id:'newtest',label:'Take another full test now',result:'That measures again before repair.',advice:'Complete diagnosis and targeted practice first.'}]},
    quickCheck:{prompt:'Which questions belong in post-test review?',choices:['Only incorrect questions','Only the hardest five','Incorrect, guessed, slow, and low-confidence questions','Only questions with calculator use'],answer:2,explanation:'Fragile correct and slow answers reveal weaknesses that the raw score does not show.'},
    practiceSet:{title:'Bluebook-to-practice handoff',intro:'Turn the official checkpoint into a focused next cycle.',questions:[
        {id:'review-bluebook-timing',difficulty:'Planning',skill:'Checkpoint use',title:'Schedule a full test',stem:'When is a full Bluebook test most useful?',choices:['Every day','After a meaningful study block as a checkpoint','Only after the real SAT','Instead of reviewing errors'],answer:1,explanation:{steps:[{text:'A spaced checkpoint measures whether study changes transfer to full conditions.'}],trap:'Daily testing leaves too little repair time.',takeaway:'Alternate measurement with intervention.'}},
        {id:'review-bluebook-tools',difficulty:'Planning',skill:'Test conditions',title:'Practice the interface',stem:'Which is a good reason to use Bluebook practice?',choices:['To memorize live questions','To learn calculator, review, timer, and navigation behavior','To avoid timing','To use prohibited outside tools'],answer:1,explanation:{steps:[{text:'Interface fluency reduces test-day friction.'}],trap:'Practice must follow test policies.',takeaway:'Rehearse the actual tool environment.'}},
        {id:'review-bluebook-explain',difficulty:'Review',skill:'Answer analysis',title:'Read all rationales',stem:'Why inspect incorrect choices after a practice test?',choices:['To memorize letters','To identify the error paths each distractor represents','To change the official score','To avoid retakes'],answer:1,explanation:{steps:[{text:'Distractors often encode common misconceptions or setup errors.'}],trap:'Review is about reasoning, not answer-letter memory.',takeaway:'Explain why each option works or fails.'}},
        {id:'review-bluebook-filter',difficulty:'Planning',skill:'Targeted practice',title:'Use official filters',stem:'A report shows weakness in right-triangle trig. What Question Bank filter is most precise?',choices:['All Reading and Writing','Math → Geometry and Trigonometry → Right triangles and trigonometry','All Math easy questions','Circles only'],answer:1,explanation:{steps:[{text:'Filter by section, domain, and exact skill.'}],trap:'Broad sets dilute the evidence-based target.',takeaway:'Turn reports into skill-specific official practice.'}},
    ]},
};

export const MISTAKE_REVIEW_LESSONS = [
    diagnoseEveryMiss,
    retakeMissedQuestions,
    buildAWeeklyWeaknessMap,
    bluebookPracticeTestHandoff,
];
