const parallelAndPerpendicularLines = {
    slug: 'parallel-and-perpendicular-lines',
    moduleId: 'linear-functions-systems',
    title: 'Parallel and Perpendicular Lines',
    eyebrow: 'Algebra',
    minutes: '32 min',
    summary: 'Line relationships are slope relationships, but standard-form, vector, bisector, and distance shortcuts make the hardest versions faster.',
    goals: [
        'Identify and construct parallel and perpendicular lines in any equation form.',
        'Handle horizontal and vertical lines without using a nonexistent reciprocal.',
        'Solve parameter problems with slope or coefficient relationships.',
        'Use vector tests, perpendicular bisectors, and parallel-line distance formulas.',
    ],
    facts: [
        {label: 'Parallel', value: 'same slope', note: 'distinct parallel lines have different intercepts'},
        {label: 'Perpendicular', value: 'negative reciprocals', note: 'for nonzero finite slopes, their product is -1'},
        {label: 'Special pair', value: 'horizontal + vertical', note: 'these lines are perpendicular'},
        {label: 'Standard form', value: 'coefficients reveal angle', note: 'often no slope conversion is needed'},
    ],
    sections: [
        {
            heading: 'Big idea 1: parallel lines share direction',
            paragraphs: [
                'Parallel lines have the same rate of change. If their intercepts differ, they never meet. If both slope and intercept match, they are not two distinct parallel lines—they are the same line.',
                'When equations are in standard form, proportional x- and y-coefficients signal equal slopes. Constants determine whether the equations are identical or distinct.',
            ],
        },
        {
            heading: 'Big idea 2: perpendicular slopes rotate direction by 90 degrees',
            paragraphs: [
                'For nonvertical, nonhorizontal lines, perpendicular slopes are negative reciprocals. Flip the fraction and change its sign: 3/4 becomes -4/3, while -2 becomes 1/2.',
                'A horizontal line has slope zero, whose negative reciprocal is not defined. Its perpendicular partner is vertical. Treat this as a special geometric case instead of trying to divide by zero.',
            ],
        },
        {
            heading: 'Big idea 3: use a known point after finding the required slope',
            paragraphs: [
                'A parallel or perpendicular condition gives a slope, not a complete equation. A point on the new line determines its position. Point-slope form is the safest bridge between those two pieces of information.',
                'Do not reuse the original line’s intercept unless the problem explicitly says the new line passes through that same axis point.',
            ],
        },
        {
            heading: 'Big idea 4: vectors unlock advanced shortcuts',
            paragraphs: [
                'For Ax + By = C, the vector (A, B) is perpendicular to the line. Two lines are perpendicular when their normal vectors have dot product zero, and parallel when their coefficient pairs are proportional.',
                'Once parallel equations use matching A and B, their separation is the difference in constants divided by the length of the normal vector. This avoids constructing a perpendicular segment manually.',
            ],
        },
    ],
    formulas: [
        {
            label: 'Parallel slopes',
            math: 'm_1=m_2',
            note: 'For distinct lines, the intercepts must differ.',
            meaning: 'Both lines change by the same vertical amount for each horizontal unit.',
            useWhen: 'Equations are in slope-intercept form or slopes are easy to extract.',
        },
        {
            label: 'Perpendicular slopes',
            math: 'm_1m_2=-1\\qquad \\left(m_2=-\\frac{1}{m_1}\\right)',
            note: 'This formula assumes both slopes are finite and nonzero.',
            meaning: 'Negative reciprocal directions meet at a right angle.',
            useWhen: 'Neither line is horizontal nor vertical.',
        },
        {
            label: 'Line through a required point',
            math: 'y-y_1=m(x-x_1)',
            note: 'First determine the parallel or perpendicular slope, then substitute the given point.',
            meaning: 'The new line has the required direction and is anchored at the required location.',
            useWhen: 'A question asks for an equation through a specific point.',
        },
        {
            label: 'Standard-form parallel test',
            math: 'A_1B_2-A_2B_1=0',
            note: 'The coefficient pairs (A₁, B₁) and (A₂, B₂) are proportional.',
            meaning: 'The two normal vectors point in the same or opposite direction.',
            useWhen: 'Both lines are written as Ax + By = C.',
        },
        {
            label: 'Standard-form perpendicular test',
            math: 'A_1A_2+B_1B_2=0',
            note: 'The coefficient-pair dot product is zero.',
            meaning: 'The normal vectors—and therefore the lines after the same 90-degree rotation—are perpendicular.',
            useWhen: 'Standard-form coefficients are cleaner than converting to slope.',
        },
        {
            label: 'Distance between parallel lines',
            math: 'Ax+By=C_1,\\ Ax+By=C_2 \\Rightarrow d=\\frac{|C_2-C_1|}{\\sqrt{A^2+B^2}}',
            note: 'The x- and y-coefficients must match exactly before using the constants.',
            meaning: 'The constant gap is normalized by the length of the line’s normal vector.',
            useWhen: 'A coordinate-geometry question asks for the shortest distance between parallel lines.',
        },
        {
            label: 'Perpendicular bisector recipe',
            math: 'M=\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2}\\right),\\qquad m_{\\perp}=-\\frac{1}{m_{\\text{segment}}}',
            note: 'The perpendicular bisector passes through the segment midpoint.',
            meaning: 'Every point on this line is equally distant from the segment endpoints.',
            useWhen: 'A problem mentions equidistance, a bisector, or the center of a circle through two points.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Construct a parallel line',
            prompt: 'Find the line parallel to y = (3/2)x - 4 that passes through (2, 5).',
            math: 'y-5=\\frac{3}{2}(x-2)',
            steps: [
                'A parallel line keeps slope 3/2.',
                'Use the new point in point-slope form.',
                'Expand: y - 5 = (3/2)x - 3.',
                'Add 5: y = (3/2)x + 2.',
            ],
            insight: 'The slope stays the same, while the given point creates a new intercept.',
            trap: 'Copying the original -4 intercept would reproduce the original line, which does not pass through (2, 5).',
        },
        {
            level: 'Core SAT',
            title: 'Construct a perpendicular line from standard form',
            prompt: 'Find the line through (-1, 4) perpendicular to 2x - 5y = 10.',
            math: 'm_{\\text{original}}=\\frac{2}{5},\\qquad m_{\\perp}=-\\frac{5}{2}',
            steps: [
                'Solve mentally for slope: -5y = -2x + 10, so m = 2/5.',
                'Take the negative reciprocal: -5/2.',
                'Use point-slope form: y - 4 = (-5/2)(x + 1).',
            ],
            insight: 'You can stop in point-slope form unless the answer choices require expansion.',
            trap: 'Changing only the sign gives -2/5, which is not the negative reciprocal.',
        },
        {
            level: 'Core SAT',
            title: 'Handle horizontal and vertical lines',
            prompt: 'Find the line through (3, -2) perpendicular to y = 7.',
            math: 'x=3',
            steps: [
                'The line y = 7 is horizontal.',
                'A line perpendicular to a horizontal line is vertical.',
                'The vertical line through (3, -2) has equation x = 3.',
            ],
            insight: 'A vertical equation uses the point’s x-coordinate and does not contain y.',
            trap: 'There is no finite negative reciprocal of slope zero.',
        },
        {
            level: 'Advanced',
            title: 'Find a parameter that forces parallel lines',
            prompt: 'For what k is (k - 1)x + 3y = 7 parallel to 2x - 6y = 5?',
            math: '-\\frac{k-1}{3}=\\frac{1}{3}',
            steps: [
                'The first slope is -(k - 1)/3.',
                'The second slope is -2/(-6) = 1/3.',
                'Set them equal: -(k - 1)/3 = 1/3.',
                'Then -(k - 1) = 1, so k = 0.',
            ],
            insight: 'The constants 7 and 5 do not affect whether the directions are parallel.',
            trap: 'Compare slopes or proportional coefficient pairs, not unmatched individual coefficients.',
        },
        {
            level: 'Advanced',
            title: 'Use the standard-form dot-product test',
            prompt: 'Classify 3x + 4y = 8 and 4x - 3y = 1.',
            math: '(3)(4)+(4)(-3)=0',
            steps: [
                'Use coefficient pairs (3, 4) and (4, -3).',
                'Their dot product is 12 - 12 = 0.',
                'Therefore the lines are perpendicular.',
                'Slope check: -3/4 and 4/3 multiply to -1.',
            ],
            insight: 'The dot-product test avoids two separate slope conversions.',
            trap: 'A zero coefficient cross-difference would indicate parallel lines; a zero dot product indicates perpendicular lines.',
        },
        {
            level: 'Advanced',
            title: 'Find the distance between parallel lines',
            prompt: 'Find the distance between 3x + 4y = 7 and 3x + 4y = 27.',
            math: 'd=\\frac{|27-7|}{\\sqrt{3^2+4^2}}',
            steps: [
                'The coefficient pairs already match.',
                'The constant difference is 20.',
                'The normal-vector length is √(9 + 16) = 5.',
                'The distance is 20/5 = 4 units.',
            ],
            insight: 'The denominator corrects for how the coefficient scale stretches the equation constants.',
            trap: 'The constant difference 20 is not itself a geometric distance.',
        },
    ],
    strategyCards: [
        {
            title: 'Build a related line',
            items: ['Extract the original slope', 'Keep it for parallel or take the negative reciprocal for perpendicular', 'Anchor the new slope with the given point'],
        },
        {
            title: 'Special and standard forms',
            items: ['Horizontal and vertical lines form a perpendicular pair', 'Proportional standard-form coefficient pairs mean parallel', 'Zero coefficient-pair dot product means perpendicular'],
        },
        {
            title: 'High-score extensions',
            items: ['Use midpoint plus negative-reciprocal slope for a perpendicular bisector', 'Normalize coefficients before a parallel-distance calculation', 'Ignore constants when testing angle relationships'],
        },
    ],
    studyTips: [
        {
            title: 'Say “flip and change the sign” out loud',
            summary: 'The negative-reciprocal step causes most perpendicular-line mistakes.',
            items: [
                'Rewrite an integer slope such as 3 as 3/1 before flipping.',
                'A positive slope becomes negative; a negative slope becomes positive.',
                'Multiply the two final slopes to check that the product is -1.',
            ],
        },
        {
            title: 'Delay slope conversion when standard form is clean',
            summary: 'High-difficulty questions often reward coefficient recognition.',
            items: [
                'For parallel lines, test whether coefficient pairs are proportional.',
                'For perpendicular lines, test whether their coefficient-pair dot product is zero.',
                'Convert to slope only as a verification step.',
            ],
        },
        {
            title: 'Sketch the direction before solving',
            summary: 'A ten-second sketch catches sign and orientation errors.',
            items: [
                'Mark whether the original line rises, falls, is horizontal, or is vertical.',
                'Draw the expected related direction through the given point.',
                'Reject equations whose slopes disagree before doing full substitution.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Choose the right relationship',
        prompt: 'A line has slope -3/5. What slope should a related line use?',
        options: [
            {
                id: 'parallel',
                label: 'Parallel line',
                result: 'Keep slope -3/5.',
                advice: 'Parallel lines share direction; only their position or intercept changes.',
            },
            {
                id: 'perpendicular',
                label: 'Perpendicular line',
                result: 'Use slope 5/3.',
                advice: 'Flip -3/5 to -5/3, then change the sign to get +5/3. The product is -1.',
            },
        ],
    },
    quickCheck: {
        prompt: 'What is the slope of a line perpendicular to 4x + 3y = 12?',
        choices: ['-4/3', '-3/4', '3/4', '4/3'],
        answer: 2,
        explanation: 'The original slope is -4/3. Its negative reciprocal is 3/4, and (-4/3)(3/4) = -1.',
    },
    practiceSet: {
        title: 'Line relationships from foundation to hard Module 2',
        intro: 'The set moves from slope rules to point-slope construction, standard-form parameters, bisectors, and distance.',
        questions: [
            {
                id: 'parallel-slope',
                difficulty: 'Foundation',
                skill: 'Parallel',
                title: 'Keep the direction',
                stem: 'What is the slope of any line parallel to y = -3x + 7?',
                choices: ['-3', '-1/3', '1/3', '3'],
                answer: 0,
                explanation: {
                    steps: ['The given line has slope -3.', 'Parallel lines have the same slope.', 'Therefore the required slope is -3.'],
                    trap: 'Taking a reciprocal is a perpendicular-line move, not a parallel-line move.',
                    takeaway: 'Parallel means equal slopes.',
                },
            },
            {
                id: 'perpendicular-slope',
                difficulty: 'Foundation',
                skill: 'Perpendicular',
                title: 'Take the negative reciprocal',
                stem: 'What is the slope of a line perpendicular to a line with slope 2/5?',
                choices: ['-5/2', '-2/5', '2/5', '5/2'],
                answer: 0,
                explanation: {
                    steps: ['Flip 2/5 to 5/2.', 'Change the sign: -5/2.', 'The product (2/5)(-5/2) is -1.'],
                    trap: 'Changing only the sign gives -2/5, which is not perpendicular.',
                    takeaway: 'Perpendicular finite slopes are negative reciprocals.',
                },
            },
            {
                id: 'parallel-through-point',
                difficulty: 'Core',
                skill: 'Equation building',
                title: 'Use a new point, not the old intercept',
                stem: 'Which line passes through (2, -1) and is parallel to y = 4x + 5?',
                choices: ['y = 4x - 9', 'y = 4x + 5', 'y = -(1/4)x - 1/2', 'y = -4x + 7'],
                answer: 0,
                explanation: {
                    steps: ['Keep slope 4.', 'Use y + 1 = 4(x - 2).', 'Expand: y + 1 = 4x - 8, so y = 4x - 9.'],
                    trap: 'Keeping the old +5 intercept reproduces a line that misses the new point.',
                    takeaway: 'A relationship supplies slope; the given point supplies position.',
                },
            },
            {
                id: 'perpendicular-through-point',
                difficulty: 'Core',
                skill: 'Equation building',
                title: 'Construct after rotating the slope',
                stem: 'Which line passes through (3, 2) and is perpendicular to y = -(1/2)x + 4?',
                choices: ['y = -2x + 8', 'y = -(1/2)x + 7/2', 'y = 2x - 4', 'y = (1/2)x + 1/2'],
                answer: 2,
                explanation: {
                    steps: ['The negative reciprocal of -1/2 is 2.', 'Use y - 2 = 2(x - 3).', 'Expand to y = 2x - 4.'],
                    trap: 'A perpendicular slope changes both sign and reciprocal.',
                    takeaway: 'Find the new slope before using the point.',
                },
            },
            {
                id: 'horizontal-vertical',
                difficulty: 'Core',
                skill: 'Special case',
                title: 'Perpendicular to horizontal',
                stem: 'Which line passes through (-2, 4) and is perpendicular to y = 7?',
                choices: ['x = -2', 'x = 4', 'y = -2', 'y = 4'],
                answer: 0,
                explanation: {
                    steps: ['The given line is horizontal.', 'Its perpendicular is vertical.', 'The vertical line through the point has x = -2.'],
                    trap: 'A vertical line uses the point’s x-coordinate, not y-coordinate.',
                    takeaway: 'Horizontal and vertical lines are perpendicular.',
                },
            },
            {
                id: 'parallel-standard',
                difficulty: 'Core',
                skill: 'Standard form',
                title: 'Recognize proportional coefficients',
                stem: 'How are 3x + 2y = 5 and 6x + 4y = 1 related?',
                choices: ['Parallel distinct lines', 'Perpendicular lines', 'The same line', 'Lines intersecting at (0, 0)'],
                answer: 0,
                explanation: {
                    steps: ['The second variable coefficients are twice the first: (6, 4) = 2(3, 2).', 'But doubling the first constant would give 10, not 1.', 'The lines have equal slopes and different intercepts.'],
                    trap: 'Proportional variable coefficients do not make equations identical unless constants scale too.',
                    takeaway: 'Coefficient proportions determine direction; constants determine position.',
                },
            },
            {
                id: 'parameter-parallel',
                difficulty: 'Advanced',
                skill: 'Parameter',
                title: 'Force matching slopes',
                stem: 'For what value of k is (k - 1)x + 3y = 7 parallel to 2x - 6y = 5?',
                choices: ['-1', '0', '1', '2'],
                answer: 1,
                explanation: {
                    steps: ['The slopes are -(k - 1)/3 and 1/3.', 'Set them equal: -(k - 1)/3 = 1/3.', 'Then k - 1 = -1, so k = 0.'],
                    trap: 'The constants do not enter the slope comparison.',
                    takeaway: 'Set symbolic slopes equal to create parallel lines.',
                },
            },
            {
                id: 'parameter-perpendicular',
                difficulty: 'Advanced',
                skill: 'Dot product',
                title: 'Use coefficient vectors',
                stem: 'For what value of k is kx + 4y = 1 perpendicular to 2x - 3y = 5?',
                choices: ['3', '4', '6', '12'],
                answer: 2,
                explanation: {
                    steps: ['Use normal vectors (k, 4) and (2, -3).', 'Perpendicular lines require zero dot product: 2k - 12 = 0.', 'Thus k = 6.'],
                    trap: 'The equation constants do not affect the angle between lines.',
                    takeaway: 'For standard-form lines, a zero coefficient-pair dot product tests perpendicularity.',
                },
            },
            {
                id: 'parallel-distance',
                difficulty: 'Advanced',
                skill: 'Distance',
                title: 'Normalize the constant gap',
                stem: 'What is the distance between 3x + 4y = 7 and 3x + 4y = 27?',
                choices: ['4', '5', '20', '25'],
                answer: 0,
                explanation: {
                    steps: ['The constant gap is |27 - 7| = 20.', 'The normal length is √(3² + 4²) = 5.', 'Distance = 20/5 = 4.'],
                    trap: 'The difference in constants depends on equation scale and is not directly the distance.',
                    takeaway: 'Divide the constant gap by the normal-vector length.',
                },
            },
            {
                id: 'perpendicular-bisector',
                difficulty: 'Advanced',
                skill: 'Bisector',
                title: 'Combine midpoint and slope',
                stem: 'What is the perpendicular bisector of the segment from (2, 1) to (6, 5)?',
                choices: ['y = x - 1', 'y = -x + 7', 'y = -x + 3', 'y = x + 7'],
                answer: 1,
                explanation: {
                    steps: ['The midpoint is ((2 + 6)/2, (1 + 5)/2) = (4, 3).', 'The segment slope is (5 - 1)/(6 - 2) = 1.', 'The perpendicular slope is -1.', 'Through (4, 3): y - 3 = -(x - 4), so y = -x + 7.'],
                    trap: 'A perpendicular bisector must be both perpendicular and pass through the midpoint.',
                    takeaway: 'Use midpoint for position and negative reciprocal for direction.',
                },
            },
            {
                id: 'standard-through-point',
                difficulty: 'Advanced',
                skill: 'Mixed forms',
                title: 'Move from standard form to point-slope',
                stem: 'Which line passes through (5, -1) and is perpendicular to 2x + 5y = 10?',
                choices: ['y + 1 = (5/2)(x - 5)', 'y + 1 = -(2/5)(x - 5)', 'y - 1 = (2/5)(x + 5)', 'y - 5 = -(5/2)(x + 1)'],
                answer: 0,
                explanation: {
                    steps: ['The original slope is -2/5.', 'Its negative reciprocal is 5/2.', 'Using (5, -1) gives y - (-1) = (5/2)(x - 5).'],
                    trap: 'The point contributes y + 1 and x - 5 in point-slope form.',
                    takeaway: 'Extract slope, rotate it, then anchor with the given point.',
                },
            },
            {
                id: 'scaled-distance',
                difficulty: 'Advanced',
                skill: 'Normalization',
                title: 'Match coefficients before measuring',
                stem: 'What is the distance between x - y = 3 and 2x - 2y = -10?',
                choices: ['2√2', '4', '4√2', '8'],
                answer: 2,
                explanation: {
                    steps: ['Divide the second equation by 2: x - y = -5.', 'Now the constant gap is |3 - (-5)| = 8.', 'The normal length is √(1² + (-1)²) = √2.', 'Distance = 8/√2 = 4√2.'],
                    trap: 'Using constants 3 and -10 before matching coefficient scales gives a meaningless gap.',
                    takeaway: 'Normalize parallel equations to identical A and B before applying the distance formula.',
                },
            },
        ],
    },
};

export default parallelAndPerpendicularLines;
