const quadraticForms = {
    slug: 'standard-factored-and-vertex-form',
    moduleId: 'quadratic-foundations',
    title: 'Standard, Factored, and Vertex Form',
    eyebrow: 'Advanced Math',
    minutes: '34 min',
    summary: 'The same parabola can wear three useful forms. Learn to read the feature each form reveals and convert only when the question demands it.',
    goals: [
        'Recognize standard, factored, and vertex form without expanding.',
        'Read the y-intercept, zeros, vertex, axis of symmetry, and opening direction.',
        'Choose the form that makes an SAT question shortest.',
        'Reconstruct a quadratic from roots, a vertex, or another point.',
    ],
    facts: [
        {label: 'Standard form', math: 'ax^2+bx+c', note: 'reveals the y-intercept immediately'},
        {label: 'Factored form', math: 'a(x-r_1)(x-r_2)', note: 'reveals the zeros immediately'},
        {label: 'Vertex form', math: 'a(x-h)^2+k', note: 'reveals the vertex immediately'},
        {label: 'Shared feature', math: 'a', note: 'controls opening direction and vertical scale in every form'},
    ],
    sections: [
        {
            heading: 'Big idea 1: form is information',
            paragraphs: [
                'Equivalent equations can describe exactly the same parabola while highlighting different features. Expanding everything into standard form is sometimes useful, but it can hide the roots or vertex that the question handed you for free.',
                'Treat the three forms like three camera angles. Before calculating, ask which feature the problem requests and look for the form that already displays it.',
            ],
            math: '\\begin{aligned}f(x)&=ax^2+bx+c\\\\&=a(x-r_1)(x-r_2)\\\\&=a(x-h)^2+k\\end{aligned}',
        },
        {
            heading: 'Big idea 2: the leading coefficient survives every form',
            paragraphs: [
                'A positive leading coefficient makes the parabola open upward, so its vertex is a minimum. A negative leading coefficient makes it open downward, so its vertex is a maximum.',
                'The size of the leading coefficient changes vertical scale. Larger absolute values produce faster vertical change away from the axis; values between negative one and one produce slower change.',
            ],
            math: 'a>0\\Rightarrow\\text{minimum},\\qquad a<0\\Rightarrow\\text{maximum}',
        },
        {
            heading: 'Big idea 3: symmetry connects roots and the vertex',
            paragraphs: [
                'A parabola is symmetric about a vertical line through its vertex. When two real roots exist, the axis of symmetry lies exactly halfway between them.',
                'In standard form, the same axis comes from the coefficient shortcut. These two routes must agree, which creates fast parameter tricks on harder questions.',
            ],
            math: 'h=\\frac{r_1+r_2}{2}=-\\frac{b}{2a}',
        },
        {
            heading: 'Big idea 4: one extra point determines the vertical scale',
            paragraphs: [
                'Knowing two roots determines the factor locations but not the leading coefficient. Likewise, knowing a vertex determines the shift but not the vertical scale. Substitute one additional point to solve for the missing coefficient.',
                'This reconstruction pattern is common in hard questions: write the structurally useful form first, then use the extra point last.',
            ],
            math: '(x_0,y_0)\\Rightarrow y_0=a(x_0-r_1)(x_0-r_2)\\quad\\text{or}\\quad y_0=a(x_0-h)^2+k',
        },
    ],
    formulas: [
        {
            label: 'Standard form',
            math: 'f(x)=ax^2+bx+c,\\qquad a\\ne0',
            note: 'The constant term is the output at zero.',
            meaning: 'The graph crosses the y-axis at the point with vertical coordinate c.',
            useWhen: 'You need the y-intercept, coefficient relationships, or the axis shortcut.',
        },
        {
            label: 'Factored form',
            math: 'f(x)=a(x-r_1)(x-r_2)',
            note: 'Each factor becomes zero at its corresponding root.',
            meaning: 'The x-intercepts are the points with horizontal coordinates r₁ and r₂ when the roots are real.',
            useWhen: 'You need zeros, signs between zeros, or a quadratic built from roots.',
        },
        {
            label: 'Vertex form',
            math: 'f(x)=a(x-h)^2+k',
            note: 'The signs inside and outside the square play different roles.',
            meaning: 'The vertex is at the point with coordinates h and k, and the axis is the vertical line through h.',
            useWhen: 'You need a maximum, minimum, range, axis, or transformation.',
        },
        {
            label: 'Axis of symmetry',
            math: 'x=h=-\\frac{b}{2a}=\\frac{r_1+r_2}{2}',
            note: 'Use the coefficient route in standard form or average the roots in factored form.',
            meaning: 'Inputs equally far from h produce equal outputs.',
            useWhen: 'The problem asks for the vertex input, midpoint of roots, or a paired input with the same output.',
        },
        {
            label: 'Y-intercept in factored form',
            math: 'f(0)=a(0-r_1)(0-r_2)=ar_1r_2',
            note: 'This equals c after the expression is expanded.',
            meaning: 'The product of the roots, scaled by a, controls the starting output.',
            useWhen: 'Roots and the leading coefficient are given but the y-intercept is requested.',
        },
        {
            label: 'Root sum and product',
            math: 'r_1+r_2=-\\frac{b}{a},\\qquad r_1r_2=\\frac{c}{a}',
            note: 'These are Vieta’s relationships for a quadratic.',
            meaning: 'You can extract symmetric information about the roots without solving for either root.',
            useWhen: 'A hard question asks for the sum, product, or midpoint of roots.',
        },
        {
            label: 'Extremum and range',
            math: '\\begin{cases}a>0: & f(x)\\ge k\\\\a<0: & f(x)\\le k\\end{cases}',
            note: 'The vertex output k is the boundary of the range.',
            meaning: 'An upward-opening parabola never falls below k; a downward-opening one never rises above k.',
            useWhen: 'A question asks for a maximum, minimum, possible output, or inequality range.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Read standard form without graphing',
            prompt: 'Identify the opening direction and y-intercept of the quadratic shown.',
            math: 'f(x)=2x^2-7x-9',
            steps: [
                {text: 'The leading coefficient is positive.', math: 'a=2>0\\Rightarrow\\text{the parabola opens upward}'},
                {text: 'Evaluate at zero or read the constant term.', math: 'f(0)=-9'},
                {text: 'State the intercept as a point.', math: '(0,-9)'},
            ],
            insight: 'Standard form gives the y-intercept before any factoring or graphing.',
            trap: 'The y-intercept is a point, while negative nine alone is its y-coordinate.',
        },
        {
            level: 'Foundation',
            title: 'Read roots from factors',
            prompt: 'Find the zeros and axis of symmetry.',
            math: 'g(x)=-3(x+4)(x-2)',
            steps: [
                {text: 'Set each factor equal to zero.', math: 'x+4=0\\Rightarrow x=-4,\\qquad x-2=0\\Rightarrow x=2'},
                {text: 'Average the two roots.', math: 'x=\\frac{-4+2}{2}=-1'},
                {text: 'The negative leading coefficient tells the opening direction.', math: 'a=-3<0\\Rightarrow\\text{opens downward}'},
            ],
            insight: 'The sign inside a factor reverses when you solve for the root.',
            trap: 'The factor containing x plus four gives a root of negative four, not positive four.',
        },
        {
            level: 'Core SAT',
            title: 'Read a vertex and range',
            prompt: 'Find the vertex, axis, and range of the quadratic shown.',
            math: 'p(x)=4(x-3)^2-7',
            steps: [
                {text: 'Match the expression to vertex form.', math: 'h=3,\\qquad k=-7'},
                {text: 'The leading coefficient is positive, so the vertex is a minimum.', math: '4>0'},
                {text: 'Write the requested features.', math: '\\text{vertex }(3,-7),\\quad\\text{axis }x=3,\\quad p(x)\\ge-7'},
            ],
            insight: 'The squared term can never be negative, so the smallest output occurs when it equals zero.',
            trap: 'The horizontal coordinate is positive three because the form uses x minus h.',
        },
        {
            level: 'Core SAT',
            title: 'Choose a form instead of expanding',
            prompt: 'Find the y-intercept directly from the factored equation.',
            math: 'q(x)=2(x-5)(x+1)',
            steps: [
                {text: 'A y-intercept occurs at zero input.', math: 'q(0)=2(0-5)(0+1)'},
                {text: 'Multiply the three values.', math: 'q(0)=2(-5)(1)=-10'},
                {text: 'State the point.', math: '(0,-10)'},
            ],
            insight: 'Substitution is shorter and safer than expanding the entire expression.',
            trap: 'Adding the roots does not give the y-intercept; the scaled product does.',
        },
        {
            level: 'Advanced',
            title: 'Build a quadratic from roots and a point',
            prompt: 'A quadratic has zeros negative two and five and passes through the point with coordinates one and negative twenty-four. Find its equation in factored form.',
            math: 'f(x)=a(x+2)(x-5)',
            steps: [
                {text: 'Use the roots to create the factors.', math: 'f(x)=a(x+2)(x-5)'},
                {text: 'Substitute the extra point.', math: '-24=a(1+2)(1-5)=-12a'},
                {text: 'Solve for the scale and write the model.', math: 'a=2\\Rightarrow f(x)=2(x+2)(x-5)'},
            ],
            insight: 'Roots determine factor locations; the extra point determines vertical scale.',
            trap: 'Assuming the leading coefficient is one ignores infinitely many vertically scaled parabolas with the same roots.',
        },
        {
            level: 'Advanced',
            title: 'Use symmetry to avoid solving',
            prompt: 'A quadratic has one root equal to seven and axis of symmetry equal to two. Find the other root.',
            math: '\\frac{7+r}{2}=2',
            steps: [
                {text: 'The axis is the midpoint of the roots.', math: '\\frac{7+r}{2}=2'},
                {text: 'Multiply by two and isolate the unknown root.', math: '7+r=4\\Rightarrow r=-3'},
                {text: 'Check the midpoint.', math: '\\frac{7+(-3)}{2}=2'},
            ],
            insight: 'A root-pair symmetry question may require no factoring or quadratic formula.',
            trap: 'The distance from seven to two is five, so the partner must be five units on the other side of two.',
        },
    ],
    strategyCards: [
        {
            title: 'Match the request to the form',
            items: ['Y-intercept or coefficient comparison: standard form', 'Zeros or sign intervals: factored form', 'Maximum, minimum, axis, or range: vertex form'],
        },
        {
            title: 'Convert only as far as needed',
            items: ['Substitute zero instead of expanding just to find the y-intercept', 'Average roots instead of expanding to find the axis', 'Use one extra point to recover the missing leading coefficient'],
        },
        {
            title: 'Check every feature',
            items: ['The sign inside a factor reverses at the root', 'The sign inside vertex form reverses at the vertex input', 'The same leading coefficient must appear after every correct conversion'],
        },
    ],
    studyTips: [
        {
            title: 'Run a five-second form scan',
            summary: 'Before touching the algebra, name the visible feature.',
            items: [
                'Standard form: circle the constant term.',
                'Factored form: set each factor equal to zero mentally.',
                'Vertex form: read the opposite inside sign and the same outside sign.',
            ],
        },
        {
            title: 'Sketch only the structural points',
            summary: 'A full graph is rarely necessary for a form-reading question.',
            items: [
                'Plot roots if factored form is given.',
                'Plot the vertex and axis if vertex form is given.',
                'Use the sign of the leading coefficient to connect the shape.',
            ],
        },
        {
            title: 'Train the reconstruction template',
            summary: 'Hard SAT questions often hide one coefficient behind roots or a vertex.',
            items: [
                'Write factors from roots or a square from the vertex.',
                'Keep the leading coefficient as an unknown.',
                'Substitute the extra point only after the structure is correct.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Pick the shortest representation',
        prompt: 'You need the maximum value of a downward-opening quadratic. Which form would you request?',
        options: [
            {
                id: 'vertex',
                label: 'Vertex form',
                result: 'Best choice: the maximum output is visible as k.',
                advice: 'In a downward-opening model, the vertex output is the greatest possible value.',
            },
            {
                id: 'standard',
                label: 'Standard form',
                result: 'Usable, but it requires an extra calculation.',
                advice: 'You would first calculate the axis input, then evaluate the function there.',
            },
            {
                id: 'factored',
                label: 'Factored form',
                result: 'Useful only if you exploit symmetry.',
                advice: 'Average the roots to find the vertex input, then substitute it. Vertex form is more direct.',
            },
        ],
    },
    quickCheck: {
        prompt: 'Which feature can be read immediately from the equation?',
        math: 'f(x)=-2(x+6)^2+11',
        choices: ['(-6,11)', '(6,11)', '(-6,-11)', '(6,-11)'],
        choiceMath: true,
        answer: 0,
        explanation: 'Vertex form uses the pattern x minus h. Here x plus six equals x minus negative six, while the outside constant stays positive eleven.',
    },
    practiceSet: {
        title: 'Quadratic forms from foundation to hard Module 2',
        intro: 'Choose structure before computation. Later questions combine forms, symmetry, parameters, and reconstruction.',
        questions: [
            {
                id: 'standard-intercept',
                difficulty: 'Foundation',
                skill: 'Standard form',
                title: 'Read the y-intercept',
                stem: 'What is the y-coordinate of the y-intercept?',
                math: 'f(x)=3x^2-8x+5',
                choices: ['-8', '3', '5', '8'],
                choiceMath: true,
                answer: 2,
                explanation: {
                    steps: [
                        {text: 'Set the input equal to zero.', math: 'f(0)=3(0)^2-8(0)+5=5'},
                    ],
                    trap: 'The linear coefficient is not the y-intercept.',
                    takeaway: 'In standard form, the constant term equals the output at zero.',
                },
            },
            {
                id: 'factored-roots',
                difficulty: 'Foundation',
                skill: 'Factored form',
                title: 'Reverse the factor signs',
                stem: 'What are the zeros?',
                math: 'g(x)=(x-4)(x+9)',
                choices: ['-9, 4', '-4, 9', '4, 9', '-9, -4'],
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'Set each factor equal to zero.', math: 'x-4=0\\Rightarrow x=4,\\qquad x+9=0\\Rightarrow x=-9'},
                    ],
                    trap: 'The signs printed inside the factors are not the root signs.',
                    takeaway: 'A factor x minus r has root r.',
                },
            },
            {
                id: 'vertex-read',
                difficulty: 'Foundation',
                skill: 'Vertex form',
                title: 'Read the ordered pair',
                stem: 'What is the vertex?',
                math: 'p(x)=5(x+2)^2-3',
                choices: ['(-2,-3)', '(2,-3)', '(-2,3)', '(2,3)'],
                choiceMath: true,
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'Rewrite the inside mentally.', math: 'x+2=x-(-2)'},
                        {text: 'Read the vertex.', math: '(h,k)=(-2,-3)'},
                    ],
                    trap: 'Only the sign inside the square reverses.',
                    takeaway: 'Vertex form is a times the square of x minus h, plus k.',
                },
            },
            {
                id: 'axis-from-roots',
                difficulty: 'Core',
                skill: 'Symmetry',
                title: 'Average the roots',
                stem: 'What is the axis of symmetry?',
                math: 'f(x)=2(x-7)(x+1)',
                choices: ['x=-4', 'x=-3', 'x=3', 'x=4'],
                answer: 2,
                explanation: {
                    steps: [
                        {text: 'Read the roots.', math: 'r_1=7,\\qquad r_2=-1'},
                        {text: 'Average them.', math: 'x=\\frac{7+(-1)}{2}=3'},
                    ],
                    trap: 'Averaging the printed constants negative seven and one gives the wrong sign.',
                    takeaway: 'The axis is halfway between the actual roots.',
                },
            },
            {
                id: 'range-from-vertex',
                difficulty: 'Core',
                skill: 'Range',
                title: 'Use the opening direction',
                stem: 'Which inequality describes every possible output?',
                math: 'q(x)=-3(x-5)^2+8',
                choices: ['q(x)\\ge 8', 'q(x)\\le 8', 'q(x)\\ge 5', 'q(x)\\le 5'],
                choiceMath: true,
                answer: 1,
                explanation: {
                    steps: [
                        {text: 'The squared term is nonnegative.', math: '(x-5)^2\\ge0'},
                        {text: 'Multiplying by negative three makes that contribution nonpositive.', math: '-3(x-5)^2\\le0'},
                        {text: 'Therefore the vertex output is a maximum.', math: 'q(x)\\le8'},
                    ],
                    trap: 'The vertex input five is not the maximum output.',
                    takeaway: 'A negative leading coefficient makes k the upper boundary of the range.',
                },
            },
            {
                id: 'factored-y-intercept',
                difficulty: 'Core',
                skill: 'Substitution',
                title: 'Find an intercept without expanding',
                stem: 'What is the y-coordinate of the y-intercept?',
                math: 'f(x)=-2(x-3)(x+4)',
                choices: ['-24', '-8', '8', '24'],
                choiceMath: true,
                answer: 3,
                explanation: {
                    steps: [
                        {text: 'Substitute zero.', math: 'f(0)=-2(-3)(4)=24'},
                    ],
                    trap: 'The product of the roots is negative twelve, but multiplying by the leading coefficient changes the result.',
                    takeaway: 'At zero input, factored form gives the scaled product of the roots.',
                },
            },
            {
                id: 'paired-input',
                difficulty: 'Core',
                skill: 'Symmetry',
                title: 'Find an equal-output input',
                stem: 'For the quadratic shown, one input with output fifty-three is two. What is the other input with output fifty-three?',
                math: 'f(x)=3(x-6)^2+5',
                choices: ['4', '6', '8', '10'],
                choiceMath: true,
                answer: 3,
                explanation: {
                    steps: [
                        {text: 'The axis is the vertical line through six.', math: 'x=6'},
                        {text: 'The input two is four units left of the axis.', math: '6-2=4'},
                        {text: 'Move four units right of the axis.', math: '6+4=10'},
                    ],
                    trap: 'Reflect the input across the axis, not across zero.',
                    takeaway: 'Inputs equally far from the axis have equal outputs.',
                },
            },
            {
                id: 'root-sum',
                difficulty: 'Advanced',
                skill: 'Vieta shortcut',
                title: 'Find a root sum without solving',
                stem: 'If the zeros are r and s, what is their sum?',
                math: '4x^2-12x-7=0',
                choices: ['-3', '3', '-7/4', '7/4'],
                choiceMath: true,
                answer: 1,
                explanation: {
                    steps: [
                        {text: 'Use the root-sum relationship.', math: 'r+s=-\\frac{b}{a}=-\\frac{-12}{4}=3'},
                    ],
                    trap: 'Forgetting the negative sign produces negative three.',
                    takeaway: 'The sum of quadratic roots is negative b divided by a.',
                },
            },
            {
                id: 'reconstruct-roots-point',
                difficulty: 'Advanced',
                skill: 'Reconstruction',
                title: 'Recover the leading coefficient',
                stem: 'A quadratic has zeros negative one and four and passes through the point with coordinates two and negative eighteen. Which equation represents it?',
                choices: ['3(x+1)(x-4)', '-3(x+1)(x-4)', '3(x-1)(x+4)', '-3(x-1)(x+4)'],
                choiceMath: true,
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'Build factors from the roots.', math: 'f(x)=a(x+1)(x-4)'},
                        {text: 'Substitute the extra point.', math: '-18=a(3)(-2)=-6a'},
                        {text: 'Solve for the scale.', math: 'a=3'},
                    ],
                    trap: 'The factor signs reverse the roots, but the leading coefficient keeps its solved sign.',
                    takeaway: 'Roots give structure; one point determines scale.',
                },
            },
            {
                id: 'reconstruct-vertex-point',
                difficulty: 'Advanced',
                skill: 'Reconstruction',
                title: 'Build from a vertex',
                stem: 'A parabola has vertex negative two, five and passes through zero, negative three. What is its leading coefficient?',
                math: 'f(x)=a(x+2)^2+5',
                choices: ['-2', '-1/2', '1/2', '2'],
                choiceMath: true,
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'Substitute the point with zero input and negative three output.', math: '-3=a(0+2)^2+5'},
                        {text: 'Solve.', math: '-8=4a\\Rightarrow a=-2'},
                    ],
                    trap: 'The vertical change is negative eight, not positive eight.',
                    takeaway: 'Vertex form plus one point uniquely determines a quadratic.',
                },
            },
            {
                id: 'parameter-axis',
                difficulty: 'Advanced',
                skill: 'Parameters',
                title: 'Use the coefficient-axis shortcut',
                stem: 'The axis of symmetry is the vertical line with horizontal coordinate four. What is p?',
                math: 'f(x)=2x^2+px-9',
                choices: ['-16', '-8', '8', '16'],
                choiceMath: true,
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'Use the standard-form axis.', math: '-\\frac{p}{2(2)}=4'},
                        {text: 'Solve for the parameter.', math: '-p=16\\Rightarrow p=-16'},
                    ],
                    trap: 'The denominator is two times the leading coefficient, not just the leading coefficient.',
                    takeaway: 'A known axis creates a direct coefficient equation.',
                },
            },
            {
                id: 'same-roots-scale',
                difficulty: 'Advanced',
                skill: 'Structure',
                title: 'Compare quadratics with the same zeros',
                stem: 'The two functions have the same zeros. If the y-intercept of the first function is twelve, what is the y-intercept of the second?',
                math: 'f(x)=a(x-2)(x+3),\\qquad g(x)=-4a(x-2)(x+3)',
                choices: ['-48', '-16', '16', '48'],
                choiceMath: true,
                answer: 0,
                explanation: {
                    steps: [
                        {text: 'The second function is a constant multiple of the first.', math: 'g(x)=-4f(x)'},
                        {text: 'Apply the same scale at zero input.', math: 'g(0)=-4f(0)=-4(12)=-48'},
                    ],
                    trap: 'Shared zeros do not imply shared y-intercepts; vertical scaling preserves roots but changes other outputs.',
                    takeaway: 'Multiplying a function by a constant multiplies every output by that constant.',
                },
            },
        ],
    },
};

export default quadraticForms;
