const slopeAsRateOfChange = {
    slug: 'slope-as-rate-of-change',
    moduleId: 'linear-functions-systems',
    title: 'Slope as Rate of Change',
    eyebrow: 'Algebra',
    minutes: '30 min',
    summary: 'Slope is not just rise over run. It is a signed rate with units that connects equations, tables, graphs, and real situations.',
    goals: [
        'Calculate slope accurately from points, tables, equations, and contexts.',
        'Interpret the sign, size, and units of a rate of change.',
        'Use point-slope and standard-form shortcuts on harder SAT questions.',
        'Find average rate of change even when a function is not linear.',
    ],
    facts: [
        {label: 'Core ratio', value: 'change in y / change in x', note: 'the numerator and denominator must use the same point order'},
        {label: 'Units', value: 'y-units per x-unit', note: 'dollars per hour, feet per second, or points per game'},
        {label: 'Direction', value: 'sign of m', note: 'positive rises, negative falls, zero stays level'},
        {label: 'Linear test', value: 'constant slope', note: 'equal changes in x produce equal changes in y'},
    ],
    sections: [
        {
            heading: 'Big idea 1: slope compares two matching changes',
            paragraphs: [
                'Slope tells how much y changes when x increases by one unit. Between two points, subtract the y-values in one order and the x-values in that same order. Reversing both orders gives the same slope; reversing only one creates the wrong sign.',
                'The phrase rise over run is useful on a graph, but change in output over change in input works everywhere. It applies to tables, equations, and real-world models even when no graph is shown.',
            ],
        },
        {
            heading: 'Big idea 2: the units carry the meaning',
            paragraphs: [
                'If y is measured in dollars and x in hours, then slope is measured in dollars per hour. A slope of -6 means the amount decreases by 6 dollars for every additional hour; it does not merely mean the line points down.',
                'The sign describes direction, while the absolute value describes speed of change. A slope of -8 changes faster than a slope of -2 even though -8 is numerically smaller.',
            ],
        },
        {
            heading: 'Big idea 3: every linear representation hides the same rate',
            paragraphs: [
                'In y = mx + b, the coefficient m is already the slope. In a table, divide a y-change by its matching x-change. In standard form Ax + By = C, the slope is -A/B as long as B is not zero.',
                'A linear function has the same slope between every pair of distinct points. This lets you use far-apart table entries when they make the arithmetic cleaner, and it lets you verify a model with a second pair of points.',
            ],
        },
        {
            heading: 'Big idea 4: average rate is a secant slope',
            paragraphs: [
                'For a nonlinear function, the instantaneous rate may change, but the SAT can still ask for the average rate between two inputs. Compute the two outputs, subtract them, and divide by the change in input.',
                'Do not average the two output values or the two individual rates. Average rate of change is the slope of the line joining the two endpoint points.',
            ],
        },
    ],
    formulas: [
        {
            label: 'Slope from two points',
            math: 'm=\\frac{\\Delta y}{\\Delta x}=\\frac{y_2-y_1}{x_2-x_1},\\quad x_2\\ne x_1',
            note: 'Subtract the coordinates vertically in matching order.',
            meaning: 'For every 1-unit increase in x, a linear model changes by m units in y.',
            useWhen: 'You are given two points, two table rows, or two states of a real situation.',
        },
        {
            label: 'Slope-intercept form',
            math: 'y=mx+b',
            note: 'The coefficient of x is the slope; b is the y-intercept.',
            meaning: 'Each extra x adds another copy of m to the output.',
            useWhen: 'The equation is already solved for y or can be rearranged quickly.',
        },
        {
            label: 'Point-slope form',
            math: 'y-y_1=m(x-x_1)',
            note: 'This builds a line directly from one point and a slope.',
            meaning: 'The change from the known point follows the constant rate m.',
            useWhen: 'A problem gives one point and a slope, especially when the intercept would be messy.',
        },
        {
            label: 'Standard-form shortcut',
            math: 'Ax+By=C \\Rightarrow m=-\\frac{A}{B},\\quad B\\ne0',
            note: 'The negative ratio of the x- and y-coefficients is the slope.',
            meaning: 'Rearranging gives y = -(A/B)x + C/B.',
            useWhen: 'Only the slope is requested and solving fully for y would waste time.',
        },
        {
            label: 'Average rate of change',
            math: '\\frac{f(b)-f(a)}{b-a}',
            note: 'Evaluate the function at both endpoints before dividing.',
            meaning: 'This is the slope of the secant line through (a, f(a)) and (b, f(b)).',
            useWhen: 'The question names an interval or the function is nonlinear.',
        },
        {
            label: 'Horizontal and vertical cases',
            math: 'y=c\\Rightarrow m=0,\\qquad x=c\\Rightarrow m\\text{ is undefined}',
            note: 'A vertical line has zero run, so the slope denominator would be zero.',
            meaning: 'Horizontal outputs do not change; vertical lines are not functions of x.',
            useWhen: 'The two points share a y-coordinate or an x-coordinate.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Find slope from two points',
            prompt: 'Find the slope of the line through (2, 5) and (6, 13).',
            math: 'm=\\frac{13-5}{6-2}',
            steps: [
                'Subtract the y-values: 13 - 5 = 8.',
                'Subtract the matching x-values in the same order: 6 - 2 = 4.',
                'Divide: m = 8/4 = 2.',
            ],
            insight: 'Starting from either point gives 2 because reversing both differences changes two signs, which cancel.',
            trap: 'Using (13 - 5)/(2 - 6) reverses only the denominator and incorrectly gives -2.',
        },
        {
            level: 'Core SAT',
            title: 'Read a rate from uneven table intervals',
            prompt: 'A table contains (2019, 48) and (2022, 60), where the output is measured in thousands of subscribers. Find and interpret the rate.',
            math: 'm=\\frac{60-48}{2022-2019}=4',
            steps: [
                'The output increased by 12 thousand subscribers.',
                'The input increased by 3 years.',
                'The rate is 12/3 = 4 thousand subscribers per year.',
            ],
            insight: 'The raw increase is 12, but slope is the increase per one year, so the answer is 4.',
            trap: 'Reporting 12 thousand subscribers ignores that the table entries are three years apart.',
        },
        {
            level: 'Core SAT',
            title: 'Extract slope from standard form',
            prompt: 'Find the slope of 6x + 4y = 20 without graphing.',
            math: 'm=-\\frac{6}{4}=-\\frac{3}{2}',
            steps: [
                'Identify A = 6 and B = 4 in Ax + By = C.',
                'Use m = -A/B to get m = -6/4.',
                'Reduce the fraction: m = -3/2.',
            ],
            insight: 'The constant 20 affects where the line sits, but it does not affect the slope.',
            trap: 'The slope is not A/B. Moving Ax across the equals sign creates the negative.',
        },
        {
            level: 'Applied',
            title: 'Interpret a negative rate with units',
            prompt: 'The temperature T, in degrees Fahrenheit, of a cooling object after t minutes is T(t) = 86 - 1.7t. Explain the slope and find T(8).',
            math: 'T(8)=86-1.7(8)=72.4',
            steps: [
                'The coefficient of t is -1.7, so the temperature decreases.',
                'Its units are degrees Fahrenheit per minute.',
                'After 8 minutes, substitute t = 8 to get 72.4 degrees Fahrenheit.',
            ],
            insight: 'A complete interpretation includes direction, amount, output unit, and input unit.',
            trap: 'Saying the temperature is -1.7 degrees confuses a rate with an actual temperature.',
        },
        {
            level: 'Advanced',
            title: 'Recover a missing coordinate',
            prompt: 'The line through (k, 4) and (5, 19) has slope 3. Find k.',
            math: '\\frac{19-4}{5-k}=3',
            steps: [
                'Substitute into the slope formula: 15/(5 - k) = 3.',
                'Multiply by 5 - k: 15 = 15 - 3k.',
                'Subtract 15: 0 = -3k, so k = 0.',
                'Check: the points (0, 4) and (5, 19) have slope 15/5 = 3.',
            ],
            insight: 'When a coordinate is unknown, the slope formula becomes an equation rather than a final calculation.',
            trap: 'Do not replace 5 - k with k - 5 unless you also reverse the numerator order.',
        },
        {
            level: 'Advanced',
            title: 'Average rate for a nonlinear function',
            prompt: 'For f(x) = x² - 3x, find the average rate of change from x = 1 to x = 5.',
            math: '\\frac{f(5)-f(1)}{5-1}',
            steps: [
                'Evaluate the endpoints: f(5) = 25 - 15 = 10 and f(1) = 1 - 3 = -2.',
                'Find the output change: 10 - (-2) = 12.',
                'Find the input change: 5 - 1 = 4.',
                'Divide: the average rate of change is 12/4 = 3.',
            ],
            insight: 'The function is not a line, but the secant line joining the endpoint points has slope 3.',
            trap: 'Averaging f(1) and f(5) gives an average output, not an average rate.',
        },
    ],
    strategyCards: [
        {
            title: 'Choose the fastest representation',
            items: ['Two points or table rows: use change in y over change in x', 'Equation solved for y: read the x-coefficient', 'Standard form: use -A/B if only slope is needed'],
        },
        {
            title: 'Write a complete interpretation',
            items: ['State whether the output increases or decreases', 'State how much it changes', 'Attach output-units per input-unit'],
        },
        {
            title: 'Advanced shortcuts',
            items: ['Use far-apart table points to avoid fractions', 'Treat a missing coordinate as an equation in the slope formula', 'For average rate, evaluate endpoints before subtracting'],
        },
    ],
    studyTips: [
        {
            title: 'Use the sign-and-units scan',
            summary: 'Before doing arithmetic, predict what the answer should look like.',
            items: [
                'Trace the points left to right: rising predicts positive slope; falling predicts negative slope.',
                'Write the expected units beside the formula before substituting.',
                'If the computed sign or units disagree with the story, audit the subtraction order.',
            ],
        },
        {
            title: 'Practice representation switching',
            summary: 'Hard SAT questions often hide an easy slope inside an unfamiliar form.',
            items: [
                'Take one line and express it as two points, a table, y = mx + b, and Ax + By = C.',
                'Confirm that every representation gives the same slope.',
                'Time yourself identifying the slope without fully rewriting the equation.',
            ],
        },
        {
            title: 'Build an error log for slope',
            summary: 'Most misses come from a small number of repeatable habits.',
            items: [
                'Label each miss as order, sign, units, zero denominator, or wrong representation.',
                'Redo the question with the other point order to verify the result.',
                'For context problems, require a sentence with both units before marking yourself correct.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Choose a point pair',
        prompt: 'A linear table contains (1, 7), (3, 13), and (8, 28). Which pair should you use?',
        options: [
            {
                id: 'adjacent',
                label: '(1, 7) and (3, 13)',
                result: 'This gives slope 3.',
                advice: 'Compute (13 - 7)/(3 - 1) = 6/2 = 3. Adjacent points work, but they are not required.',
            },
            {
                id: 'far',
                label: '(1, 7) and (8, 28)',
                result: 'This also gives slope 3.',
                advice: 'Compute (28 - 7)/(8 - 1) = 21/7 = 3. For a linear table, choose the pair with the cleanest arithmetic.',
            },
        ],
    },
    quickCheck: {
        prompt: 'What is the slope of the line 5x - 2y = 14?',
        choices: ['-5/2', '-2/5', '2/5', '5/2'],
        answer: 3,
        explanation: 'Use the shortcut m = -A/B with A = 5 and B = -2: m = -5/(-2) = 5/2. Equivalently, -2y = -5x + 14 gives y = (5/2)x - 7.',
    },
    practiceSet: {
        title: 'Slope from foundation to hard Module 2',
        intro: 'The set begins with direct calculations, then moves into interpretation, nonlinear average rate, and parameter questions.',
        questions: [
            {
                id: 'basic-positive',
                difficulty: 'Foundation',
                skill: 'Two points',
                title: 'A clean positive slope',
                stem: 'What is the slope of the line through (1, 2) and (5, 10)?',
                math: 'm=\\frac{10-2}{5-1}',
                choices: ['1/2', '2', '4', '8'],
                answer: 1,
                explanation: {
                    steps: ['The y-change is 10 - 2 = 8.', 'The x-change is 5 - 1 = 4.', 'Divide: m = 8/4 = 2.'],
                    trap: 'Run over rise gives 4/8 = 1/2, the reciprocal of the slope.',
                    takeaway: 'Slope is change in y divided by change in x.',
                },
            },
            {
                id: 'negative-points',
                difficulty: 'Foundation',
                skill: 'Signs',
                title: 'A falling line',
                stem: 'What is the slope of the line through (-2, 7) and (4, -5)?',
                math: 'm=\\frac{-5-7}{4-(-2)}',
                choices: ['-3', '-2', '2', '3'],
                answer: 1,
                explanation: {
                    steps: ['The y-change is -12.', 'The x-change is 6.', 'The slope is -12/6 = -2.'],
                    trap: 'Subtracting a negative x-coordinate means 4 - (-2) = 6, not 2.',
                    takeaway: 'Use parentheses when substituting negative coordinates.',
                },
            },
            {
                id: 'reverse-order',
                difficulty: 'Core',
                skill: 'Point order',
                title: 'Reverse both or neither',
                stem: 'What is the slope of the line through (3, -1) and (-1, 7)?',
                choices: ['-2', '-1/2', '1/2', '2'],
                answer: 0,
                explanation: {
                    steps: ['Using the second point minus the first gives (7 - (-1))/(-1 - 3).', 'That is 8/(-4) = -2.'],
                    trap: 'Mixing numerator order with denominator order produces the wrong positive sign.',
                    takeaway: 'Choose a point order once and use it for both coordinate differences.',
                },
            },
            {
                id: 'uneven-table',
                difficulty: 'Core',
                skill: 'Table',
                title: 'Uneven input intervals',
                stem: 'A linear table contains the points (2, 9), (5, 18), and (11, 36). What is its rate of change?',
                choices: ['3', '6', '9', '27'],
                answer: 0,
                explanation: {
                    steps: ['Use the first two points: (18 - 9)/(5 - 2) = 9/3.', 'The rate of change is 3.'],
                    trap: 'The y-change 9 is not the rate because x changed by 3.',
                    takeaway: 'Table spacing does not need to be one; divide by the actual x-change.',
                },
            },
            {
                id: 'standard-form',
                difficulty: 'Core',
                skill: 'Equation',
                title: 'Use the standard-form shortcut',
                stem: 'What is the slope of 4x + 5y = 20?',
                choices: ['-5/4', '-4/5', '4/5', '5/4'],
                answer: 1,
                explanation: {
                    steps: ['Here A = 4 and B = 5.', 'Use m = -A/B: m = -4/5.'],
                    trap: 'The slope is not the ratio in the order the coefficients appear; it includes a negative.',
                    takeaway: 'For Ax + By = C, slope is -A/B.',
                },
            },
            {
                id: 'point-slope',
                difficulty: 'Core',
                skill: 'Equation building',
                title: 'Use point-slope form',
                stem: 'Which equation represents the line with slope 4 through (-3, 2)?',
                choices: ['y - 2 = 4(x + 3)', 'y + 2 = 4(x - 3)', 'y - 2 = 4(x - 3)', 'y + 3 = 4(x - 2)'],
                answer: 0,
                explanation: {
                    steps: ['Use y - y₁ = m(x - x₁).', 'Substitute m = 4, x₁ = -3, and y₁ = 2.', 'Then y - 2 = 4(x - (-3)) = 4(x + 3).'],
                    trap: 'Subtracting a negative x-coordinate becomes addition inside the parentheses.',
                    takeaway: 'Point-slope form preserves the signs of the given point.',
                },
            },
            {
                id: 'horizontal',
                difficulty: 'Core',
                skill: 'Special slope',
                title: 'No vertical change',
                stem: 'What is the slope of the line through (2, 5) and (9, 5)?',
                choices: ['0', '5/7', '7/5', 'Undefined'],
                answer: 0,
                explanation: {
                    steps: ['The y-change is 5 - 5 = 0.', 'The x-change is 9 - 2 = 7.', 'The slope is 0/7 = 0.'],
                    trap: 'A horizontal line has slope zero, not undefined.',
                    takeaway: 'Zero rise with nonzero run gives slope zero.',
                },
            },
            {
                id: 'vertical',
                difficulty: 'Core',
                skill: 'Special slope',
                title: 'No horizontal change',
                stem: 'What is the slope of the line x = -4?',
                choices: ['-4', '0', '1/4', 'Undefined'],
                answer: 3,
                explanation: {
                    steps: ['Every point on the line has x-coordinate -4.', 'The run between any two points is zero.', 'Division by zero is undefined.'],
                    trap: 'The number -4 gives the line location, not its slope.',
                    takeaway: 'Vertical lines have undefined slope.',
                },
            },
            {
                id: 'context-rate',
                difficulty: 'Applied',
                skill: 'Interpretation',
                title: 'Say what a negative coefficient means',
                stem: 'A venue has P = 240 - 18t people remaining t minutes after an event ends. What does -18 represent?',
                choices: ['18 people enter each minute', '18 people leave each minute', 'The venue began with 18 people', 'The venue empties after 18 minutes'],
                answer: 1,
                explanation: {
                    steps: ['The coefficient of t is the rate of change.', 'Its units are people per minute.', 'The negative sign means the number remaining decreases, so 18 people leave each minute.'],
                    trap: 'The constant 240, not the slope, is the starting number of people.',
                    takeaway: 'Interpret slope with direction and units.',
                },
            },
            {
                id: 'nonlinear-average',
                difficulty: 'Advanced',
                skill: 'Average rate',
                title: 'A secant slope on a curve',
                stem: 'For f(x) = x² + 2, what is the average rate of change from x = 1 to x = 4?',
                math: '\\frac{f(4)-f(1)}{4-1}',
                choices: ['3', '5', '7', '15'],
                answer: 1,
                explanation: {
                    steps: ['Compute f(4) = 18 and f(1) = 3.', 'The output change is 15 and the input change is 3.', 'The average rate is 15/3 = 5.'],
                    trap: 'The output change 15 must still be divided by the interval length 3.',
                    takeaway: 'Average rate of change uses endpoint outputs over endpoint inputs.',
                },
            },
            {
                id: 'missing-coordinate',
                difficulty: 'Advanced',
                skill: 'Parameter',
                title: 'Solve inside the slope formula',
                stem: 'The line through (k, 7) and (4, 1) has slope -2. What is k?',
                math: '\\frac{1-7}{4-k}=-2',
                choices: ['-1', '1', '3', '7'],
                answer: 1,
                explanation: {
                    steps: ['Write -6/(4 - k) = -2.', 'Multiply: -6 = -8 + 2k.', 'Add 8: 2 = 2k, so k = 1.'],
                    trap: 'Canceling the negative signs before preserving the denominator expression can lose the k sign.',
                    takeaway: 'Use the known slope to form and solve an equation for the missing coordinate.',
                },
            },
            {
                id: 'parameter-standard',
                difficulty: 'Advanced',
                skill: 'Coefficient matching',
                title: 'Force a standard-form slope',
                stem: 'The line kx + 6y = 12 has slope -2/3. What is k?',
                choices: ['2', '3', '4', '9'],
                answer: 2,
                explanation: {
                    steps: ['The slope of kx + 6y = 12 is -k/6.', 'Set -k/6 = -2/3.', 'Multiply by -6: k = 4.'],
                    trap: 'The constant 12 does not affect slope.',
                    takeaway: 'Match -A/B to the required slope and solve for the parameter.',
                },
            },
        ],
    },
};

export default slopeAsRateOfChange;
