const systemsAsIntersections = {
    slug: 'systems-as-intersections',
    moduleId: 'linear-functions-systems',
    title: 'Systems as Intersections',
    eyebrow: 'Algebra',
    minutes: '35 min',
    summary: 'A system asks where two conditions are true at once. The best method depends on structure, not on a fixed favorite algorithm.',
    goals: [
        'Interpret a system solution as an intersection that satisfies both equations.',
        'Choose efficiently among substitution, elimination, graphing, and expression matching.',
        'Recognize one-solution, no-solution, and infinite-solution systems.',
        'Use determinants and parameter conditions on hard Module 2 problems.',
    ],
    facts: [
        {label: 'Solution', value: 'one ordered pair', note: 'it must satisfy every equation in the system'},
        {label: 'Substitution', value: 'replace a variable', note: 'best when one equation already isolates a variable'},
        {label: 'Elimination', value: 'cancel a variable', note: 'best when coefficients match or become opposites easily'},
        {label: 'Graph meaning', value: 'intersection', note: 'one, zero, or infinitely many shared points'},
    ],
    sections: [
        {
            heading: 'Big idea 1: a solution must satisfy both conditions',
            paragraphs: [
                'Each linear equation represents a line and a set of ordered pairs. A system solution belongs to both sets, so it is the point where the two lines intersect.',
                'Finding x is not always the end. Unless the question asks for x alone or a target expression, substitute back to find y and report the ordered pair.',
            ],
        },
        {
            heading: 'Big idea 2: choose the method from the equation structure',
            paragraphs: [
                'Use substitution when a variable is already isolated or has coefficient 1. Use elimination when opposite coefficients already appear or a small multiplication will create them.',
                'Use graphing when the question asks for the number of intersections, an estimate, or a visual comparison. Exact algebra is usually faster when answer choices contain fractions or parameters.',
            ],
        },
        {
            heading: 'Big idea 3: sometimes the requested expression is easier than x and y',
            paragraphs: [
                'SAT questions may ask for x + y, 3x, or another combination. Before solving the full system, compare the requested expression with sums or differences of the given equations.',
                'Adding or subtracting whole equations preserves truth. A carefully chosen linear combination can produce the target immediately and avoid unnecessary arithmetic.',
            ],
        },
        {
            heading: 'Big idea 4: coefficient structure controls the number of solutions',
            paragraphs: [
                'Two different slopes intersect once. Equal slopes with different intercepts are parallel and never intersect. Equivalent equations describe the same line and share infinitely many points.',
                'For a parameterized system, the determinant ad - bc detects whether the coefficient rows are independent. A nonzero determinant guarantees exactly one solution; zero requires a second check of the constants.',
            ],
        },
    ],
    formulas: [
        {
            label: 'Intersection of slope-intercept lines',
            math: 'm_1x+b_1=m_2x+b_2 \\Rightarrow x=\\frac{b_2-b_1}{m_1-m_2}',
            note: 'Set the two y-expressions equal because both equal the same output at the intersection.',
            meaning: 'The initial gap b₂ - b₁ is closed at a relative rate m₁ - m₂.',
            useWhen: 'Both equations are already solved for y and the slopes differ.',
        },
        {
            label: 'Substitution principle',
            math: 'y=f(x),\\ y=g(x) \\Rightarrow f(x)=g(x)',
            note: 'Replace the isolated variable everywhere it appears in the other equation.',
            meaning: 'At the solution, the two formulas produce the same value.',
            useWhen: 'One equation already gives x or y in terms of the other variable.',
        },
        {
            label: 'Elimination principle',
            math: 'r(ax+by)+s(cx+dy)=re+sf',
            note: 'Multiply entire equations, then add or subtract them so one variable cancels.',
            meaning: 'Any linear combination of true equations is also true at their shared solution.',
            useWhen: 'Coefficients are equal, opposite, or easy multiples.',
        },
        {
            label: 'Determinant test',
            math: 'D=ad-bc',
            note: 'For ax + by = e and cx + dy = f, D ≠ 0 means exactly one solution. D = 0 means the lines are parallel or identical.',
            meaning: 'A nonzero determinant says the coefficient directions are not proportional.',
            useWhen: 'A hard parameter question asks when a system has one solution.',
        },
        {
            label: 'Cramer shortcut',
            math: '\\begin{aligned}x&=\\frac{ed-bf}{ad-bc}\\\\[4pt]y&=\\frac{af-ec}{ad-bc}\\end{aligned}',
            note: 'Use only when the determinant arithmetic is clean; ordinary elimination is often shorter.',
            meaning: 'The constants replace one coefficient column at a time.',
            useWhen: 'You need an exact coordinate from a compact 2-by-2 system and D is nonzero.',
        },
        {
            label: 'Same-slope classification',
            math: 'm_1=m_2,\\ b_1\\ne b_2\\Rightarrow 0\\text{ solutions};\\qquad m_1=m_2,\\ b_1=b_2\\Rightarrow \\infty',
            note: 'Equal slopes require comparing intercepts before classifying.',
            meaning: 'Parallel distinct lines never meet; identical lines meet at every point on the line.',
            useWhen: 'Variables cancel or equations reduce to proportional forms.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Substitute an isolated variable',
            prompt: 'Solve y = 2x + 1 and 3x + y = 16.',
            math: '3x+(2x+1)=16',
            steps: [
                'Replace y in the second equation with 2x + 1.',
                'Combine: 5x + 1 = 16, so 5x = 15 and x = 3.',
                'Substitute back: y = 2(3) + 1 = 7.',
                'The solution is (3, 7).',
            ],
            insight: 'Substitution converts two equations in two variables into one equation in one variable.',
            trap: 'After finding x, use either original equation to recover y.',
        },
        {
            level: 'Core SAT',
            title: 'Eliminate without extra multiplication',
            prompt: 'Solve 2x + 3y = 12 and 4x - 3y = 6.',
            math: '(2x+3y)+(4x-3y)=12+6',
            steps: [
                'Add the equations; +3y and -3y cancel.',
                'This gives 6x = 18, so x = 3.',
                'Substitute into 2x + 3y = 12: 6 + 3y = 12.',
                'Then y = 2, so the solution is (3, 2).',
            ],
            insight: 'Opposite coefficients signal that elimination should be nearly immediate.',
            trap: 'Add every term on each side, including both constants.',
        },
        {
            level: 'Core SAT',
            title: 'Find the intersection of two functions',
            prompt: 'Where do y = -x + 5 and y = 2x - 1 intersect?',
            math: '-x+5=2x-1',
            steps: [
                'Set the y-expressions equal.',
                'Add x and 1: 6 = 3x, so x = 2.',
                'Substitute: y = 2(2) - 1 = 3.',
                'The intersection is (2, 3).',
            ],
            insight: 'Equating outputs is substitution without writing an extra replacement step.',
            trap: 'The x-coordinate 2 alone is not the full intersection point.',
        },
        {
            level: 'Applied',
            title: 'Model a two-group total',
            prompt: 'A theater sold 40 adult and child tickets. Adult tickets cost $12, child tickets cost $8, and revenue was $400. Find each count.',
            math: 'a+c=40,\\qquad 12a+8c=400',
            steps: [
                'Multiply the count equation by 8: 8a + 8c = 320.',
                'Subtract it from the revenue equation: 4a = 80.',
                'So a = 20, and then c = 40 - 20 = 20.',
                'Check: 12(20) + 8(20) = 400.',
            ],
            insight: 'Multiplying the total-count equation by the cheaper price creates a useful baseline.',
            trap: 'The two ticket counts add to 40; each count does not equal 40.',
        },
        {
            level: 'Advanced',
            title: 'Classify a parameterized system',
            prompt: 'For what values of k does kx + 2y = 4 and 3x + 6y = 9 have exactly one solution?',
            math: 'D=k(6)-2(3)=6(k-1)',
            steps: [
                'Use coefficients a = k, b = 2, c = 3, and d = 6.',
                'A unique solution requires D ≠ 0.',
                'So 6(k - 1) ≠ 0, which means k ≠ 1.',
                'At k = 1, the left sides are proportional but the constants are not, so that case has no solution.',
            ],
            insight: 'The determinant isolates the one parameter value that makes the lines parallel.',
            trap: 'D = 0 does not automatically mean infinitely many solutions; compare constants next.',
        },
        {
            level: 'Advanced',
            title: 'Use Cramer’s rule as a compact check',
            prompt: 'Solve 2x + 3y = 7 and 5x - y = 9 using determinants.',
            math: 'D=2(-1)-3(5)=-17',
            steps: [
                'Compute x = [7(-1) - 3(9)]/(-17) = -34/-17 = 2.',
                'Compute y = [2(9) - 7(5)]/(-17) = -17/-17 = 1.',
                'The solution is (2, 1).',
                'Check: 2(2) + 3(1) = 7 and 5(2) - 1 = 9.',
            ],
            insight: 'Cramer’s rule can verify an elimination result quickly when the determinant is small.',
            trap: 'Keep the denominator ad - bc in the same order for both coordinates.',
        },
    ],
    strategyCards: [
        {
            title: 'Choose the method',
            items: ['Variable isolated: substitute', 'Opposite or matching coefficients: eliminate', 'Number of intersections or estimate: graph'],
        },
        {
            title: 'Look for a target shortcut',
            items: ['Compare the requested expression with each equation', 'Try adding or subtracting the equations as written', 'Solve the full pair only if the target does not appear'],
        },
        {
            title: 'Classify special systems',
            items: ['Different slopes or nonzero determinant: one solution', 'Same slope and different intercepts: no solution', 'Equivalent equations: infinitely many solutions'],
        },
    ],
    studyTips: [
        {
            title: 'Make method choice a five-second habit',
            summary: 'Do not begin expanding until you have scanned the coefficient structure.',
            items: [
                'Circle an already-isolated variable.',
                'Box equal or opposite coefficients.',
                'If neither appears, compare the smallest multipliers needed for elimination.',
            ],
        },
        {
            title: 'Check the ordered pair in both equations',
            summary: 'A value can satisfy the equation used last and still fail the other because of an earlier arithmetic error.',
            items: [
                'Substitute x and y into both original equations.',
                'Check left and right sides numerically.',
                'In context, also check nonnegative and whole-number restrictions.',
            ],
        },
        {
            title: 'Use graphing as verification, not decoration',
            summary: 'Desmos is powerful when you ask it a precise question.',
            items: [
                'Graph both equations to estimate the intersection before exact algebra.',
                'Use the visual to detect parallel or identical lines.',
                'For exact fractional answers, finish with algebra rather than reading rounded coordinates.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Pick the efficient method',
        prompt: 'For 4x + y = 13 and 2x - y = 5, which method is fastest?',
        options: [
            {
                id: 'eliminate',
                label: 'Add the equations',
                result: 'Best choice: y cancels immediately.',
                advice: 'Adding gives 6x = 18, so x = 3. Then y = 1.',
            },
            {
                id: 'substitute',
                label: 'Solve for y first',
                result: 'Correct, but one step longer.',
                advice: 'You can write y = 13 - 4x and substitute, but the opposite y-coefficients already invite elimination.',
            },
        ],
    },
    quickCheck: {
        prompt: 'The equations 2x + 4y = 8 and x + 2y = 5 form what kind of system?',
        choices: ['Exactly one solution', 'No solution', 'Infinitely many solutions', 'Exactly two solutions'],
        answer: 1,
        explanation: 'Dividing the first equation by 2 gives x + 2y = 4, which has the same left side but a different constant from x + 2y = 5. The lines are parallel and distinct.',
    },
    practiceSet: {
        title: 'Systems from foundation to hard Module 2',
        intro: 'The set progresses through substitution and elimination into target expressions, special cases, fractions, and parameter classification.',
        questions: [
            {
                id: 'basic-substitution',
                difficulty: 'Foundation',
                skill: 'Substitution',
                title: 'Replace the isolated variable',
                stem: 'What is the solution to y = x + 2 and 2x + y = 11?',
                choices: ['(2, 5)', '(3, 5)', '(3, 7)', '(5, 3)'],
                answer: 1,
                explanation: {
                    steps: ['Substitute y = x + 2: 2x + x + 2 = 11.', 'Then 3x = 9, so x = 3.', 'y = 3 + 2 = 5.'],
                    trap: 'Report the ordered pair as (x, y), not (y, x).',
                    takeaway: 'An isolated variable makes substitution direct.',
                },
            },
            {
                id: 'basic-elimination',
                difficulty: 'Foundation',
                skill: 'Elimination',
                title: 'Add opposite coefficients',
                stem: 'What is the solution to x + y = 9 and x - y = 1?',
                choices: ['(4, 5)', '(5, 4)', '(8, 1)', '(9, 1)'],
                answer: 1,
                explanation: {
                    steps: ['Add the equations: 2x = 10.', 'So x = 5.', 'Then y = 9 - 5 = 4.'],
                    trap: 'The y-terms cancel; do not add them to 2y.',
                    takeaway: 'Opposite coefficients are ready for immediate elimination.',
                },
            },
            {
                id: 'function-intersection',
                difficulty: 'Core',
                skill: 'Intersection',
                title: 'Equate two outputs',
                stem: 'Where do y = 3x - 4 and y = -x + 8 intersect?',
                choices: ['(2, 2)', '(3, 5)', '(4, 8)', '(5, 11)'],
                answer: 1,
                explanation: {
                    steps: ['Set 3x - 4 = -x + 8.', 'Then 4x = 12, so x = 3.', 'Substitute to get y = 5.'],
                    trap: 'Solving 4x = 12 gives the x-coordinate, not y.',
                    takeaway: 'At an intersection, both formulas produce the same output.',
                },
            },
            {
                id: 'parallel-no-solution',
                difficulty: 'Core',
                skill: 'Classification',
                title: 'Proportional left sides, conflicting constants',
                stem: 'How many solutions does 2x + 4y = 8 and x + 2y = 5 have?',
                choices: ['None', 'One', 'Two', 'Infinitely many'],
                answer: 0,
                explanation: {
                    steps: ['Divide the first equation by 2: x + 2y = 4.', 'The second says the same expression equals 5.', 'Both cannot be true, so there is no solution.'],
                    trap: 'Proportional coefficients do not guarantee infinitely many solutions unless constants match too.',
                    takeaway: 'Same slope and different intercepts means no intersection.',
                },
            },
            {
                id: 'identical-infinite',
                difficulty: 'Core',
                skill: 'Classification',
                title: 'Equivalent equations',
                stem: 'How many solutions does 3x - 6y = 9 and x - 2y = 3 have?',
                choices: ['None', 'One', 'Three', 'Infinitely many'],
                answer: 3,
                explanation: {
                    steps: ['Divide the first equation by 3: x - 2y = 3.', 'This is exactly the second equation.', 'Every point on that line satisfies both.'],
                    trap: 'Two written equations can represent only one distinct line.',
                    takeaway: 'Equivalent equations produce infinitely many shared points.',
                },
            },
            {
                id: 'context-items',
                difficulty: 'Applied',
                skill: 'Modeling',
                title: 'Two item types',
                stem: 'A store sells 25 notebooks and pens total. Notebooks cost $5, pens cost $2, and revenue is $80. How many notebooks were sold?',
                choices: ['5', '10', '15', '20'],
                answer: 1,
                explanation: {
                    steps: ['Let n + p = 25 and 5n + 2p = 80.', 'Multiply the first by 2: 2n + 2p = 50.', 'Subtract: 3n = 30, so n = 10.'],
                    trap: 'The $3 price difference applies only after accounting for the $50 all-pen baseline.',
                    takeaway: 'Use the total-count equation to eliminate one group.',
                },
            },
            {
                id: 'target-expression',
                difficulty: 'Advanced',
                skill: 'Linear combination',
                title: 'Produce the target without solving both variables',
                stem: 'If 7x + 2y = 20 and 3x - 2y = 4, what is 5x?',
                choices: ['6', '10', '12', '24'],
                answer: 2,
                explanation: {
                    steps: ['Add the equations: 10x = 24.', 'Divide by 2: 5x = 12.', 'The requested expression is obtained without finding x or y separately.'],
                    trap: 'Stopping at 10x = 24 answers a different expression.',
                    takeaway: 'Scale a combined equation to match the exact target.',
                },
            },
            {
                id: 'parameter-unique',
                difficulty: 'Advanced',
                skill: 'Determinant',
                title: 'Guarantee one intersection',
                stem: 'For what condition does kx + 2y = 4 and 3x + 6y = 9 have exactly one solution?',
                choices: ['k = 0', 'k = 1', 'k ≠ 1', 'k ≠ 3'],
                answer: 2,
                explanation: {
                    steps: ['The determinant is 6k - 6 = 6(k - 1).', 'Exactly one solution requires a nonzero determinant.', 'Therefore k ≠ 1.'],
                    trap: 'At k = 1, the coefficients are proportional and the constants conflict.',
                    takeaway: 'A nonzero coefficient determinant guarantees a unique solution.',
                },
            },
            {
                id: 'parameter-infinite',
                difficulty: 'Advanced',
                skill: 'Identity condition',
                title: 'Make two equations equivalent',
                stem: 'For what value of p do (p - 1)x + 2y = 6 and 2x + 4y = 12 have infinitely many solutions?',
                choices: ['1', '2', '3', '4'],
                answer: 1,
                explanation: {
                    steps: ['Divide the second equation by 2: x + 2y = 6.', 'Match the x-coefficient: p - 1 = 1.', 'Thus p = 2.'],
                    trap: 'Matching p directly to 1 ignores the expression p - 1.',
                    takeaway: 'Infinite solutions require every corresponding coefficient and constant to be proportional.',
                },
            },
            {
                id: 'cramer-coordinate',
                difficulty: 'Advanced',
                skill: 'Determinant shortcut',
                title: 'Compute one coordinate compactly',
                stem: 'What is x in the system 2x + 3y = 7 and 5x - y = 9?',
                choices: ['1', '2', '3', '4'],
                answer: 1,
                explanation: {
                    steps: ['The determinant is 2(-1) - 3(5) = -17.', 'The x-numerator is 7(-1) - 3(9) = -34.', 'Therefore x = -34/-17 = 2.'],
                    trap: 'Cramer’s x-numerator replaces the x-coefficient column with constants.',
                    takeaway: 'Use the determinant shortcut only when its arithmetic is cleaner than elimination.',
                },
            },
            {
                id: 'fraction-system',
                difficulty: 'Advanced',
                skill: 'Fractions',
                title: 'Clear denominators before eliminating',
                stem: 'What is the solution to x/2 + y/3 = 4 and x - y = 3?',
                choices: ['(3, 0)', '(5, 2)', '(6, 3)', '(8, 5)'],
                answer: 2,
                explanation: {
                    steps: ['Multiply the first equation by 6: 3x + 2y = 24.', 'From x - y = 3, y = x - 3.', 'Substitute: 3x + 2x - 6 = 24, so x = 6 and y = 3.'],
                    trap: 'Multiplying by 6 must hit both fraction terms and the constant 4.',
                    takeaway: 'Remove denominator clutter before choosing a system method.',
                },
            },
            {
                id: 'parameter-no-solution',
                difficulty: 'Advanced',
                skill: 'Parallel condition',
                title: 'Force parallel distinct lines',
                stem: 'For what value of a do (a + 1)x + 2y = 5 and 3x + 6y = 4 have no solution?',
                choices: ['-1', '0', '1', '2'],
                answer: 1,
                explanation: {
                    steps: ['Divide the second equation by 3: x + 2y = 4/3.', 'For matching left-side coefficients, a + 1 = 1, so a = 0.', 'The constants 5 and 4/3 differ, so the lines are parallel and distinct.'],
                    trap: 'Do not scale the constant independently from its equation.',
                    takeaway: 'No solution requires proportional variable coefficients but inconsistent constants.',
                },
            },
        ],
    },
};

export default systemsAsIntersections;
