const tablesToEquations = {
    slug: 'tables-to-equations',
    moduleId: 'linear-functions-systems',
    title: 'Tables to Equations',
    eyebrow: 'Algebra',
    minutes: '32 min',
    summary: 'A linear table is an equation in disguise: constant rate determines the slope, and any row can reveal the intercept.',
    goals: [
        'Decide whether a table represents a linear function, even with uneven input intervals.',
        'Build a linear equation when the table does not include x = 0.',
        'Recover missing values, parameters, and target inputs efficiently.',
        'Track how shifts and transformations change a table-based linear model.',
    ],
    facts: [
        {label: 'Linear test', value: 'constant Δy/Δx', note: 'constant first differences work only when x-steps are equal'},
        {label: 'Slope', value: 'rate between rows', note: 'use any two distinct rows of a truly linear table'},
        {label: 'Intercept', value: 'b = y - mx', note: 'substitute any known row after finding m'},
        {label: 'Fast prediction', value: 'known row + rate', note: 'point-slope thinking can avoid finding b'},
    ],
    sections: [
        {
            heading: 'Big idea 1: constant differences need equal input steps',
            paragraphs: [
                'If x increases by the same amount in every row, a linear table has a constant change in y. But when the x-steps are uneven, comparing raw y-differences is misleading.',
                'The reliable test is slope: divide each y-change by its matching x-change. A table is linear only when those rates agree across every interval.',
            ],
        },
        {
            heading: 'Big idea 2: a row is a point, not automatically an intercept',
            paragraphs: [
                'Every table row (x, y) is a point on the graph. Only a row with x = 0 directly gives the y-intercept. If zero is missing, first find the slope and then use b = y - mx.',
                'Students often treat the first visible row as the starting value. The table may begin at x = 5 even though the model began earlier, so always inspect the input coordinate.',
            ],
        },
        {
            heading: 'Big idea 3: point-slope form is often the fastest table model',
            paragraphs: [
                'Once you know a slope m and one row (a, f(a)), the equation f(x) = f(a) + m(x - a) predicts every other value. This form is especially useful when the intercept is fractional or never requested.',
                'If the question asks for standard form or slope-intercept form, expand only at the end. Keeping the anchored form reduces arithmetic and sign errors.',
            ],
        },
        {
            heading: 'Big idea 4: transformations preserve or modify table structure',
            paragraphs: [
                'Adding a constant outside a function shifts every output and keeps the slope unchanged. Replacing x by x + h shifts which original input is used; for a linear function, the slope still stays unchanged but the intercept changes.',
                'For high-difficulty questions, substitute the transformation into the original equation before rebuilding a table. Algebra is usually faster than calculating several transformed rows.',
            ],
        },
    ],
    formulas: [
        {
            label: 'Slope from two table rows',
            math: 'm=\\frac{y_2-y_1}{x_2-x_1}',
            note: 'Treat each row as an ordered pair and preserve subtraction order.',
            meaning: 'The table output changes by m units for each 1-unit input increase.',
            useWhen: 'You have any two distinct rows from a linear table.',
        },
        {
            label: 'Linear-table test',
            math: '\\frac{\\Delta y_1}{\\Delta x_1}=\\frac{\\Delta y_2}{\\Delta x_2}=\\cdots',
            note: 'Equal y-differences alone are sufficient only when every x-difference is equal.',
            meaning: 'Every secant slope is the same because all points lie on one line.',
            useWhen: 'You must decide whether a table is linear or choose among competing tables.',
        },
        {
            label: 'Recover the intercept',
            math: 'b=y-mx',
            note: 'Substitute the coordinates from any known row after calculating m.',
            meaning: 'Move backward from the known output by m times the known input.',
            useWhen: 'The table does not contain a row with x = 0.',
        },
        {
            label: 'Anchored linear form',
            math: 'f(x)=f(a)+m(x-a)',
            note: 'This is point-slope form written in function language.',
            meaning: 'Start at the known output f(a), then apply the rate over the change x - a.',
            useWhen: 'You need a prediction more than you need the y-intercept.',
        },
        {
            label: 'Solve backward for an input',
            math: 'y=mx+b \\Rightarrow x=\\frac{y-b}{m},\\quad m\\ne0',
            note: 'Set the requested output first, then solve for the input.',
            meaning: 'Remove the starting value and divide the remaining change by the per-input rate.',
            useWhen: 'A table model asks when or at what input a target output occurs.',
        },
        {
            label: 'Linear output shift',
            math: 'g(x)=f(x+h)+k,\\quad f(x)=mx+b \\Rightarrow g(x)=mx+(mh+b+k)',
            note: 'The slope remains m; the intercept becomes mh + b + k.',
            meaning: 'A horizontal input shift changes a linear output by mh, while k adds a vertical shift.',
            useWhen: 'A hard question transforms a function defined by a table or equation.',
        },
    ],
    workedExamples: [
        {
            level: 'Foundation',
            title: 'Use the zero-input row',
            prompt: 'A table contains (0, 5), (1, 8), and (2, 11). Write its equation.',
            math: 'f(x)=3x+5',
            steps: [
                'The equal x-steps are 1 and the equal y-steps are 3, so m = 3.',
                'The row (0, 5) gives the y-intercept b = 5.',
                'Substitute into f(x) = mx + b to get f(x) = 3x + 5.',
            ],
            insight: 'When x = 0 appears, the intercept requires no calculation.',
            trap: 'The first difference 3 is the slope here only because each x-step equals 1.',
        },
        {
            level: 'Core SAT',
            title: 'Build an equation without x = 0',
            prompt: 'A linear table includes (2, 11) and (5, 23). Find its equation.',
            math: 'm=\\frac{23-11}{5-2}=4',
            steps: [
                'Compute the slope: m = 12/3 = 4.',
                'Use b = y - mx with (2, 11): b = 11 - 4(2) = 3.',
                'The equation is y = 4x + 3.',
                'Check the second row: 4(5) + 3 = 23.',
            ],
            insight: 'Any row gives the same b if the slope is correct and the table is linear.',
            trap: 'The first visible output 11 is not the intercept because its input is 2, not 0.',
        },
        {
            level: 'Core SAT',
            title: 'Test uneven intervals',
            prompt: 'Determine whether the points (1, 4), (3, 10), and (8, 25) form a linear table.',
            math: '\\frac{10-4}{3-1}=3,\\qquad \\frac{25-10}{8-3}=3',
            steps: [
                'The first interval has rate 6/2 = 3.',
                'The second interval has rate 15/5 = 3.',
                'The rates match, so all three points lie on one line.',
            ],
            insight: 'The y-differences 6 and 15 are unequal because the x-intervals 2 and 5 are unequal.',
            trap: 'Do not reject a linear table merely because its raw first differences are not equal.',
        },
        {
            level: 'Advanced',
            title: 'Recover a missing table entry',
            prompt: 'The points (2, 7), (5, p), and (9, 21) lie on one line. Find p.',
            math: 'm=\\frac{21-7}{9-2}=2',
            steps: [
                'Use the two complete rows to find slope 14/7 = 2.',
                'Move from x = 2 to x = 5, a change of 3.',
                'The output rises by 2(3) = 6.',
                'Therefore p = 7 + 6 = 13.',
            ],
            insight: 'Anchored prediction is faster than finding the full equation.',
            trap: 'Adding only the slope 2 ignores that x increased by 3 units.',
        },
        {
            level: 'Applied',
            title: 'Read a model and its units from a table',
            prompt: 'A service costs $31 at 2 hours and $67 at 8 hours. Assume a linear model. Find the hourly rate and fixed fee.',
            math: 'm=\\frac{67-31}{8-2}=6',
            steps: [
                'The cost increases $36 over 6 hours, so the rate is $6 per hour.',
                'Use b = y - mx: b = 31 - 6(2) = 19.',
                'The model is C = 6h + 19, so the fixed fee is $19.',
            ],
            insight: 'Slope and intercept have different units: dollars per hour versus dollars.',
            trap: 'Dividing $31 by 2 hours mixes the fixed fee into the hourly rate.',
        },
        {
            level: 'Advanced',
            title: 'Transform a linear function',
            prompt: 'A table represents f(x) = 4x - 1. Define g(x) = f(x + 2) - 3. Find g(x).',
            math: 'g(x)=4(x+2)-1-3',
            steps: [
                'Replace every x in f with x + 2: f(x + 2) = 4(x + 2) - 1.',
                'Then subtract 3 outside the function.',
                'Simplify: g(x) = 4x + 8 - 1 - 3 = 4x + 4.',
            ],
            insight: 'The transformation changes the intercept from -1 to 4 but preserves slope 4.',
            trap: 'Replacing f(x + 2) with f(x) + 2 misses the fourfold effect of the input shift.',
        },
    ],
    strategyCards: [
        {
            title: 'Build the model',
            items: ['Test rates if linearity is not guaranteed', 'Find m from two rows', 'Use x = 0 directly or calculate b = y - mx'],
        },
        {
            title: 'Avoid unnecessary work',
            items: ['Use anchored form for one prediction', 'Use complete rows to find a missing entry', 'Do not expand until the requested equation form requires it'],
        },
        {
            title: 'Hard-question checks',
            items: ['Verify a third row after building the equation', 'Track input shifts inside the function before output shifts outside', 'Keep rate units separate from intercept units'],
        },
    ],
    studyTips: [
        {
            title: 'Annotate table differences',
            summary: 'Write Δx and Δy between rows instead of looking only at the columns.',
            items: [
                'For equal x-steps, compare y-differences quickly.',
                'For uneven x-steps, write Δy/Δx beside every interval.',
                'Circle x = 0 if it appears; that row gives the intercept.',
            ],
        },
        {
            title: 'Practice the two-model method',
            summary: 'Build the same line in both slope-intercept and anchored form.',
            items: [
                'Use y = mx + b when interpretation or the intercept matters.',
                'Use y - y₁ = m(x - x₁) when predicting from a known row.',
                'Confirm the two forms agree by expanding the anchored form.',
            ],
        },
        {
            title: 'Use a third row as a checksum',
            summary: 'One incorrect sign can still produce an equation through the two rows you used.',
            items: [
                'Substitute a row that was not used to calculate m or b.',
                'If it fails, recheck subtraction order before redoing everything.',
                'On multiple choice, test a convenient row directly in the answer choices.',
            ],
        },
    ],
    adaptiveDemo: {
        title: 'Choose the fastest route',
        prompt: 'A linear table contains (7, 20) and (11, 32), and you need f(15). What should you do?',
        options: [
            {
                id: 'anchored',
                label: 'Predict from (11, 32)',
                result: 'Fastest: the slope is 3, then move 4 inputs.',
                advice: 'From x = 11 to 15, y rises by 3(4) = 12, so f(15) = 44. No intercept is needed.',
            },
            {
                id: 'full-equation',
                label: 'Find y = mx + b',
                result: 'Correct, but longer for this question.',
                advice: 'You would find m = 3 and b = -1, then calculate f(15) = 45 - 1 = 44.',
            },
        ],
    },
    quickCheck: {
        prompt: 'A linear table contains (3, 14) and (7, 30). Which equation represents it?',
        choices: ['y = 2x + 8', 'y = 4x + 2', 'y = 4x + 14', 'y = 8x - 10'],
        answer: 1,
        explanation: 'The slope is (30 - 14)/(7 - 3) = 16/4 = 4. Then b = 14 - 4(3) = 2, so y = 4x + 2.',
    },
    practiceSet: {
        title: 'Tables from foundation to hard Module 2',
        intro: 'The set moves from reading a zero-input row to uneven intervals, parameters, transformations, and extrapolation.',
        questions: [
            {
                id: 'zero-row-equation',
                difficulty: 'Foundation',
                skill: 'Equation building',
                title: 'Read slope and intercept',
                stem: 'A linear table contains (0, 4), (1, 7), and (2, 10). Which equation represents it?',
                choices: ['y = 3x + 4', 'y = 4x + 3', 'y = 7x - 3', 'y = 10x - 6'],
                answer: 0,
                explanation: {
                    steps: ['Each 1-unit x increase raises y by 3, so m = 3.', 'At x = 0, y = 4, so b = 4.', 'The equation is y = 3x + 4.'],
                    trap: 'Swapping the slope and intercept gives y = 4x + 3.',
                    takeaway: 'The zero-input row gives b directly.',
                },
            },
            {
                id: 'uneven-rate',
                difficulty: 'Foundation',
                skill: 'Slope',
                title: 'Divide by the actual input change',
                stem: 'What is the rate of change between the table rows (2, 5) and (8, 23)?',
                choices: ['2', '3', '6', '18'],
                answer: 1,
                explanation: {
                    steps: ['The output change is 23 - 5 = 18.', 'The input change is 8 - 2 = 6.', 'The rate is 18/6 = 3.'],
                    trap: 'The raw output change 18 is not a per-unit rate.',
                    takeaway: 'Slope divides matching output and input changes.',
                },
            },
            {
                id: 'missing-zero',
                difficulty: 'Core',
                skill: 'Intercept',
                title: 'Recover b from a row',
                stem: 'A linear table contains (3, 14) and (7, 30). Which equation represents it?',
                choices: ['y = 2x + 8', 'y = 4x + 2', 'y = 4x + 14', 'y = 8x - 10'],
                answer: 1,
                explanation: {
                    steps: ['Slope is 16/4 = 4.', 'Using (3, 14), b = 14 - 4(3) = 2.', 'Thus y = 4x + 2.'],
                    trap: 'The output 14 at x = 3 is not the y-intercept.',
                    takeaway: 'When x = 0 is absent, use b = y - mx.',
                },
            },
            {
                id: 'linearity-test',
                difficulty: 'Core',
                skill: 'Linear test',
                title: 'Compare interval rates',
                stem: 'Which set of points lies on one line?',
                choices: ['(0, 1), (2, 5), (5, 11)', '(0, 1), (2, 5), (5, 10)', '(0, 1), (2, 4), (5, 10)', '(0, 1), (2, 6), (5, 13)'],
                answer: 0,
                explanation: {
                    steps: ['For choice A, the rates are (5 - 1)/2 = 2 and (11 - 5)/3 = 2.', 'The matching rates show all three points are collinear.'],
                    trap: 'Uneven x-spacing means raw y-differences should not be equal.',
                    takeaway: 'Compare Δy/Δx across intervals, not Δy alone.',
                },
            },
            {
                id: 'missing-entry',
                difficulty: 'Core',
                skill: 'Missing value',
                title: 'Interpolate with a known rate',
                stem: 'The points (1, 6), (4, p), and (7, 24) lie on one line. What is p?',
                choices: ['9', '12', '15', '18'],
                answer: 2,
                explanation: {
                    steps: ['The slope from (1, 6) to (7, 24) is 18/6 = 3.', 'From x = 1 to x = 4 is 3 input units.', 'Add 3(3) = 9 to 6: p = 15.'],
                    trap: 'Adding the slope once ignores the three-unit input change.',
                    takeaway: 'Output change equals slope times input change.',
                },
            },
            {
                id: 'target-input',
                difficulty: 'Core',
                skill: 'Solve backward',
                title: 'Find when an output occurs',
                stem: 'A linear table contains (2, 11) and (6, 23). At what x-value is y = 50?',
                choices: ['10', '12', '15', '18'],
                answer: 2,
                explanation: {
                    steps: ['The slope is 12/4 = 3.', 'The equation is y = 3x + 5.', 'Set 50 = 3x + 5, so 45 = 3x and x = 15.'],
                    trap: 'Dividing 50 directly by 3 ignores the intercept 5.',
                    takeaway: 'Remove the starting value before dividing by the rate.',
                },
            },
            {
                id: 'parameter-coefficients',
                difficulty: 'Advanced',
                skill: 'Parameters',
                title: 'Recover both coefficients',
                stem: 'For f(x) = ax + b, a table gives f(-2) = 9 and f(4) = -3. What is a + b?',
                choices: ['-7', '1', '3', '7'],
                answer: 2,
                explanation: {
                    steps: ['The slope a = (-3 - 9)/(4 - (-2)) = -12/6 = -2.', 'Use 9 = -2(-2) + b to get 9 = 4 + b, so b = 5.', 'Therefore a + b = -2 + 5 = 3.'],
                    trap: 'The negative input -2 makes a(-2) positive when a = -2.',
                    takeaway: 'The table rate gives a; one row then gives b.',
                },
            },
            {
                id: 'context-table',
                difficulty: 'Applied',
                skill: 'Units',
                title: 'Separate rate from fixed cost',
                stem: 'A service costs $25 at 0 minutes, $43 at 3 minutes, and $67 at 7 minutes. What does the slope represent?',
                choices: ['$6 per minute', '$18 per minute', 'A $25 per-minute fee', 'A $67 fixed fee'],
                answer: 0,
                explanation: {
                    steps: ['From 0 to 3 minutes, cost rises $18 over 3 minutes.', 'The slope is $6 per minute.', 'The later interval also gives $24/4 = $6 per minute.'],
                    trap: 'The $25 value is the fixed starting cost, not a rate.',
                    takeaway: 'Slope units are output units per input unit.',
                },
            },
            {
                id: 'standard-form-match',
                difficulty: 'Core',
                skill: 'Equivalent equations',
                title: 'Match a table to standard form',
                stem: 'A line contains (1, 4) and (3, 10). Which standard-form equation represents it?',
                choices: ['3x - y = -1', '3x + y = 7', 'x - 3y = -11', 'x + 3y = 13'],
                answer: 0,
                explanation: {
                    steps: ['Slope is (10 - 4)/(3 - 1) = 3.', 'Using (1, 4), b = 4 - 3 = 1, so y = 3x + 1.', 'Rearrange to 3x - y = -1.'],
                    trap: 'Moving y across the equals sign changes its sign.',
                    takeaway: 'Build the familiar form first, then rearrange only if needed.',
                },
            },
            {
                id: 'function-shift',
                difficulty: 'Advanced',
                skill: 'Transformation',
                title: 'Shift inputs and outputs',
                stem: 'If f(x) = 4x - 1 and g(x) = f(x + 2) - 3, what is g(0)?',
                choices: ['-4', '-1', '4', '8'],
                answer: 2,
                explanation: {
                    steps: ['g(0) = f(2) - 3.', 'f(2) = 8 - 1 = 7.', 'Therefore g(0) = 7 - 3 = 4.'],
                    trap: 'The +2 is inside f, so evaluate f at 2 before subtracting 3.',
                    takeaway: 'Follow function transformations from the inside out.',
                },
            },
            {
                id: 'compare-table-rates',
                difficulty: 'Advanced',
                skill: 'Comparison',
                title: 'Compare models with different spacing',
                stem: 'Table A contains (1, 5) and (4, 17). Table B contains (2, 9) and (8, 27). How much greater is A’s rate than B’s?',
                choices: ['1', '3', '4', '9'],
                answer: 0,
                explanation: {
                    steps: ['Table A rate is 12/3 = 4.', 'Table B rate is 18/6 = 3.', 'The difference is 4 - 3 = 1.'],
                    trap: 'Comparing raw output changes 12 and 18 ignores different input intervals.',
                    takeaway: 'Normalize both models to per-unit rates before comparing.',
                },
            },
            {
                id: 'extrapolation',
                difficulty: 'Advanced',
                skill: 'Model extension',
                title: 'Extrapolate far beyond the table',
                stem: 'A linear model contains (50, 132) and (80, 198). What output does it predict at x = 120?',
                choices: ['242', '264', '286', '308'],
                answer: 2,
                explanation: {
                    steps: ['Slope is (198 - 132)/(80 - 50) = 66/30 = 2.2.', 'Find b = 132 - 2.2(50) = 22.', 'At x = 120, y = 2.2(120) + 22 = 264 + 22 = 286.'],
                    trap: 'Extending the 66-unit output increase once assumes another 30 input units, but x rises by 40 from 80 to 120.',
                    takeaway: 'Use the per-unit model when extrapolating across a new interval length.',
                },
            },
        ],
    },
};

export default tablesToEquations;
