const parallelLinesAndAngleChasing = {
    slug:'parallel-lines-and-angle-chasing',moduleId:'triangles-similarity',title:'Parallel Lines & Angle Chasing',eyebrow:'Geometry and Trigonometry',minutes:'35 min',
    summary:'Turn crowded diagrams into a few dependable angle relationships, including the algebraic and parameter versions common in harder modules.',
    goals:['Recognize vertical, linear-pair, corresponding, alternate-interior, and same-side-interior angles.','Use parallel markings before trusting how a diagram looks.','Build and solve equations from angle expressions.','Combine line facts with triangle angle sums in multistep diagrams.'],
    facts:[{label:'Vertical angles',math:'\\angle1=\\angle3',note:'opposite angles at an intersection'},{label:'Linear pair',math:'\\angle1+\\angle2=180^\\circ',note:'adjacent angles on a line'},{label:'Corresponding',value:'equal',note:'when a transversal crosses parallel lines'},{label:'Same-side interior',math:'a+b=180^\\circ',note:'supplementary for parallel lines'}],
    sections:[
        {heading:'Big idea 1: classify the relationship before writing an equation',paragraphs:['At one intersection, opposite angles are vertical and equal; adjacent angles whose outside sides form a straight line are supplementary. These facts do not require parallel lines.','When two lines are marked parallel, a transversal copies an acute angle to every acute position and an obtuse angle to every obtuse position.'],math:'\\text{equal or supplementary}\\;\\longrightarrow\\;\\text{equation}'},
        {heading:'Big idea 2: parallel markings are conditions, not decoration',paragraphs:['Corresponding and alternate-interior equality depends on parallel lines. If the lines are not stated or marked parallel, you cannot assume those relationships from appearance.','The converse can also appear: if a corresponding or alternate-interior pair is equal, the two lines are parallel.']},
        {heading:'Big idea 3: angle expressions are still angle measures',paragraphs:['Set equal expressions equal, and set supplementary expressions to a sum of 180. Solve for the variable, then substitute back if the question asks for an angle rather than the variable.','Reject values that make an angle zero, negative, or at least 180 degrees in an ordinary triangle.']},
        {heading:'Big idea 4: harder diagrams chain one fact at a time',paragraphs:['Do not search for one giant formula. Transfer an angle through vertical or parallel relationships, place it inside a triangle, and then use the triangle sum.','Mark every value you prove on the diagram. This keeps the chain visible and prevents using the same fact twice.']},
    ],
    formulas:[
        {label:'Straight line',math:'m\\angle1+m\\angle2=180^\\circ',note:'A linear pair is supplementary.',meaning:'A half-turn measures 180 degrees.',useWhen:'Two adjacent angles share a ray and their other sides form a line.'},
        {label:'Angles around a point',math:'\\sum m\\angle=360^\\circ',note:'Include every nonoverlapping angle around the vertex.',meaning:'One full rotation measures 360 degrees.',useWhen:'Three or more angles surround one point.'},
        {label:'Parallel-line equalities',math:'\\text{corresponding}=\\text{alternate interior}=\\text{alternate exterior}',note:'Each named pair must belong to the same transversal.',meaning:'Parallel lines preserve the transversal’s angle with each line.',useWhen:'Parallel arrows or an explicit parallel condition appear.'},
        {label:'Same-side interior',math:'m\\angle a+m\\angle b=180^\\circ',note:'Also called consecutive interior angles.',meaning:'The pair fills a straight-angle turn between parallel lines.',useWhen:'Both angles lie between the parallels on one side of a transversal.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Solve a vertical-angle equation',prompt:'Vertical angles measure 5x minus 8 degrees and 3x plus 24 degrees. Find x.',math:'5x-8=3x+24',steps:[{text:'Vertical angles are equal.'},{text:'Solve.',math:'2x=32\\Rightarrow x=16'},{text:'Check the common angle.',math:'5(16)-8=72^\\circ'}],insight:'The relationship determines the equation before the algebra begins.',trap:'Do not add vertical angles to 180 unless they also form a linear pair.'},
        {level:'Core SAT',title:'Use supplementary expressions',prompt:'Same-side interior angles are 7x plus 5 degrees and 4x minus 1 degrees. The lines are parallel. Find the larger angle.',math:'(7x+5)+(4x-1)=180',steps:[{text:'Solve for x.',math:'11x+4=180\\Rightarrow x=16'},{text:'Evaluate both angles.',math:'117^\\circ\\text{ and }63^\\circ'}],insight:'The question asks for an angle, so solving for x is only an intermediate step.',trap:'Same-side interior angles add to 180; they are not generally equal.'},
        {level:'Advanced',title:'Chain a transversal into a triangle',prompt:'A transversal makes a 68-degree acute angle with one of two parallel lines. Inside the strip, it and a second segment form a triangle whose other known angle is 47 degrees. Find the third angle.',math:'68+47+x=180',steps:[{text:'Transfer the 68-degree angle using alternate-interior angles.'},{text:'Apply the triangle sum.',math:'x=65^\\circ'}],insight:'Hard diagrams often combine one line theorem with one triangle theorem.',trap:'Use the interior angle that belongs to the triangle, not its supplementary neighbor.'},
    ],
    strategyCards:[{title:'Label the diagram',items:['Mark vertical pairs with matching symbols.','Write 180 beside straight lines.','Trace one transversal at a time.']},{title:'Translate expressions',items:['Equal pair: set expressions equal.','Supplementary pair: sum to 180.','Substitute back for the requested angle.']},{title:'Check geometry',items:['Use only stated parallel lines.','Ordinary angles must be between 0 and 180 degrees.','Acute and obtuse positions should match the diagram’s structure.']}],
    studyTips:[{title:'Use two colors mentally',summary:'Every intersection of a transversal with parallel lines creates one acute family and one obtuse family.',items:['All acute angles share one measure.','All obtuse angles share the supplement.','You only need to find one member of each family.']}],
    adaptiveDemo:{title:'Pick the governing fact',prompt:'Two marked parallel lines are cut by a transversal. A pair lies between the lines on opposite sides of the transversal.',options:[{id:'alternate',label:'Alternate interior',result:'The angles are equal.',advice:'Opposite sides plus interior location identifies alternate-interior angles.'},{id:'same',label:'Same-side interior',result:'That pair would lie on the same side and sum to 180.',advice:'Check which side of the transversal each angle occupies.'}]},
    quickCheck:{prompt:'Corresponding angles measure 9x minus 14 degrees and 5x plus 30 degrees. The lines are parallel. What is x?',choices:['4','9','11','22'],choiceMath:true,answer:2,explanation:'Corresponding angles are equal: nine x minus fourteen equals five x plus thirty, so four x equals forty-four and x equals eleven.'},
    practiceSet:{title:'Angle chasing from foundation to hard Module 2',intro:'Name each relationship first, then solve only the equation it creates.',questions:[
        {id:'tri-angle-vertical',difficulty:'Foundation',skill:'Vertical angles',title:'Use opposite angles',stem:'Vertical angles are 2x plus 17 degrees and 5x minus 28 degrees. Find x.',choices:['9','15','21','45'],choiceMath:true,answer:1,explanation:{steps:[{text:'Set vertical angles equal.',math:'2x+17=5x-28'},{text:'Solve.',math:'45=3x\\Rightarrow x=15'}],trap:'Vertical angles are equal.',takeaway:'Classify before calculating.'}},
        {id:'tri-angle-linear',difficulty:'Foundation',skill:'Linear pairs',title:'Complete a straight angle',stem:'One angle in a linear pair is 124 degrees. What is the other?',choices:['46°','56°','66°','236°'],answer:1,explanation:{steps:[{text:'Subtract from a straight angle.',math:'180-124=56^\\circ'}],trap:'Angles around a point use 360, but a linear pair uses 180.',takeaway:'A straight line creates supplementary angles.'}},
        {id:'tri-angle-corresponding',difficulty:'Core',skill:'Parallel lines',title:'Use a corresponding pair',stem:'Corresponding angles are 6x plus 9 degrees and 9x minus 30 degrees. Find their common measure.',choices:['13°','57°','87°','117°'],answer:2,explanation:{steps:[{text:'Set the expressions equal.',math:'6x+9=9x-30\\Rightarrow x=13'},{text:'Substitute.',math:'6(13)+9=87^\\circ'}],trap:'Thirteen is x, not the requested angle.',takeaway:'Return to the question after solving the variable.'}},
        {id:'tri-angle-converse',difficulty:'Advanced',skill:'Parallel converse',title:'Prove lines parallel numerically',stem:'For which k are alternate-interior angles 4k plus 2 degrees and 7k minus 37 degrees equal, making the lines parallel?',choices:['11','13','15','39'],choiceMath:true,answer:1,explanation:{steps:[{text:'Use the converse equality.',math:'4k+2=7k-37'},{text:'Solve.',math:'39=3k\\Rightarrow k=13'}],trap:'The equal-angle condition is what forces parallelism.',takeaway:'Angle converses can determine a parameter.'}},
        {id:'tri-angle-chain',difficulty:'Advanced',skill:'Multistep diagram',title:'Finish a hidden triangle',stem:'A triangle between parallel lines has one angle alternate-interior to a 73-degree angle and a second angle vertical to a 38-degree angle. Find the third angle.',choices:['31°','59°','69°','111°'],answer:2,explanation:{steps:[{text:'Transfer both equal measures into the triangle.',math:'73^\\circ,\\ 38^\\circ'},{text:'Use the triangle sum.',math:'180-73-38=69^\\circ'}],trap:'Do not replace either transferred angle by its supplement.',takeaway:'Chain local facts into the triangle sum.'}},
    ]},
};

const triangleTheoremsAndCongruence = {
    slug:'triangle-theorems-and-congruence',moduleId:'triangles-similarity',title:'Triangle Theorems & Congruence',eyebrow:'Geometry and Trigonometry',minutes:'38 min',
    summary:'Use angle sums, exterior angles, isosceles structure, and congruence conditions to recover missing measures without assuming a picture is to scale.',
    goals:['Apply interior and exterior angle theorems.','Use equal sides and equal opposite angles in isosceles triangles.','Identify SSS, SAS, ASA, AAS, and HL congruence.','Use congruence to transfer corresponding parts and solve parameters.'],
    facts:[{label:'Triangle sum',math:'A+B+C=180^\\circ',note:'all interior angles'},{label:'Exterior angle',math:'E=A+B',note:'sum of the two remote interior angles'},{label:'Isosceles',value:'equal sides ↔ equal base angles',note:'the relationship works both ways'},{label:'Not enough',value:'AAA or SSA',note:'does not prove general congruence'}],
    sections:[
        {heading:'Big idea 1: every triangle distributes 180 degrees',paragraphs:['Interior angles always sum to 180 degrees. An exterior angle and its adjacent interior angle form a linear pair, which produces the exterior-angle theorem.','An exterior angle equals the sum of the two nonadjacent, or remote, interior angles. This is often faster than finding the adjacent interior angle first.']},
        {heading:'Big idea 2: equal sides and equal angles point to each other',paragraphs:['In an isosceles triangle, the angles opposite equal sides are equal. Conversely, equal angles imply their opposite sides are equal.','An equilateral triangle has three 60-degree angles. Do not assume isosceles or equilateral status without tick marks, equal measures, or a stated condition.']},
        {heading:'Big idea 3: congruence means same size and shape',paragraphs:['SSS, SAS, ASA, AAS, and right-triangle HL give enough information for congruence. The letter order tells which vertices correspond.','AAA proves only similarity, because one triangle could be a scaled copy. SSA is generally ambiguous and is not a standard congruence condition.']},
        {heading:'Big idea 4: CPCTC is the payoff',paragraphs:['Once triangles are congruent, corresponding sides and angles are equal. SAT questions may hide a desired segment behind a congruence argument or ask which additional fact is sufficient.','Match vertices carefully from the congruence statement before equating expressions.']},
    ],
    formulas:[
        {label:'Triangle angle sum',math:'m\\angle A+m\\angle B+m\\angle C=180^\\circ',note:'Works for every Euclidean triangle.',meaning:'A triangle’s three turns fill a straight angle.',useWhen:'Two angles or algebraic expressions determine a third.'},
        {label:'Exterior-angle theorem',math:'m\\angle E=m\\angle A+m\\angle B',note:'A and B are the nonadjacent interior angles.',meaning:'The exterior turn equals the combined remote turns.',useWhen:'An outside angle and remote interior angles appear.'},
        {label:'Polygon interior sum',math:'S=(n-2)180^\\circ',note:'Triangulate an n-sided polygon from one vertex.',meaning:'An n-gon contains n minus two triangles.',useWhen:'A triangle question is embedded in a polygon or asks for a regular polygon angle.'},
        {label:'Congruence toolkit',math:'\\text{SSS, SAS, ASA, AAS, HL}',note:'HL requires right triangles.',meaning:'Each condition fixes both shape and scale.',useWhen:'Determining whether two triangles must be congruent.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Use an exterior angle',prompt:'An exterior angle is 133 degrees. One remote interior angle is 58 degrees. Find the other.',math:'133=58+x',steps:[{text:'Subtract.',math:'x=75^\\circ'}],insight:'The adjacent interior angle is unnecessary.',trap:'Remote interior angles add to the exterior angle, not 180.'},
        {level:'Core SAT',title:'Use isosceles structure',prompt:'In an isosceles triangle, the vertex angle is 38 degrees. Find each base angle.',math:'38+2x=180',steps:[{text:'The base angles are equal.'},{text:'Solve.',math:'2x=142\\Rightarrow x=71^\\circ'}],insight:'Equal sides create equal opposite angles.',trap:'The vertex angle is the angle between the equal sides.'},
        {level:'Advanced',title:'Transfer a congruent side',prompt:'Triangles ABC and DEF are congruent in that order. AB equals 4x minus 1 and DE equals 2x plus 9. Find BC if EF equals 17.',math:'AB=DE',steps:[{text:'Use the order A↔D, B↔E, C↔F.'},{text:'Solve the corresponding-side equation.',math:'4x-1=2x+9\\Rightarrow x=5'},{text:'Transfer BC to EF.',math:'BC=17'}],insight:'The requested side may not require the parameter after correspondence is known.',trap:'Do not pair BC with DE; follow vertex order.'},
    ],
    strategyCards:[{title:'For angle measures',items:['Choose triangle sum or exterior-angle theorem.','Use equal base angles when sides are marked equal.','Substitute back if x is not the target.']},{title:'For congruence',items:['Mark shared sides and vertical angles.','Look for a complete condition such as SAS.','Reject AAA and general SSA.']},{title:'For corresponding parts',items:['Write the vertex matching.','Pair sides between matching vertices.','Equate only corresponding expressions.']}],
    studyTips:[{title:'Read tick marks literally',summary:'Matching ticks and arcs are given data.',items:['One-tick sides match one-tick sides.','Angle arcs identify equal angles.','A square marks exactly 90 degrees.']}],
    adaptiveDemo:{title:'Is the information sufficient?',prompt:'Two triangles have two equal sides and the included angle equal.',options:[{id:'sas',label:'Yes—SAS',result:'The triangles must be congruent.',advice:'Included means the angle lies between the two known sides.'},{id:'ssa',label:'No—SSA',result:'That would apply if the known angle were not between the sides.',advice:'Locate the angle relative to the known sides.'}]},
    quickCheck:{prompt:'An isosceles triangle has base angles of 4x plus 6 degrees and a vertex angle of 16x degrees. What is x?',choices:['7','8','9','12'],choiceMath:true,answer:0,explanation:'The two base angles are equal, so two times the quantity four x plus six plus sixteen x equals 180. Thus twenty-four x plus twelve equals 180 and x equals seven.'},
    practiceSet:{title:'Triangle theorems and congruence',intro:'Use stated structure, not visual guesses.',questions:[
        {id:'tri-thm-sum',difficulty:'Foundation',skill:'Triangle sum',title:'Find the third angle',stem:'Two angles are 42 degrees and 67 degrees. Find the third.',choices:['61°','71°','81°','109°'],answer:1,explanation:{steps:[{text:'Subtract both from 180.',math:'180-42-67=71^\\circ'}],trap:'All three interior angles sum to 180.',takeaway:'Triangle sum is the first check.'}},
        {id:'tri-thm-exterior',difficulty:'Foundation',skill:'Exterior angle',title:'Use remote interiors',stem:'An exterior angle is 145 degrees and one remote interior angle is 62 degrees. Find the other.',choices:['73°','83°','97°','117°'],answer:1,explanation:{steps:[{text:'Subtract the known remote angle.',math:'145-62=83^\\circ'}],trap:'The remote angles sum to the exterior angle.',takeaway:'Avoid an unnecessary adjacent-angle step.'}},
        {id:'tri-thm-iso',difficulty:'Core',skill:'Isosceles triangles',title:'Solve equal base angles',stem:'The vertex angle is twice either base angle. Find the vertex angle.',choices:['45°','60°','90°','120°'],answer:2,explanation:{steps:[{text:'Let each base angle be x.',math:'x+x+2x=180'},{text:'Solve and find the vertex.',math:'x=45\\Rightarrow2x=90^\\circ'}],trap:'The question asks for the doubled angle.',takeaway:'Use one variable for equal angles.'}},
        {id:'tri-thm-condition',difficulty:'Core',skill:'Congruence',title:'Choose sufficient information',stem:'Which condition does not guarantee triangle congruence?',choices:['SSS','SAS','AAA','AAS'],answer:2,explanation:{steps:[{text:'AAA fixes shape but not size.'}],trap:'Similar triangles can satisfy AAA at different scales.',takeaway:'Congruence must fix scale.'}},
        {id:'tri-thm-parameter',difficulty:'Advanced',skill:'CPCTC',title:'Match corresponding angles',stem:'Triangle ABC is congruent to triangle DEF. Angle A is 7x minus 5 degrees and angle D is 4x plus 31 degrees. Find angle A.',choices:['12°','43°','79°','115°'],answer:2,explanation:{steps:[{text:'A corresponds to D.',math:'7x-5=4x+31\\Rightarrow x=12'},{text:'Evaluate.',math:'7(12)-5=79^\\circ'}],trap:'Twelve is the parameter, not the angle.',takeaway:'Congruence makes corresponding measures equal.'}},
    ]},
};

const triangleSimilarityAndScaleFactors = {
    slug:'triangle-similarity-and-scale-factors',moduleId:'triangles-similarity',title:'Similarity & Scale Factors',eyebrow:'Geometry and Trigonometry',minutes:'40 min',
    summary:'Use angle matching and one consistent scale factor to solve proportional sides, indirect measurement, perimeter, and area questions.',
    goals:['Prove similarity using AA, SAS similarity, or SSS similarity.','Match corresponding vertices and sides.','Apply one scale factor to lengths and perimeter.','Square the scale factor for area and reverse ratios accurately.'],
    facts:[{label:'AA similarity',value:'two angle pairs',note:'the third pair then matches automatically'},{label:'Length scale',math:'k',note:'all corresponding lengths and perimeters'},{label:'Area scale',math:'k^2',note:'square units'},{label:'Congruent',math:'k=1',note:'a special case of similarity'}],
    sections:[
        {heading:'Big idea 1: similar triangles preserve shape, not necessarily size',paragraphs:['Corresponding angles are equal and corresponding side lengths share one constant ratio. AA is the most common SAT route to establish similarity.','SAS similarity uses proportional pairs around an equal included angle; SSS similarity uses three proportional side pairs.']},
        {heading:'Big idea 2: vertex order prevents reversed proportions',paragraphs:['If triangle ABC is similar to triangle DEF, then A matches D, B matches E, and C matches F. Therefore AB matches DE, BC matches EF, and AC matches DF.','Write both ratios in the same direction. Mixing small-to-large with large-to-small creates a false proportion.']},
        {heading:'Big idea 3: scale factors change dimensions by powers',paragraphs:['Every length and the perimeter scale by k. Area scales by k squared because it multiplies two lengths. For solids, volume later scales by k cubed.','If the area ratio is known, take a square root to recover the length ratio.']},
        {heading:'Big idea 4: parallel segments create hidden similar triangles',paragraphs:['A segment parallel to one side of a triangle creates a smaller triangle similar to the whole triangle. Shared vertex angles and corresponding angles from parallel lines give AA.','Use whole side lengths consistently; a labeled leftover segment may need to be added to another segment before forming the large-triangle ratio.']},
    ],
    formulas:[
        {label:'Corresponding-side ratio',math:'\\frac{AB}{DE}=\\frac{BC}{EF}=\\frac{AC}{DF}=k',note:'Keep one triangle in every numerator.',meaning:'One multiplier carries every length from one triangle to the other.',useWhen:'Triangles are known or shown to be similar.'},
        {label:'Perimeter ratio',math:'\\frac{P_2}{P_1}=k',note:'Perimeter is a length sum.',meaning:'Scaling every side by k scales their total by k.',useWhen:'A perimeter and a side scale are connected.'},
        {label:'Area ratio',math:'\\frac{A_2}{A_1}=k^2',note:'Take a square root to move from area ratio to side ratio.',meaning:'Area uses two linear dimensions.',useWhen:'Similar figures have areas or shaded regions compared.'},
        {label:'Geometric mean in a right triangle',math:'h^2=pq',note:'An altitude to the hypotenuse creates three similar triangles.',meaning:'The altitude is the geometric mean of the two hypotenuse segments.',useWhen:'A hard right-triangle diagram gives an altitude to the hypotenuse.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find a missing corresponding side',prompt:'Two similar triangles have small-to-large scale factor 3/5. A small side is 12. Find its matching large side.',math:'\\frac{12}{x}=\\frac35',steps:[{text:'Cross-multiply.',math:'3x=60\\Rightarrow x=20'}],insight:'A large-triangle side should exceed its small match.',trap:'Keep ratio direction consistent.'},
        {level:'Core SAT',title:'Move from area to perimeter',prompt:'Two similar triangles have areas 49 and 121. Find the ratio of their perimeters, smaller to larger.',math:'\\sqrt{\\frac{49}{121}}',steps:[{text:'Area ratio is the square of the length ratio.'},{text:'Take the positive square root.',math:'\\frac{P_s}{P_l}=\\frac7{11}'}],insight:'Perimeter follows the linear scale, not the area scale.',trap:'Forty-nine to one hundred twenty-one is the area ratio.'},
        {level:'Advanced',title:'Use a parallel segment inside a triangle',prompt:'In triangle ABC, DE is parallel to BC, D lies on AB, and E lies on AC. If AD equals 6, DB equals 4, and AE equals 9, find AC.',math:'\\frac{AD}{AB}=\\frac{AE}{AC}',steps:[{text:'Find the whole side.',math:'AB=6+4=10'},{text:'Use similar triangles ADE and ABC.',math:'\\frac6{10}=\\frac9{AC}'},{text:'Solve.',math:'AC=15'}],insight:'The large-triangle side is the sum of its labeled pieces.',trap:'Do not compare AD with DB; they are pieces of the same side.'},
    ],
    strategyCards:[{title:'Match first',items:['Write the vertex correspondence.','Pair sides opposite matching angles.','Choose one direction for every ratio.']},{title:'Choose the right power',items:['Lengths and perimeter: k.','Area: k squared.','Reverse area scale with a square root.']},{title:'Spot hidden similarity',items:['Parallel segment inside a triangle.','Altitude to a right-triangle hypotenuse.','Shared angle plus another equal angle.']}],
    studyTips:[{title:'Write small over large',summary:'A fixed direction makes magnitude a built-in error check.',items:['Small-to-large length ratios are below one.','Small-to-large area ratios are even smaller.','Whole sides must include all their pieces.']}],
    adaptiveDemo:{title:'Choose the scale',prompt:'A triangle’s side lengths double. What happens to its area?',options:[{id:'square',label:'Multiplies by 4',result:'Correct: area scales by two squared.',advice:'Two independent dimensions each double.'},{id:'linear',label:'Multiplies by 2',result:'That is the side and perimeter scale.',advice:'Area requires the square of the length factor.'}]},
    quickCheck:{prompt:'Similar triangles have an area ratio of 25 to 81. What is the corresponding side ratio?',choices:['5:9','25:81','50:162','625:6561'],answer:0,explanation:'Take the positive square root of each area-ratio term: the length ratio is five to nine.'},
    practiceSet:{title:'Similarity and scale factors',intro:'Match vertices and decide whether the target uses k or k squared.',questions:[
        {id:'tri-sim-aa',difficulty:'Foundation',skill:'AA similarity',title:'Identify a proof',stem:'Two triangles have two pairs of equal angles. Which conclusion is guaranteed?',choices:['They are congruent.','They are similar.','They have equal areas.','They have equal perimeters.'],answer:1,explanation:{steps:[{text:'Two matching angle pairs establish AA similarity.'}],trap:'Similarity does not require equal size.',takeaway:'AA fixes shape.'}},
        {id:'tri-sim-side',difficulty:'Foundation',skill:'Proportions',title:'Scale a side',stem:'The scale factor from triangle A to triangle B is 1.5. A corresponding side in A is 8. Find the side in B.',choices:['5.33','8','9.5','12'],choiceMath:true,answer:3,explanation:{steps:[{text:'Multiply by the scale factor.',math:'8(1.5)=12'}],trap:'The direction is A to B.',takeaway:'A directed scale factor is a multiplier.'}},
        {id:'tri-sim-perim',difficulty:'Core',skill:'Perimeter scale',title:'Scale a perimeter',stem:'A small triangle has perimeter 28 and the large-to-small side ratio is 9 to 4. Find the large perimeter.',choices:['56','63','84','126'],choiceMath:true,answer:1,explanation:{steps:[{text:'Perimeter uses the linear scale.',math:'28\\left(\\frac94\\right)=63'}],trap:'Do not square the scale for perimeter.',takeaway:'Perimeter is linear.'}},
        {id:'tri-sim-area',difficulty:'Core',skill:'Area scale',title:'Scale an area',stem:'Corresponding sides have ratio 3 to 7. If the small area is 45, what is the large area?',choices:['105','175','245','735'],choiceMath:true,answer:2,explanation:{steps:[{text:'Use the squared scale.',math:'45\\left(\\frac73\\right)^2=45\\cdot\\frac{49}{9}=245'}],trap:'Multiplying by seven thirds gives a length-scaled result.',takeaway:'Area scale is k squared.'}},
        {id:'tri-sim-altitude',difficulty:'Advanced',skill:'Right-triangle similarity',title:'Use a geometric mean',stem:'An altitude to a right triangle’s hypotenuse divides the hypotenuse into segments 4 and 9. Find the altitude.',choices:['6','6.5','13','36'],choiceMath:true,answer:0,explanation:{steps:[{text:'Use the altitude geometric mean.',math:'h^2=4(9)=36'},{text:'Take the positive root.',math:'h=6'}],trap:'A length is positive and equals the square root of the product.',takeaway:'The altitude creates similar triangles.'}},
    ]},
};

const pythagoreanAndSpecialRightTriangles = {
    slug:'pythagorean-and-special-right-triangles',moduleId:'triangles-similarity',title:'Pythagorean & Special Right Triangles',eyebrow:'Geometry and Trigonometry',minutes:'42 min',
    summary:'Recognize right-triangle structure quickly, use special ratios exactly, and handle diagonals, coordinates, and parameterized sides.',
    goals:['Apply the Pythagorean theorem and its converse.','Recognize common triples and scaled versions.','Use 45-45-90 and 30-60-90 ratios.','Build hidden right triangles in rectangles, coordinates, and composite figures.'],
    facts:[{label:'Pythagorean',math:'a^2+b^2=c^2',note:'c is opposite the right angle'},{label:'45-45-90',math:'x:x:x\\sqrt2',note:'legs, then hypotenuse'},{label:'30-60-90',math:'x:x\\sqrt3:2x',note:'short leg, long leg, hypotenuse'},{label:'Common triples',value:'3-4-5, 5-12-13, 8-15-17',note:'and scaled copies'}],
    sections:[
        {heading:'Big idea 1: identify the hypotenuse before substituting',paragraphs:['The hypotenuse lies opposite the 90-degree angle and is the longest side. It is always the isolated c squared term in the standard theorem.','When finding a missing leg, subtract the known leg square from the hypotenuse square.']},
        {heading:'Big idea 2: triples save arithmetic but do not replace reasoning',paragraphs:['Common triples and their multiples can turn a square-root calculation into recognition. A 6-8-10 triangle is a doubled 3-4-5 triangle.','If the sides do not match a triple, leave exact radicals unless the question asks for a decimal.']},
        {heading:'Big idea 3: special angle measures create fixed ratios',paragraphs:['An isosceles right triangle is 45-45-90. An equilateral triangle split by an altitude produces two 30-60-90 triangles.','Match the given side to its role before applying the ratio. The side opposite 30 degrees is always the short leg.']},
        {heading:'Big idea 4: many SAT shapes hide right triangles',paragraphs:['A rectangle diagonal, coordinate distance, radius to a tangent, altitude, and half-diagonal of a square all create right-triangle structure. Draw or mark the triangle before choosing a formula.','Hard questions may combine a special ratio with area, similarity, or an algebraic expression.']},
    ],
    formulas:[
        {label:'Pythagorean theorem',math:'a^2+b^2=c^2',note:'Use only for right triangles.',meaning:'The sum of the leg-square areas equals the hypotenuse-square area.',useWhen:'Two sides of a right triangle determine the third.'},
        {label:'Converse',math:'a^2+b^2=c^2\\Rightarrow\\text{right triangle}',note:'Test the largest side as c.',meaning:'The side relationship can prove the included angle is right.',useWhen:'Given three sides and asked to classify the triangle.'},
        {label:'45-45-90 ratio',math:'\\text{hypotenuse}=\\text{leg}\\sqrt2',note:'The two legs are equal.',meaning:'The diagonal of a square creates this triangle.',useWhen:'A right triangle has a 45-degree angle or equal legs.'},
        {label:'30-60-90 ratio',math:'s:\\ell:h=1:\\sqrt3:2',note:'s is opposite 30 degrees.',meaning:'The longer leg is square root three times the short leg.',useWhen:'A right triangle has a 30- or 60-degree angle.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find a missing leg',prompt:'A right triangle has hypotenuse 13 and one leg 5. Find the other leg.',math:'5^2+b^2=13^2',steps:[{text:'Subtract squares.',math:'b^2=169-25=144'},{text:'Take the positive root.',math:'b=12'}],insight:'This is the 5-12-13 triple.',trap:'Thirteen must be the hypotenuse because it is longest.'},
        {level:'Core SAT',title:'Find a square diagonal',prompt:'A square has side length 7. Find its diagonal.',math:'d=7\\sqrt2',steps:[{text:'The diagonal creates a 45-45-90 triangle.'},{text:'Multiply a leg by square root two.'}],insight:'Exact radical form is usually preferred.',trap:'The diagonal is not fourteen; that would add rather than combine perpendicular lengths.'},
        {level:'Advanced',title:'Combine an equilateral altitude with area',prompt:'An equilateral triangle has side 12. Find its area.',math:'h=6\\sqrt3',steps:[{text:'The altitude bisects the base into two segments of 6.'},{text:'Use the 30-60-90 ratio.',math:'h=6\\sqrt3'},{text:'Compute area.',math:'A=\\frac12(12)(6\\sqrt3)=36\\sqrt3'}],insight:'The altitude creates two special right triangles.',trap:'The side length 12 is the hypotenuse of each half-triangle.'},
    ],
    strategyCards:[{title:'Before calculating',items:['Mark the right angle.','Circle the hypotenuse.','Name each special-triangle side by its opposite angle.']},{title:'Keep exact values',items:['Simplify radicals.','Use decimal approximations only when requested.','Compare answer forms before typing.']},{title:'Find hidden triangles',items:['Draw rectangle or square diagonals.','Connect circle centers to tangent points.','Drop an altitude in symmetric figures.']}],
    studyTips:[{title:'Memorize ratios as roles',summary:'Names are safer than a bare sequence.',items:['Short leg is opposite 30 degrees.','Long leg is opposite 60 degrees.','Hypotenuse is opposite 90 degrees.']}],
    adaptiveDemo:{title:'Choose the shortcut',prompt:'A right triangle has equal legs of 9.',options:[{id:'special',label:'45-45-90',result:'The hypotenuse is nine square root two.',advice:'Equal legs force equal acute angles of 45 degrees.'},{id:'thirty',label:'30-60-90',result:'That triangle has unequal legs.',advice:'Look for a 30-degree angle or an equilateral split.'}]},
    quickCheck:{prompt:'In a 30-60-90 triangle, the hypotenuse is 18. What is the longer leg?',choices:['9','9√2','9√3','18√3'],answer:2,explanation:'The short leg is half the hypotenuse, or nine, and the longer leg is nine square root three.'},
    practiceSet:{title:'Right triangles from foundation to hard Module 2',intro:'Identify side roles before choosing the theorem or ratio.',questions:[
        {id:'tri-right-basic',difficulty:'Foundation',skill:'Pythagorean theorem',title:'Find a hypotenuse',stem:'A right triangle has legs 9 and 12. Find the hypotenuse.',choices:['15','18','21','225'],choiceMath:true,answer:0,explanation:{steps:[{text:'Add leg squares.',math:'c^2=81+144=225'},{text:'Take the positive root.',math:'c=15'}],trap:'The theorem uses squares, but the answer is a length.',takeaway:'Nine-twelve-fifteen scales three-four-five.'}},
        {id:'tri-right-converse',difficulty:'Core',skill:'Converse',title:'Classify side lengths',stem:'Which side set forms a right triangle?',choices:['4, 5, 6','6, 8, 10','7, 8, 9','8, 10, 13'],answer:1,explanation:{steps:[{text:'Test the largest side.',math:'6^2+8^2=36+64=100=10^2'}],trap:'Only the exact square equality proves a right triangle.',takeaway:'Use the largest side as c.'}},
        {id:'tri-right-45',difficulty:'Core',skill:'45-45-90',title:'Reverse from hypotenuse',stem:'A square diagonal is 10. Find its side.',choices:['5','5√2','10√2','20'],answer:1,explanation:{steps:[{text:'Divide the hypotenuse by square root two.',math:'s=10/\\sqrt2=5\\sqrt2'}],trap:'Rationalize or recognize the equivalent exact form.',takeaway:'Leg equals hypotenuse over square root two.'}},
        {id:'tri-right-30',difficulty:'Core',skill:'30-60-90',title:'Use the long leg',stem:'The longer leg is 7√3. Find the hypotenuse.',choices:['7','14','14√3','21'],answer:1,explanation:{steps:[{text:'The long leg is short leg times square root three.',math:'s=7'},{text:'Double the short leg.',math:'h=14'}],trap:'Identify the given side role before multiplying.',takeaway:'The ratio is one, square root three, two.'}},
        {id:'tri-right-param',difficulty:'Advanced',skill:'Parameters',title:'Force a right triangle',stem:'A right triangle has legs x and x plus 7 and hypotenuse 17. What is x?',choices:['7','8','9','10'],choiceMath:true,answer:1,explanation:{steps:[{text:'Build the theorem.',math:'x^2+(x+7)^2=289'},{text:'Simplify.',math:'2x^2+14x-240=0'},{text:'Factor and keep the positive root.',math:'(x-8)(x+15)=0\\Rightarrow x=8'}],trap:'A side length cannot be negative.',takeaway:'Geometry can create a quadratic with a contextual root.'}},
    ]},
};

const triangleInequalityAndAdvancedSetups = {
    slug:'triangle-inequality-and-advanced-setups',moduleId:'triangles-similarity',title:'Triangle Inequality & Advanced Setups',eyebrow:'Geometry and Trigonometry',minutes:'35 min',
    summary:'Decide which triangles can exist, compare sides and angles, and break unfamiliar diagrams into familiar SAT relationships.',
    goals:['Apply the triangle inequality to ranges and integer counts.','Compare side lengths using opposite angle measures.','Use the hinge idea for two triangles with matching side pairs.','Decompose advanced diagrams and filter algebraic answers through geometric constraints.'],
    facts:[{label:'Third-side range',math:'|a-b|<x<a+b',note:'strict inequalities'},{label:'Largest side',value:'opposite largest angle',note:'and conversely'},{label:'Positive lengths',math:'s>0',note:'always enforce context'},{label:'Degenerate case',math:'a+b=c',note:'forms a line, not a triangle'}],
    sections:[
        {heading:'Big idea 1: any two sides must exceed the third',paragraphs:['The most useful form for an unknown third side is absolute difference less than x less than sum. Both endpoints are excluded because equality collapses the triangle into a straight segment.','For integer-length questions, list only integers strictly inside the interval.']},
        {heading:'Big idea 2: side order matches opposite-angle order',paragraphs:['The longest side faces the largest angle; equal sides face equal angles. This lets you rank lengths without calculating them.','The converse works too: longer side information ranks the opposite angles.']},
        {heading:'Big idea 3: geometry restricts algebra',paragraphs:['A parameter solution may produce a negative side, an angle outside zero to 180, or a degenerate triangle. Such values are algebraic candidates, not valid geometric answers.','Write the geometric domain before solving when possible.']},
        {heading:'Big idea 4: decompose hard figures',paragraphs:['Add an auxiliary radius, altitude, diagonal, or shared side to expose right triangles, similar triangles, or angle sums. The SAT rarely requires a theorem far beyond its official list; difficulty comes from hiding familiar structure.','Work from stated facts and labels, since figures may not be drawn to scale.']},
    ],
    formulas:[
        {label:'Third-side interval',math:'|a-b|<x<a+b',note:'Neither endpoint is included.',meaning:'Two sides must connect rather than fall short or flatten into a line.',useWhen:'Two side lengths are known and the third is constrained.'},
        {label:'Integer count',math:'\\#\\{x\\in\\mathbb Z:|a-b|<x<a+b\\}',note:'List or count strict interior integers.',meaning:'Only whole-number lengths inside the existence interval work.',useWhen:'Asked how many integer values are possible.'},
        {label:'Side-angle order',math:'a>b\\Longleftrightarrow A>B',note:'Each side is paired with its opposite angle.',meaning:'Larger angles open to longer opposite sides.',useWhen:'Ranking sides or angles without full measurements.'},
        {label:'Hinge comparison',math:'a,b\\text{ fixed and }C_1>C_2\\Rightarrow c_1>c_2',note:'The included angle lies between the fixed sides.',meaning:'Opening the hinge wider increases the opposite side.',useWhen:'Two triangles share two corresponding side lengths.'},
    ],
    workedExamples:[
        {level:'Foundation',title:'Find a third-side range',prompt:'Two sides are 8 and 13. Find the possible range for x.',math:'|13-8|<x<13+8',steps:[{text:'Compute the bounds.',math:'5<x<21'}],insight:'Five and twenty-one are excluded.',trap:'A difference of five creates a flat segment, not a triangle.'},
        {level:'Core SAT',title:'Count integer lengths',prompt:'Sides 7 and 11 are joined by an integer third side. How many values are possible?',math:'4<x<18',steps:[{text:'List integers five through seventeen.'},{text:'Count inclusively.',math:'17-5+1=13'}],insight:'Strict bounds shift both endpoints inward.',trap:'Do not count four or eighteen.'},
        {level:'Advanced',title:'Filter a parameter solution',prompt:'A triangle has sides x plus 2, x plus 5, and 15. Find the least integer x that makes a triangle.',math:'(x+2)+(x+5)>15',steps:[{text:'The two variable sides are the only pair that may fail for relevant positive x.',math:'2x+7>15\\Rightarrow x>4'},{text:'Enforce integer and positive sides.',math:'x_{min}=5'}],insight:'The strongest inequality determines the lower bound here.',trap:'x equals four gives equality and a degenerate triangle.'},
    ],
    strategyCards:[{title:'For possible sides',items:['Write difference less than x less than sum.','Keep inequalities strict.','Apply integer or positivity conditions last.']},{title:'For rankings',items:['Pair each side with its opposite angle.','Largest faces largest.','Equal faces equal.']},{title:'For hard diagrams',items:['Add a radius, altitude, or diagonal.','Search for a shared side or parallel line.','Use only stated markings, never visual scale.']}],
    studyTips:[{title:'Test the smallest two sides',summary:'For three known positive lengths, the only necessary check is whether the two smaller sides sum to more than the largest.',items:['Sort the sides.','Add the smaller two.','Equality is not enough.']}],
    adaptiveDemo:{title:'Can the triangle exist?',prompt:'Side lengths are 4, 7, and 11.',options:[{id:'no',label:'No',result:'Correct: four plus seven equals eleven, so the figure is degenerate.',advice:'Triangle inequality must be strict.'},{id:'yes',label:'Yes',result:'Equality creates a straight segment.',advice:'Require the smaller sides to sum to more than the largest.'}]},
    quickCheck:{prompt:'Two sides are 6 and 14. Which could be the third side?',choices:['8','9','20','21'],choiceMath:true,answer:1,explanation:'The third side must be strictly between fourteen minus six equals eight and fourteen plus six equals twenty. Only nine qualifies.'},
    practiceSet:{title:'Triangle constraints and advanced setups',intro:'Let geometry filter every algebraic candidate.',questions:[
        {id:'tri-ineq-possible',difficulty:'Foundation',skill:'Existence',title:'Choose a valid side set',stem:'Which lengths form a triangle?',choices:['2, 3, 5','3, 4, 8','5, 7, 10','6, 6, 12'],answer:2,explanation:{steps:[{text:'Check the two smaller sides.',math:'5+7>10'}],trap:'Equality is degenerate.',takeaway:'The smaller two must exceed the largest.'}},
        {id:'tri-ineq-range',difficulty:'Foundation',skill:'Range',title:'Bound a third side',stem:'Two sides are 10 and 16. Which interval contains every possible third side x?',choices:['6≤x≤26','6<x<26','10<x<16','16<x<26'],answer:1,explanation:{steps:[{text:'Use difference and sum.',math:'|16-10|<x<16+10'}],trap:'Both endpoints are excluded.',takeaway:'Use strict bounds.'}},
        {id:'tri-ineq-order',difficulty:'Core',skill:'Side-angle order',title:'Rank an opposite side',stem:'In triangle ABC, angle A is 80 degrees, angle B is 65 degrees, and angle C is 35 degrees. Which side is longest?',choices:['AB','AC','BC','Cannot determine'],answer:2,explanation:{steps:[{text:'The largest angle is A.'},{text:'The side opposite A is BC.'}],trap:'Do not choose a side adjacent to the largest angle.',takeaway:'Largest side faces largest angle.'}},
        {id:'tri-ineq-count',difficulty:'Core',skill:'Integer count',title:'Count possible integers',stem:'Sides are 9, 15, and integer x. How many x-values are possible?',choices:['16','17','18','23'],choiceMath:true,answer:1,explanation:{steps:[{text:'Find the interval.',math:'6<x<24'},{text:'Count seven through twenty-three.',math:'23-7+1=17'}],trap:'Six and twenty-four are excluded.',takeaway:'Count strict interior integers.'}},
        {id:'tri-ineq-param',difficulty:'Advanced',skill:'Parameters',title:'Find the least integer parameter',stem:'Sides are 2x, x plus 3, and 12, where x is a positive integer. What is the least possible x?',choices:['3','4','5','6'],choiceMath:true,answer:1,explanation:{steps:[{text:'The strongest lower-bound condition is.',math:'2x+(x+3)>12\\Rightarrow3x>9\\Rightarrow x>3'},{text:'Choose the least positive integer.',math:'x=4'}],trap:'At x equals three, the two smaller sides sum exactly to twelve.',takeaway:'Apply strict inequality before the integer condition.'}},
    ]},
};

export const TRIANGLES_LESSONS = [
    parallelLinesAndAngleChasing,
    triangleTheoremsAndCongruence,
    triangleSimilarityAndScaleFactors,
    pythagoreanAndSpecialRightTriangles,
    triangleInequalityAndAdvancedSetups,
];
