import {
    BookOpenText,
    CheckSquare2,
    Compass,
    ListChecks,
    MessageSquareText,
    Search,
    Target,
} from 'lucide-react';

export const ENGLISH_STUDY_GUIDE_MODULES = [
    {
        id: 'english-reading-method',
        domain: 'Foundations',
        title: 'The SAT Reading Method',
        summary: 'Build the decision process that powers every Reading and Writing question, from reading the task to learning from a miss.',
        icon: Compass,
        accent: 'bg-primary-100 text-primary-700',
        time: '2 hr 15 min',
        pages: [
            {
                title: 'The Digital SAT English Map',
                slug: 'digital-sat-english-map',
                focus: 'Format, domain order, adaptation, and pacing',
            },
            {
                title: 'Read the Task Before the Text',
                slug: 'read-the-task-before-the-text',
                focus: 'Turn recurring question stems into a precise job',
            },
            {
                title: 'The Textual Contract',
                slug: 'the-textual-contract',
                focus: 'Demand evidence and match scope, strength, and logic',
            },
            {
                title: 'Predict Before You Pick',
                slug: 'predict-before-you-pick',
                focus: 'Build a plain-language target before choices create noise',
            },
            {
                title: 'Distractor Anatomy',
                slug: 'distractor-anatomy',
                focus: 'Recognize the five wrong-answer patterns',
            },
            {
                title: 'Review That Raises Your Score',
                slug: 'review-that-raises-your-score',
                focus: 'Diagnose the failed decision and write a transfer rule',
            },
        ],
    },
    {
        id: 'craft-and-structure',
        domain: 'Craft and Structure · ≈28%',
        title: 'Words, Purpose & Structure',
        summary: 'Use context to choose precise language, explain what a sentence does, and connect authors without flattening their differences.',
        icon: BookOpenText,
        accent: 'bg-cyan-100 text-cyan-700',
        comingSoon: true,
        pages: [
            {title: 'Vocabulary by Context and Prediction', focus: 'Use logic before definitions'},
            {title: 'Precision, Connotation, and Register', focus: 'Separate near-synonyms by exact fit'},
            {title: 'Sentence Function', focus: 'Name the role, not merely the topic'},
            {title: 'Main Purpose and Text Structure', focus: 'Track the passage-wide plan'},
            {title: 'Cross-Text Connections', focus: 'Compare agreement, response, and evidence'},
            {title: '700+ Craft', focus: 'Qualification, concession, and subtle alignment'},
        ],
    },
    {
        id: 'information-and-ideas',
        domain: 'Information and Ideas · ≈26%',
        title: 'Ideas, Inferences & Evidence',
        summary: 'Find what a text says, infer only what it permits, and connect claims with the strongest textual or quantitative evidence.',
        icon: Search,
        accent: 'bg-emerald-100 text-emerald-700',
        comingSoon: true,
        pages: [
            {title: 'Central Ideas Without Over-Summarizing', focus: 'Keep the main claim and its essential frame'},
            {title: 'Details and Accurate Paraphrase', focus: 'Match meaning without copying words'},
            {title: 'Inferences: What Must Be True', focus: 'Use constraints instead of possibility'},
            {title: 'Literary Inference and Character', focus: 'Read action, attitude, and figurative language'},
            {title: 'Textual Evidence', focus: 'Support or challenge a claim'},
            {title: 'Quantitative Evidence', focus: 'Read tables and graphs as arguments'},
            {title: '700+ Evidence', focus: 'Experiments, competing claims, and multiple results'},
        ],
    },
    {
        id: 'sentence-boundaries',
        domain: 'Standard English Conventions · ≈26%',
        title: 'Sentence Boundaries',
        summary: 'See the sentence core first, then use punctuation to join, separate, or embed ideas with control.',
        icon: ListChecks,
        accent: 'bg-amber-100 text-amber-700',
        comingSoon: true,
        pages: [
            {title: 'Find the Sentence Core', focus: 'Clauses and complete thoughts'},
            {title: 'Periods and Semicolons', focus: 'Separate independent clauses'},
            {title: 'Commas and Coordinating Conjunctions', focus: 'Join complete thoughts correctly'},
            {title: 'Colons and Dashes', focus: 'Introduce and emphasize elaboration'},
            {title: 'Essential and Nonessential Elements', focus: 'Punctuate information by function'},
            {title: '700+ Boundaries', focus: 'Long subjects, interruptions, and no-punctuation traps'},
        ],
    },
    {
        id: 'form-structure-sense',
        domain: 'Standard English Conventions · ≈26%',
        title: 'Form, Structure & Sense',
        summary: 'Control agreement, verb form, modifiers, pronouns, and parallel structure inside increasingly complex sentences.',
        icon: CheckSquare2,
        accent: 'bg-fuchsia-100 text-fuchsia-700',
        comingSoon: true,
        pages: [
            {title: 'Subject-Verb Agreement', focus: 'Find the true subject through interruptions'},
            {title: 'Verb Tense and Form', focus: 'Use chronology and sentence structure'},
            {title: 'Pronouns, Plurals, and Possessives', focus: 'Match reference and meaning'},
            {title: 'Modifiers and Logical Subjects', focus: 'Put descriptions beside what they modify'},
            {title: 'Parallelism and Comparisons', focus: 'Match grammatical and logical form'},
            {title: '700+ Grammar', focus: 'Subtle agreement in early-college-level sentences'},
        ],
    },
    {
        id: 'expression-of-ideas',
        domain: 'Expression of Ideas · ≈20%',
        title: 'Transitions & Synthesis',
        summary: 'Name logical relationships and select only the source notes that accomplish a precise rhetorical goal.',
        icon: MessageSquareText,
        accent: 'bg-sky-100 text-sky-700',
        comingSoon: true,
        pages: [
            {title: 'Relationship Before Transition', focus: 'Predict the connection before the word'},
            {title: 'Contrast, Continuation, Cause, and Example', focus: 'Master the core transition families'},
            {title: 'Concession, Clarification, and Emphasis', focus: 'Handle subtle logical relationships'},
            {title: 'Translate the Rhetorical Goal', focus: 'Turn the task into a checklist'},
            {title: 'Select Only the Needed Notes', focus: 'Control relevance and scope'},
            {title: '700+ Synthesis', focus: 'Audience, generalizations, and specific study results'},
        ],
    },
    {
        id: 'english-timed-mastery',
        domain: 'Strategy',
        title: 'Timed Mastery',
        summary: 'Combine every domain under realistic pacing, protect accuracy, and turn the final error patterns into a short study plan.',
        icon: Target,
        accent: 'bg-slate-100 text-slate-700',
        comingSoon: true,
        pages: [
            {title: 'Use the Predictable Section Order', focus: 'Plan around grouped domains'},
            {title: 'Two-Pass Triage and Pacing', focus: 'Protect solvable points first'},
            {title: 'Hard Module 2 Precision', focus: 'Choose between plausible final answers'},
            {title: 'Mixed-Domain Mini-Module', focus: 'Switch skills under the clock'},
            {title: 'Final Error Audit and 14-Day Plan', focus: 'Turn patterns into maintenance'},
        ],
    },
];

