import {
    Calculator,
    Compass,
    Flame,
    FunctionSquare,
    LineChart,
    Sigma,
    Target,
    Triangle,
} from 'lucide-react';

export const STUDY_GUIDE_MODULES = [
    {
        id: 'math-map',
        domain: 'Orientation',
        title: 'Math Map',
        summary: 'Know the section format, domain weights, and the study loop before you start grinding questions.',
        icon: Compass,
        accent: 'bg-primary-100 text-primary-700',
        time: '30 min',
        pages: [
            {
                title: 'How Digital SAT Math Works',
                slug: 'how-digital-sat-math-works',
                focus: 'Format, timing, and adaptive modules',
            },
            {title: 'The Four Math Domains', slug: 'four-math-domains', focus: 'What appears most often'},
            {title: 'How to Study With SAT Duel', slug: 'study-with-sat-duel', focus: 'Review misses, then practice targeted reps'},
        ],
    },
    {
        id: 'linear-equations',
        domain: 'Algebra',
        title: 'Linear Equations',
        summary: 'Build clean equation habits so easy Algebra questions become automatic points.',
        icon: Sigma,
        accent: 'bg-cyan-100 text-cyan-700',
        time: '1 hr 45 min',
        pages: [
            {title: 'One-Variable Equations', slug: 'one-variable-equations', focus: 'Fractions, parentheses, and signs'},
            {title: 'Linear Inequalities', slug: 'linear-inequalities', focus: 'Graph, interval, and flip rules'},
            {title: 'Equations With Parameters', slug: 'equations-with-parameters', focus: 'Constants that stand in for numbers'},
            {title: 'Word Problems to Equations', slug: 'word-problems-to-equations', focus: 'Rates, totals, and constraints'},
            {title: 'No-Solution and Infinite-Solution Cases', slug: 'no-solution-and-infinite-solution-cases', focus: 'When equations collapse'},
        ],
    },
    {
        id: 'linear-functions-systems',
        domain: 'Algebra',
        title: 'Linear Functions',
        summary: 'Connect lines, tables, systems, and word problems as the same relationship in different forms.',
        icon: LineChart,
        accent: 'bg-emerald-100 text-emerald-700',
        time: '2 hr 40 min',
        pages: [
            {title: 'Slope as Rate of Change', slug: 'slope-as-rate-of-change', focus: 'Units, steepness, and direction'},
            {title: 'Intercepts as Starting Values', slug: 'intercepts-as-starting-values', focus: 'What each intercept means'},
            {title: 'Tables to Equations', slug: 'tables-to-equations', focus: 'Constant change to linear models'},
            {title: 'Systems as Intersections', slug: 'systems-as-intersections', focus: 'Substitution, elimination, and graphs'},
            {title: 'Parallel and Perpendicular Lines', slug: 'parallel-and-perpendicular-lines', focus: 'Slope relationships in disguise'},
        ],
    },
    {
        id: 'quadratic-foundations',
        domain: 'Advanced Math',
        title: 'Quadratics I',
        summary: 'Learn what each quadratic form reveals so you stop expanding when factoring would be faster.',
        icon: FunctionSquare,
        accent: 'bg-amber-100 text-amber-700',
        time: '2 hr 50 min',
        pages: [
            {title: 'Standard, Factored, and Vertex Form', slug: 'standard-factored-and-vertex-form', focus: 'Choose the useful form first'},
            {title: 'Factoring Patterns', slug: 'factoring-patterns', focus: 'GCF, difference of squares, and trinomials'},
            {title: 'Completing the Square', slug: 'completing-the-square', focus: 'Turn standard form into vertex form'},
            {title: 'The Quadratic Formula', slug: 'the-quadratic-formula', focus: 'Use it when structure is hidden'},
            {title: 'Discriminant Meaning', slug: 'discriminant-meaning', focus: 'Number of real solutions'},
        ],
    },
    {
        id: 'quadratic-graphs',
        domain: 'Advanced Math',
        title: 'Quadratics II',
        summary: 'Read a parabola through zeros, vertex, symmetry, and context instead of memorizing graph facts.',
        icon: FunctionSquare,
        accent: 'bg-orange-100 text-orange-700',
        time: '3 hr 10 min',
        pages: [
            {title: 'Zeros, Intercepts, and Roots', slug: 'zeros-intercepts-and-roots', focus: 'Same idea, different language'},
            {title: 'Vertex and Axis of Symmetry', slug: 'vertex-and-axis-of-symmetry', focus: 'Maximum, minimum, and midpoint'},
            {title: 'Transformations of Parabolas', slug: 'transformations-of-parabolas', focus: 'Shift, stretch, and reflect'},
            {title: 'Quadratic Word Problems', slug: 'quadratic-word-problems', focus: 'Area, projectile, and revenue models'},
            {title: 'Quadratic Systems', slug: 'quadratic-systems', focus: 'Line-parabola intersections'},
        ],
    },
    {
        id: 'nonlinear-equations',
        domain: 'Advanced Math',
        title: 'Nonlinear Functions',
        summary: 'Handle absolute value, polynomial, rational, radical, and mixed systems without guessing.',
        icon: FunctionSquare,
        accent: 'bg-fuchsia-100 text-fuchsia-700',
        time: '3 hr 15 min',
        pages: [
            {title: 'Function Notation', slug: 'function-notation', focus: 'Inputs, outputs, and compositions'},
            {title: 'Absolute Value Equations', slug: 'absolute-value-equations', focus: 'Distance from zero and split cases'},
            {title: 'Polynomial Structure', slug: 'polynomial-structure', focus: 'Factors, zeros, and end behavior'},
            {title: 'Rational Equations', slug: 'rational-equations', focus: 'Restrictions and cross-multiplying'},
            {title: 'Radical Equations', slug: 'radical-equations', focus: 'Isolate, square, then check'},
        ],
    },
    {
        id: 'exponential-models',
        domain: 'Advanced Math',
        title: 'Exponents',
        summary: 'Recognize repeated multiplication, percent change, and hidden growth factors in context.',
        icon: FunctionSquare,
        accent: 'bg-lime-100 text-lime-700',
        time: '3 hr 20 min',
        pages: [
            {title: 'Growth Factors', slug: 'growth-factors', focus: 'Percent increase and decrease'},
            {title: 'Exponential Tables', slug: 'exponential-tables', focus: 'Common ratios and models'},
            {title: 'Linear vs. Exponential', slug: 'linear-vs-exponential', focus: 'Additive change vs. multiplicative change'},
            {title: 'Equivalent Exponential Forms', slug: 'equivalent-exponential-forms', focus: 'Rewrite bases and exponents'},
            {title: 'Model Interpretation', slug: 'exponential-model-interpretation', focus: 'Initial value, factor, and units'},
        ],
    },
    {
        id: 'advanced-expression-fluency',
        domain: 'Advanced Math',
        title: 'Expressions',
        summary: 'Rewrite polynomial, rational, and radical expressions into the form that reveals the feature you need.',
        icon: Sigma,
        accent: 'bg-sky-100 text-sky-700',
        time: '3 hr 20 min',
        pages: [
            {title: 'Polynomial Operations', slug: 'polynomial-operations', focus: 'Combine, distribute, and multiply with precision'},
            {title: 'Strategic Factoring', slug: 'strategic-factoring', focus: 'GCF, patterns, grouping, and hidden quadratics'},
            {title: 'Rational Expressions', slug: 'rational-expressions', focus: 'Restrictions, cancellation, and common denominators'},
            {title: 'Radicals & Rational Exponents', slug: 'radicals-and-rational-exponents', focus: 'Equivalent forms, conjugates, and real domains'},
            {title: 'Choosing the Most Useful Form', slug: 'choosing-the-most-useful-form', focus: 'Expose coefficients, zeros, extrema, and hidden structure'},
        ],
    },
    {
        id: 'ratios-percent-units',
        domain: 'Problem-Solving and Data Analysis',
        title: 'Ratios & Percents',
        summary: 'Turn word problems into ratios, unit rates, and percent relationships with the right denominator.',
        icon: Target,
        accent: 'bg-rose-100 text-rose-700',
        time: '3 hr 20 min',
        pages: [
            {title: 'Ratios & Proportional Relationships', slug: 'ratios-and-proportional-relationships', focus: 'Shares, direct variation, and ratio chains'},
            {title: 'Rates & Derived Units', slug: 'rates-and-derived-units', focus: 'Unit rates, density, work, and average speed'},
            {title: 'Unit Conversion & Scale', slug: 'unit-conversion-and-scale', focus: 'Conversion chains, dimensions, and scale drawings'},
            {title: 'Percent Relationships', slug: 'percent-relationships', focus: 'Bases, nested percents, points, and overlap'},
            {title: 'Percent Change & Multipliers', slug: 'percent-change-and-multipliers', focus: 'Successive factors, reversal, and net change'},
        ],
    },
    {
        id: 'statistics-probability',
        domain: 'Problem-Solving and Data Analysis',
        title: 'Statistics',
        summary: 'Read data displays carefully and know what a statistic can and cannot prove.',
        icon: Target,
        accent: 'bg-teal-100 text-teal-700',
        time: '3 hr 20 min',
        pages: [
            {title: 'One-Variable Data & Distributions', slug: 'one-variable-data-and-distributions', focus: 'Displays, center, quartiles, and reconstruction'},
            {title: 'Comparing Center & Spread', slug: 'comparing-center-and-spread', focus: 'Outliers, transformations, and standard deviation'},
            {title: 'Scatterplots & Models', slug: 'scatterplots-and-models', focus: 'Association, model choice, residuals, and prediction'},
            {title: 'Probability & Two-Way Tables', slug: 'probability-and-two-way-tables', focus: 'Conditional denominators, unions, and independence'},
            {title: 'Sampling, Margin of Error & Claims', slug: 'sampling-margin-of-error-and-claims', focus: 'Generalization, causation, bias, and precision'},
        ],
    },
    {
        id: 'triangles-similarity',
        domain: 'Geometry and Trigonometry',
        title: 'Triangles',
        summary: 'Use angle facts and proportional reasoning before reaching for formulas.',
        icon: Triangle,
        accent: 'bg-violet-100 text-violet-700',
        time: '3 hr 10 min',
        pages: [
            {title: 'Parallel Lines & Angle Chasing', slug: 'parallel-lines-and-angle-chasing', focus: 'Vertical, corresponding, alternate, and supplementary angles'},
            {title: 'Triangle Theorems & Congruence', slug: 'triangle-theorems-and-congruence', focus: 'Angle sums, exterior angles, isosceles facts, and congruence'},
            {title: 'Similarity & Scale Factors', slug: 'triangle-similarity-and-scale-factors', focus: 'Proportional sides, AA similarity, and area scale'},
            {title: 'Pythagorean & Special Right Triangles', slug: 'pythagorean-and-special-right-triangles', focus: 'Right-triangle structure, 30-60-90, and 45-45-90'},
            {title: 'Triangle Inequality & Advanced Setups', slug: 'triangle-inequality-and-advanced-setups', focus: 'Possible sides, hidden triangles, altitude, and parameter questions'},
        ],
    },
    {
        id: 'circles-coordinate-geometry',
        domain: 'Geometry and Trigonometry',
        title: 'Circles & Coordinates',
        summary: 'Connect circle facts to equations, distance, midpoint, and slope on the coordinate plane.',
        icon: Triangle,
        accent: 'bg-indigo-100 text-indigo-700',
        time: '3 hr 15 min',
        pages: [
            {title: 'Arcs, Central Angles & Sectors', slug: 'arcs-central-angles-and-sectors', focus: 'Fractions of a circle, radians, arc length, and sector area'},
            {title: 'Tangents, Chords & Inscribed Angles', slug: 'tangents-chords-and-inscribed-angles', focus: 'Radius-tangent right angles, intercepted arcs, and power relationships'},
            {title: 'Circumference, Area & Composite Circles', slug: 'circumference-area-and-composite-circles', focus: 'Formula choice, shaded regions, wheels, and units'},
            {title: 'Circle Equations', slug: 'circle-equations', focus: 'Center, radius, completing the square, and tangent lines'},
            {title: 'Distance, Midpoint & Coordinate Proof', slug: 'distance-midpoint-and-coordinate-proof', focus: 'Lengths, centers, collinearity, and geometric verification'},
        ],
    },
    {
        id: 'area-volume-trig',
        domain: 'Geometry and Trigonometry',
        title: 'Area, Volume & Trig',
        summary: 'Organize shape formulas and use trig as side-ratio language, not a separate mystery topic.',
        icon: Triangle,
        accent: 'bg-stone-100 text-stone-700',
        time: '3 hr 20 min',
        pages: [
            {title: 'Perimeter, Area & Composite Figures', slug: 'perimeter-area-and-composite-figures', focus: 'Polygons, circles, subtraction, and algebraic dimensions'},
            {title: 'Surface Area & Volume', slug: 'surface-area-and-volume', focus: 'Prisms, cylinders, pyramids, cones, spheres, and missing dimensions'},
            {title: 'Scale Factors & Geometry Units', slug: 'scale-factors-and-geometry-units', focus: 'Length, area, volume, density, and squared or cubed conversions'},
            {title: 'Sine, Cosine & Tangent', slug: 'sine-cosine-and-tangent', focus: 'Right-triangle ratios, complementary angles, and inverse trig'},
            {title: 'Trig in Context & the Unit Circle', slug: 'trig-in-context-and-unit-circle', focus: 'Elevation, multi-step modeling, radians, and exact values'},
        ],
    },
    {
        id: 'calculator-mixed-review',
        domain: 'Strategy',
        title: 'Calculator Strategy',
        summary: 'Use the calculator when it saves time, then practice switching topics like the real test.',
        icon: Calculator,
        accent: 'bg-slate-100 text-slate-700',
        time: '3 hr 5 min',
        pages: [
            {title: 'Graphing Systems & Intersections', slug: 'graphing-systems-and-intersections', focus: 'Zeros, intersections, tangency, and parameter sliders'},
            {title: 'Tables, Lists & Regression', slug: 'tables-lists-and-regression', focus: 'Function tables, data models, residuals, and statistics'},
            {title: 'Answer Testing & Modeling', slug: 'answer-testing-and-modeling', focus: 'Backsolving, restrictions, sliders, and visual checks'},
            {title: 'Calculator Traps & Exact Values', slug: 'calculator-traps-and-exact-values', focus: 'Window errors, rounding, degrees, syntax, and when algebra wins'},
            {title: 'Hard Module 2 Workflow', slug: 'hard-module-2-workflow', focus: 'Triage, translate, choose a method, verify, and finish'},
        ],
    },
    {
        id: 'review-system',
        domain: 'Review',
        title: 'Mistake Review',
        summary: 'Turn missed questions into a short list of fixable habits instead of vague frustration.',
        icon: Flame,
        accent: 'bg-red-100 text-red-700',
        time: '2 hr 15 min',
        pages: [
            {title: 'Diagnose Every Miss', slug: 'diagnose-every-miss', focus: 'Concept, translation, process, reading, calculator, and timing errors'},
            {title: 'Retake Missed Questions', slug: 'retake-missed-questions', focus: 'Delayed redo, explain-back, variants, and proof of mastery'},
            {title: 'Build a Weekly Weakness Map', slug: 'build-a-weekly-weakness-map', focus: 'Use evidence to balance skills, difficulty, accuracy, and speed'},
            {title: 'Bluebook Practice Test Handoff', slug: 'bluebook-practice-test-handoff', focus: 'Full-length timing, My Practice review, and the next study cycle'},
        ],
    },
];
