import {
    Calculator,
    Compass,
    Flame,
    FunctionSquare,
    LineChart,
    Sigma,
    Target,
    Triangle,
} from 'lucide-react';

export const STUDY_GUIDE_MODULES = [
    {
        id: 'math-map',
        domain: 'Orientation',
        title: 'Digital SAT Math Map',
        summary: 'Know the section format, domain weights, and the study loop before you start grinding questions.',
        icon: Compass,
        accent: 'bg-primary-100 text-primary-700',
        time: '25 min',
        pages: [
            {
                title: 'How Digital SAT Math Works',
                slug: 'how-digital-sat-math-works',
                focus: 'Format, timing, and adaptive modules',
            },
            {title: 'The Four Math Domains', focus: 'What appears most often'},
            {title: 'How to Study With SAT Duel', focus: 'Review misses, then practice targeted reps'},
        ],
    },
    {
        id: 'linear-equations',
        domain: 'Algebra',
        title: 'Linear Equations and Inequalities',
        summary: 'Build clean equation habits so easy Algebra questions become automatic points.',
        icon: Sigma,
        accent: 'bg-cyan-100 text-cyan-700',
        time: '45 min',
        pages: [
            {title: 'One-Variable Equations', focus: 'Fractions, parentheses, and signs'},
            {title: 'Linear Inequalities', focus: 'Graph, interval, and flip rules'},
            {title: 'Equations With Parameters', focus: 'Constants that stand in for numbers'},
            {title: 'Word Problems to Equations', focus: 'Rates, totals, and constraints'},
            {title: 'No-Solution and Infinite-Solution Cases', focus: 'When equations collapse'},
        ],
    },
    {
        id: 'linear-functions-systems',
        domain: 'Algebra',
        title: 'Linear Functions and Systems',
        summary: 'Connect lines, tables, systems, and word problems as the same relationship in different forms.',
        icon: LineChart,
        accent: 'bg-emerald-100 text-emerald-700',
        time: '55 min',
        pages: [
            {title: 'Slope as Rate of Change', focus: 'Units, steepness, and direction'},
            {title: 'Intercepts as Starting Values', focus: 'What each intercept means'},
            {title: 'Tables to Equations', focus: 'Constant change to linear models'},
            {title: 'Systems as Intersections', focus: 'Substitution, elimination, and graphs'},
            {title: 'Parallel and Perpendicular Lines', focus: 'Slope relationships in disguise'},
        ],
    },
    {
        id: 'quadratic-foundations',
        domain: 'Advanced Math',
        title: 'Quadratic Foundations',
        summary: 'Learn what each quadratic form reveals so you stop expanding when factoring would be faster.',
        icon: FunctionSquare,
        accent: 'bg-amber-100 text-amber-700',
        time: '60 min',
        pages: [
            {title: 'Standard, Factored, and Vertex Form', focus: 'Choose the useful form first'},
            {title: 'Factoring Patterns', focus: 'GCF, difference of squares, and trinomials'},
            {title: 'Completing the Square', focus: 'Turn standard form into vertex form'},
            {title: 'The Quadratic Formula', focus: 'Use it when structure is hidden'},
            {title: 'Discriminant Meaning', focus: 'Number of real solutions'},
        ],
    },
    {
        id: 'quadratic-graphs',
        domain: 'Advanced Math',
        title: 'Quadratic Graphs and Features',
        summary: 'Read a parabola through zeros, vertex, symmetry, and context instead of memorizing graph facts.',
        icon: FunctionSquare,
        accent: 'bg-orange-100 text-orange-700',
        time: '55 min',
        pages: [
            {title: 'Zeros, Intercepts, and Roots', focus: 'Same idea, different language'},
            {title: 'Vertex and Axis of Symmetry', focus: 'Maximum, minimum, and midpoint'},
            {title: 'Transformations of Parabolas', focus: 'Shift, stretch, and reflect'},
            {title: 'Quadratic Word Problems', focus: 'Area, projectile, and revenue models'},
            {title: 'Quadratic Systems', focus: 'Line-parabola intersections'},
        ],
    },
    {
        id: 'nonlinear-equations',
        domain: 'Advanced Math',
        title: 'Nonlinear Equations and Functions',
        summary: 'Handle absolute value, polynomial, rational, radical, and mixed systems without guessing.',
        icon: FunctionSquare,
        accent: 'bg-fuchsia-100 text-fuchsia-700',
        time: '65 min',
        pages: [
            {title: 'Function Notation', focus: 'Inputs, outputs, and compositions'},
            {title: 'Absolute Value Equations', focus: 'Distance from zero and split cases'},
            {title: 'Polynomial Structure', focus: 'Factors, zeros, and end behavior'},
            {title: 'Rational Equations', focus: 'Restrictions and cross-multiplying'},
            {title: 'Radical Equations', focus: 'Isolate, square, then check'},
        ],
    },
    {
        id: 'exponential-models',
        domain: 'Advanced Math',
        title: 'Exponential and Growth Models',
        summary: 'Recognize repeated multiplication, percent change, and hidden growth factors in context.',
        icon: FunctionSquare,
        accent: 'bg-lime-100 text-lime-700',
        time: '45 min',
        pages: [
            {title: 'Growth Factors', focus: 'Percent increase and decrease'},
            {title: 'Exponential Tables', focus: 'Common ratios and models'},
            {title: 'Linear vs. Exponential', focus: 'Additive change vs. multiplicative change'},
            {title: 'Equivalent Exponential Forms', focus: 'Rewrite bases and exponents'},
            {title: 'Model Interpretation', focus: 'Initial value, factor, and units'},
        ],
    },
    {
        id: 'advanced-expression-fluency',
        domain: 'Advanced Math',
        title: 'Expression Fluency',
        summary: 'Make equivalent expressions feel mechanical so SAT answer choices look familiar.',
        icon: Sigma,
        accent: 'bg-sky-100 text-sky-700',
        time: '50 min',
        pages: [
            {title: 'Expanding and Combining Like Terms', focus: 'Clean algebra bookkeeping'},
            {title: 'Factoring by Structure', focus: 'Spot the useful pattern'},
            {title: 'Rational Expressions', focus: 'Cancel only common factors'},
            {title: 'Radical and Exponent Rules', focus: 'Rewrite without changing value'},
            {title: 'Answer Choice Matching', focus: 'Transform until one choice matches'},
        ],
    },
    {
        id: 'ratios-percent-units',
        domain: 'Problem-Solving and Data Analysis',
        title: 'Ratios, Percentages, and Units',
        summary: 'Turn word problems into ratios, unit rates, and percent relationships with the right denominator.',
        icon: Target,
        accent: 'bg-rose-100 text-rose-700',
        time: '50 min',
        pages: [
            {title: 'Ratios and Proportions', focus: 'Part-to-part and part-to-whole'},
            {title: 'Unit Rates', focus: 'Per, each, and every'},
            {title: 'Percent Of', focus: 'Base, percent, and amount'},
            {title: 'Percent Change', focus: 'Increase, decrease, and multiplier'},
            {title: 'Unit Conversion', focus: 'Cancel units across steps'},
        ],
    },
    {
        id: 'statistics-probability',
        domain: 'Problem-Solving and Data Analysis',
        title: 'Statistics, Probability, and Inference',
        summary: 'Read data displays carefully and know what a statistic can and cannot prove.',
        icon: Target,
        accent: 'bg-teal-100 text-teal-700',
        time: '55 min',
        pages: [
            {title: 'One-Variable Data', focus: 'Mean, median, range, and spread'},
            {title: 'Two-Way Tables', focus: 'Conditional percentages'},
            {title: 'Scatterplots and Models', focus: 'Trend, association, and fit'},
            {title: 'Probability Basics', focus: 'Counts, complements, and conditions'},
            {title: 'Samples and Claims', focus: 'Margin of error and study design'},
        ],
    },
    {
        id: 'triangles-similarity',
        domain: 'Geometry and Trigonometry',
        title: 'Lines, Angles, Triangles, and Similarity',
        summary: 'Use angle facts and proportional reasoning before reaching for formulas.',
        icon: Triangle,
        accent: 'bg-violet-100 text-violet-700',
        time: '60 min',
        pages: [
            {title: 'Parallel Lines and Angle Chasing', focus: 'Supplementary, vertical, and corresponding angles'},
            {title: 'Triangle Angle Sums', focus: 'Interior and exterior angle facts'},
            {title: 'Special Triangles', focus: '30-60-90 and 45-45-90'},
            {title: 'Similarity', focus: 'Scale factors and proportional sides'},
            {title: 'Triangle Inequality', focus: 'Possible side lengths'},
        ],
    },
    {
        id: 'circles-coordinate-geometry',
        domain: 'Geometry and Trigonometry',
        title: 'Circles and Coordinate Geometry',
        summary: 'Connect circle facts to equations, distance, midpoint, and slope on the coordinate plane.',
        icon: Triangle,
        accent: 'bg-indigo-100 text-indigo-700',
        time: '60 min',
        pages: [
            {title: 'Circle Parts', focus: 'Radius, diameter, arcs, and sectors'},
            {title: 'Circumference and Area', focus: 'Formula choice and units'},
            {title: 'Circle Equations', focus: 'Center, radius, and graph features'},
            {title: 'Distance and Midpoint', focus: 'Coordinate geometry essentials'},
            {title: 'Slope in Geometry', focus: 'Parallel, perpendicular, and collinear points'},
        ],
    },
    {
        id: 'area-volume-trig',
        domain: 'Geometry and Trigonometry',
        title: 'Area, Volume, and Right-Triangle Trig',
        summary: 'Organize shape formulas and use trig as side-ratio language, not a separate mystery topic.',
        icon: Triangle,
        accent: 'bg-stone-100 text-stone-700',
        time: '60 min',
        pages: [
            {title: 'Area Formulas', focus: 'Triangles, rectangles, circles, and composites'},
            {title: 'Volume Formulas', focus: 'Prisms, cylinders, pyramids, cones, and spheres'},
            {title: 'Unit Changes in Geometry', focus: 'Square and cubic units'},
            {title: 'Sine, Cosine, and Tangent', focus: 'Right-triangle side ratios'},
            {title: 'Trig in Context', focus: 'Angles of elevation and missing sides'},
        ],
    },
    {
        id: 'calculator-mixed-review',
        domain: 'Strategy',
        title: 'Calculator Strategy and Mixed Review',
        summary: 'Use the calculator when it saves time, then practice switching topics like the real test.',
        icon: Calculator,
        accent: 'bg-slate-100 text-slate-700',
        time: '70 min',
        pages: [
            {title: 'When Graphing Beats Algebra', focus: 'Intersections and visual checks'},
            {title: 'Tables and Answer Testing', focus: 'Fast checks for function behavior'},
            {title: 'Calculator Traps', focus: 'Do not graph one-step algebra'},
            {title: 'Mixed 10-Question Sets', focus: 'Switch topics without labels'},
            {title: 'Hard Module 2 Finish Round', focus: 'Skip, estimate, solve, or verify'},
        ],
    },
    {
        id: 'review-system',
        domain: 'Review',
        title: 'Mistake Review System',
        summary: 'Turn missed questions into a short list of fixable habits instead of vague frustration.',
        icon: Flame,
        accent: 'bg-red-100 text-red-700',
        time: '35 min',
        pages: [
            {title: 'Error Log Categories', focus: 'Concept, setup, algebra, reading, or timing'},
            {title: 'Retake Missed Questions', focus: 'Redo without looking at the solution'},
            {title: 'Weekly Weakness Map', focus: 'Pick the next module from evidence'},
            {title: 'Bluebook Practice Test Handoff', focus: 'When to test full length'},
        ],
    },
];
