/**
 * Metadata for every public, indexable route — the single source of truth for
 * three consumers that used to drift apart:
 *
 *   1. <SEO> tags rendered at runtime (what Google sees after it runs the JS)
 *   2. public/sitemap.xml            (generated by scripts/prerender.mjs)
 *   3. the prerendered static HTML   (what link-preview crawlers see, since
 *                                     they never run the JS at all)
 *
 * Plain ES module with no JSX or React imports on purpose: scripts/prerender.mjs
 * imports it directly under Node at build time.
 *
 * Adding a public page means adding it here. Login-gated routes must NOT be
 * listed — they render <SEO noindex> instead.
 */

export const SITE_URL = 'https://satduel.com';
export const SITE_NAME = 'SAT Duel';
export const DEFAULT_IMAGE = '/og/default.png';

export const SEO_ROUTES = [
    {
        key: 'home',
        path: '/',
        title: 'SAT Duel - Turn Digital SAT Practice Into a Duel',
        description: 'Train with 1,800+ Digital SAT questions, challenge friends in timed rounds, review AI explanations, and track every mistake across Math and Reading & Writing.',
        image: '/og/default.png',
    },
    {
        key: 'digitalSatPractice',
        path: '/digital-sat-practice',
        title: 'Digital SAT Practice That Keeps You Moving',
        description: 'Practice Digital SAT questions one at a time, see your rating change, and build a daily study habit with SAT Duel.',
        image: '/og/practice.png',
        type: 'article',
    },
    {
        key: 'satMath',
        path: '/sat-math-practice',
        title: 'SAT Math Practice for the Digital SAT',
        description: 'Practice SAT Math questions with adaptive difficulty, clear feedback, and a rating that moves as you improve.',
        image: '/og/math.png',
        type: 'article',
    },
    {
        key: 'satReadingWriting',
        path: '/sat-reading-and-writing-practice',
        title: 'SAT Reading and Writing Practice',
        description: 'Build Digital SAT Reading and Writing skills with short questions, clear explanations, and focused practice loops.',
        image: '/og/english.png',
        type: 'article',
    },
    {
        key: 'wordsInContext',
        path: '/sat-vocabulary-words-in-context',
        title: 'SAT Words in Context Practice',
        description: 'Practice SAT Words in Context questions by learning how sentence logic, contrast, and tone point to the right answer.',
        image: '/og/english.png',
        type: 'article',
    },
    {
        key: 'scoreGuide',
        path: '/digital-sat-score-guide',
        title: 'How to Improve Your Digital SAT Score',
        description: 'A practical Digital SAT score improvement guide: diagnose your level, practice weak skills, review misses, and keep a steady habit.',
        image: '/og/practice.png',
        type: 'article',
    },
    {
        key: 'partyGame',
        path: '/sat-party-game',
        title: 'SAT Party Game: Play SAT Questions With Friends Live',
        description: 'Host a live SAT game for your class or friends. Share a room code, answer real SAT questions together, and watch the scoreboard update in real time. Free to play.',
        image: '/og/party.png',
        type: 'article',
    },
    {
        key: 'tournaments',
        path: '/sat-tournaments',
        title: 'SAT Tournaments and Competitions for Schools and Clubs',
        description: 'Run an SAT competition for your class, club, or whole school. Create a tournament, share one join link, and follow a live leaderboard as students answer.',
        image: '/og/tournaments.png',
        type: 'article',
    },
    {
        key: 'studyGuide',
        path: '/sat-study-guide',
        title: 'Free Digital SAT Study Guide: Math and English Lessons',
        description: 'A complete Digital SAT study guide covering Math and Reading & Writing in order, with short lessons that build on each other so you always know what to learn next.',
        image: '/og/studyGuide.png',
        type: 'article',
    },
    {
        key: 'diagnostic',
        path: '/diagnostic',
        title: 'Free Digital SAT Diagnostic',
        description: 'Answer three SAT Duel questions and get a quick, honest estimate of your Digital SAT practice level.',
        image: '/og/diagnostic.png',
    },
    {
        key: 'pricing',
        path: '/pricing',
        title: 'SAT Duel Pricing',
        description: 'Start SAT Duel for free or upgrade to Premium for unlimited Digital SAT practice and focused topic selection.',
        image: '/og/default.png',
    },
    {
        key: 'about',
        path: '/about',
        title: 'About SAT Duel',
        description: 'Meet the SAT Duel team and the mission behind a focused, competitive Digital SAT practice platform.',
        image: '/og/default.png',
    },
    // Indexable but never shared, so they inherit the default card. Copy matches
    // LEGAL_DOCS in src/pages/LegalPage.jsx.
    {key: 'terms', path: '/terms', title: 'Terms of Service', description: 'The rules for using SAT Duel.', image: DEFAULT_IMAGE},
    {key: 'privacy', path: '/privacy', title: 'Privacy Policy', description: 'How SAT Duel collects, uses, and protects information.', image: DEFAULT_IMAGE},
    {key: 'refunds', path: '/refund-policy', title: 'Refund and Cancellation Policy', description: 'How SAT Duel handles Premium cancellations and refund requests.', image: DEFAULT_IMAGE},
];

/** Look up one route's metadata by key. Throws early on a typo. */
export function seoMeta(key) {
    const found = SEO_ROUTES.find((r) => r.key === key);
    if (!found) throw new Error(`Unknown SEO route key: ${key}`);
    return found;
}
