/**
 * Post-build step: emit a static HTML file per public route, and the sitemap.
 *
 * Why this exists
 * ---------------
 * Link-preview crawlers (Discord, iMessage, Slack, X, WhatsApp) never run
 * JavaScript, so they only ever see the HTML the server hands back. For an SPA
 * that is always index.html, which means every URL previewed as the site-wide
 * default no matter which page it pointed at — the per-route <SEO> tags are
 * written by react-helmet after the crawler has already left.
 *
 * So for each route in src/seo/routes.js we write build/<path>/index.html: a
 * byte-for-byte copy of the built index.html with only the <head> metadata
 * swapped. Netlify serves an existing file before applying the
 * `/* /index.html 200` SPA fallback in public/_redirects, so crawlers get the
 * right tags while humans still get the identical SPA bundle and React routes
 * as normal.
 *
 * This is deliberately NOT full server-side rendering: <div id="root"> stays
 * empty and the body is untouched. Google renders the JS to see page content;
 * everything that matters to a preview lives in the head.
 */
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';

import {SEO_ROUTES, SHARE_ROUTES, SITE_URL, SITE_NAME} from '../src/seo/routes.js';

const BUILD = fileURLToPath(new URL('../build', import.meta.url));

const escapeAttr = (s) =>
    s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const absolute = (path) => `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;

/** Title as <SEO> would render it, so prerendered and runtime tags agree. */
const fullTitle = (title) => (title.includes(SITE_NAME) ? title : `${title} | ${SITE_NAME}`);

export function headFor(route) {
    const title = escapeAttr(fullTitle(route.title));
    const description = escapeAttr(route.description);
    const canonical = absolute(route.path);
    const image = absolute(route.image);

    // Share cards are login-gated: they exist so a pasted link unfurls properly,
    // not to be indexed. No canonical either — it would contradict noindex.
    const indexing = route.noindex
        ? '    <meta data-rh="true" name="robots" content="noindex,nofollow"/>'
        : `    <meta data-rh="true" name="robots" content="index,follow"/>\n`
          + `    <link data-rh="true" rel="canonical" href="${canonical}"/>`;

    // data-rh marks each tag as react-helmet-async's to own: on mount it
    // replaces these in place instead of appending a second, conflicting copy.
    // Without it every page ships two <link rel="canonical"> tags.
    return `    <meta data-rh="true" name="description" content="${description}"/>
${indexing}
    <meta data-rh="true" property="og:site_name" content="${SITE_NAME}"/>
    <meta data-rh="true" property="og:type" content="${route.type || 'website'}"/>
    <meta data-rh="true" property="og:title" content="${title}"/>
    <meta data-rh="true" property="og:description" content="${description}"/>
    <meta data-rh="true" property="og:url" content="${canonical}"/>
    <meta data-rh="true" property="og:image" content="${image}"/>
    <meta data-rh="true" property="og:image:type" content="image/png"/>
    <meta data-rh="true" property="og:image:width" content="1200"/>
    <meta data-rh="true" property="og:image:height" content="630"/>
    <meta data-rh="true" property="og:image:alt" content="${title}"/>
    <meta data-rh="true" name="twitter:card" content="summary_large_image"/>
    <meta data-rh="true" name="twitter:title" content="${title}"/>
    <meta data-rh="true" name="twitter:description" content="${description}"/>
    <meta data-rh="true" name="twitter:image" content="${image}"/>
    <title>${title}</title>`;
}

const START = '<!-- seo:start';
const END = '<!-- seo:end -->';

/** Swap the marked metadata block in the built index.html for this route's. */
export function render(shell, route) {
    const from = shell.indexOf(START);
    const to = shell.indexOf(END);

    if (from === -1 || to === -1 || to < from) {
        throw new Error(
            'prerender: the seo:start / seo:end markers are missing from index.html. ' +
            'They delimit the block this script rewrites — put them back.'
        );
    }

    return shell.slice(0, from) + headFor(route).trimStart() + shell.slice(to + END.length);
}

export function sitemap() {
    const urls = SEO_ROUTES
        .map((r) => `  <url><loc>${absolute(r.path)}</loc></url>`)
        .join('\n');
    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs from src/seo/routes.js. Do not edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

async function main() {
    const shell = await readFile(join(BUILD, 'index.html'), 'utf8');

    const shareRoutes = SHARE_ROUTES.map((r) => ({...r, noindex: true}));
    for (const route of [...SEO_ROUTES, ...shareRoutes]) {
        if (route.path === '/') continue;  // that IS build/index.html
        const dir = join(BUILD, route.path);
        await mkdir(dir, {recursive: true});
        await writeFile(join(dir, 'index.html'), render(shell, route));
    }

    // The home route rewrites the shell itself, so do it last.
    const home = SEO_ROUTES.find((r) => r.path === '/');
    await writeFile(join(BUILD, 'index.html'), render(shell, home));

    // Only public routes belong in the sitemap; share cards are noindex.
    await writeFile(join(BUILD, 'sitemap.xml'), sitemap());

    console.log(
        `prerendered ${SEO_ROUTES.length} public + ${shareRoutes.length} share routes, + sitemap.xml`
    );
}

// Importable for tests; only builds when run as a script.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
    main();
}
